In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option("display.max_row",50)
pd.set_option("display.max_columns",130)

In [ ]:
# LOUIS
data_louis_orig = pd.read_csv("C:/Users/Christian/Desktop/IRIS_BV_final/Bureau_de_votes_louis/CORRIGER_VERSION_2/Geo_bureaux_de_vote_access.txt",sep=";", header=0, dtype=str)
data_louis = data_louis_orig.copy()
print(data_louis.shape)
data_louis.iloc[70045:70045+1,:]

(70048, 25)

,commune_code,libelle,code,code_corr,Code du bvote,Code du bvote_sans 0 devant,libelle_bv,num_voie,voie,complement1,complement2,lieu_dit,code_postal,commune,canton_code,circonscription_code,longitude,latitude,geo_score,geo_type,geo_adresse,geo_id,geo_ligne,geo_l4,geo_l5
70045,14563,Saint-Benoît-d'Hébertot,001,NaN,0001,1,SAINT BENOIT D'HEBERTOT,185,route de l'Eglise,Mairie,NaN,NaN,14130,SAINT BENOIT D'HEBERTOT,14-21,14-04,0.27055,49.316366,0.62,street,Chemin de l'Eglise 14130 Saint-Benoît-d'Hébertot,14563_396noi,G,CHEMIN DE L EGLISE,NaN

In [ ]:
#########################################################################################
#                               DOUBLONS ET NAN COORDONEEES
#########################################################################################
#louis_sans_doublons= data_louis
louis_sans_doublons= data_louis.drop_duplicates(subset=["code","longitude","latitude"])
print(louis_sans_doublons.shape)
louis_sans_doublons = louis_sans_doublons[louis_sans_doublons["latitude"].isnull()==False]
print(louis_sans_doublons.shape)

(61568, 25)
(60998, 25)

In [ ]:
###################### CODES EN FRANCE METROPOLITAINE ##################

louis_sans_nan_doublons_sup_97501 = louis_sans_doublons.copy()
temp_sup_97501 = 0
temp_lettre = 0
for k in louis_sans_doublons["commune_code"].value_counts().index:
    try:
        temp_k = int(k)
        if (temp_k >= 97000):
            temp_sup_97501 = temp_sup_97501 + 1
            print(temp_k)
            louis_sans_nan_doublons_sup_97501 = louis_sans_nan_doublons_sup_97501[louis_sans_nan_doublons_sup_97501["commune_code"]!=k]
            
    except:
        temp_lettre = temp_lettre +1
        #print(k)

97411
97415
97416
97422
97209
97414
97412
97101
97409
97410
97413
97418
97407
97408
97420
97213
97611
97128
97107
97103
97117
97118
97113
97302
97120
97116
97222
97228
97115
97404
97125
97210
97405
97307
97224
97401
97105
97230
97309
97304
97604
97132
97207
97229
97220
97610
97602
97124
97614
97603
97311
97227
97212
97221
97605
97223
97612
97617
97601
97119
97608
97421
97616
97607
97305
97424
97121
97102
97114
97423
97214
97106
97104
97217
97417
97403
97606
97109
97615
97111
97226
97122
97112
97609
97225
97406
97204
97216
97218
97205
97206
97134
97203
97613
97202
97126
97360
97310
97306
97234
97110
97313
97231
97133
97356
97312
97362
97301
97108
97201
97131
97308
97129
97232
97419
97130
97219
97314
97402
97352
97233
97361
97357
97211
98734
97358
97208
97215

In [ ]:
louis_sans_nan_doublons_sup_97501["CHR_CODE"] = louis_sans_nan_doublons_sup_97501["commune_code"]+louis_sans_nan_doublons_sup_97501["Code du bvote_sans 0 devant"]
louis_sans_nan_doublons_sup_97501.head(1)

,commune_code,libelle,code,code_corr,Code du bvote,Code du bvote_sans 0 devant,libelle_bv,num_voie,voie,complement1,complement2,lieu_dit,code_postal,commune,canton_code,circonscription_code,longitude,latitude,geo_score,geo_type,geo_adresse,geo_id,geo_ligne,geo_l4,geo_l5,CHR_CODE
0,59350,Lille,807,NaN,0807,807,ECOLE AMPERE,64,RUE D'IENA,NaN,NaN,NaN,59000,LILLE,59-27,59-11,3.043027,50.621124,0.96,street,Rue d'Iena 59000 Lille,59350_4658,G,RUE D IENA,NaN,59350807

In [ ]:
# SANS DOUBLONS "CHR_CODE"
louis_sans_nan_doublons_sup_97501 = louis_sans_nan_doublons_sup_97501.drop_duplicates(subset=["CHR_CODE"])
louis_sans_nan_doublons_sup_97501.shape

(59098, 26)

In [ ]:
70048-69959

89

In [ ]:
# vérification 1
print(louis_sans_nan_doublons_sup_97501["geo_score"].isnull().sum())
louis_sans_nan_doublons_sup_97501[louis_sans_nan_doublons_sup_97501["geo_score"].isnull()]

6

,commune_code,libelle,code,code_corr,Code du bvote,Code du bvote_sans 0 devant,libelle_bv,num_voie,voie,complement1,complement2,lieu_dit,code_postal,commune,canton_code,circonscription_code,longitude,latitude,geo_score,geo_type,geo_adresse,geo_id,geo_ligne,geo_l4,geo_l5,CHR_CODE
17059,69283,Mions,2,NaN,0002,2,"""Bureau 2",GS Joliot Curie,"Restaurant""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,69-94,69-11,NaN,NaN,0,NaN,NaN,NaN,NaN,692832
36115,64489,Saint-Martin-d'Arberoue,1,NaN,0001,1,BUREAU UNIQUE,NaN,NaN,"""Mairie","le bourg""","""Mairie","le bourg""",NaN,64640,Saint-Martin-d'Arberoue,64-22,64-04,NaN,NaN,0,NaN,NaN,NaN,NaN,644891
52325,69283,Mions,9,NaN,0009,9,"""Bureau 9",GS Joliot Curie,"Préau primaire""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,69-94,69-11,NaN,NaN,0,NaN,NaN,NaN,NaN,692839
57313,69283,Mions,3,NaN,0003,3,"""Bureau 3",GS Joseph Sibuet,"Restaurant""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,69-94,69-11,NaN,NaN,0,NaN,NaN,NaN,NaN,692833
57346,69283,Mions,4,NaN,0004,4,"""Bureau 4",GS Pasteur,"Salle d'évolution""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,69-94,69-11,NaN,NaN,0,NaN,NaN,NaN,NaN,692834
57543,69283,Mions,5,NaN,0005,5,"""Bureau 5",Centre Culturel Jean Moulin,"Salle n°3""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,69-94,69-11,NaN,NaN,0,NaN,NaN,NaN,NaN,692835

In [ ]:
# index
louis_sans_nan_doublons_sup_97501[louis_sans_nan_doublons_sup_97501["geo_score"].isnull()]
index_elim=louis_sans_nan_doublons_sup_97501[louis_sans_nan_doublons_sup_97501["geo_score"].isnull()].index

In [ ]:
# effacer
for i in index_elim:
    louis_sans_nan_doublons_sup_97501 =  louis_sans_nan_doublons_sup_97501.drop(i,0)

In [ ]:
# vérification 2
louis_sans_nan_doublons_sup_97501["geo_score"].isnull().sum()

0

In [ ]:
# CORRECTION D'UNE LIGNE
louis_sans_nan_doublons_sup_97501[louis_sans_nan_doublons_sup_97501["libelle_bv"]=="ANCIENNE CURE"]

,commune_code,libelle,code,code_corr,Code du bvote,Code du bvote_sans 0 devant,libelle_bv,num_voie,voie,complement1,complement2,lieu_dit,code_postal,commune,canton_code,circonscription_code,longitude,latitude,geo_score,geo_type,geo_adresse,geo_id,geo_ligne,geo_l4,geo_l5,CHR_CODE
45678,85151,Mortagne-sur-Sèvre,0004,NaN,0004,4,ANCIENNE CURE,NaN,1 rue du Centre,Evrunes,NaN,NaN,85290,MORTAGNE SUR SEVRE,85-11,85-04,-0.971915,47.000255,0.95,housenumber,1 Rue du Centre 85290 Mortagne-sur-Sèvre,85151_0150_00001,G,1 RUE DU CENTRE,NaN,851514
65731,42154,Néronde,1,NaN,0001,1,ANCIENNE CURE,42510,NERONDE,NaN,NaN,NaN,42510,NÉRONDE,42-04,42-06,2.127469,22.927179,0.93,municipality,Néronde,42154,G,NERONDE,NaN,421541

In [ ]:
louis_sans_nan_doublons_sup_97501.loc[65731,"longitude"] = 4.236545
louis_sans_nan_doublons_sup_97501.loc[65731,"latitude"] = 45.838744

In [ ]:
# VERIFICATION
louis_sans_nan_doublons_sup_97501[louis_sans_nan_doublons_sup_97501["libelle_bv"]=="ANCIENNE CURE"]

,commune_code,libelle,code,code_corr,Code du bvote,Code du bvote_sans 0 devant,libelle_bv,num_voie,voie,complement1,complement2,lieu_dit,code_postal,commune,canton_code,circonscription_code,longitude,latitude,geo_score,geo_type,geo_adresse,geo_id,geo_ligne,geo_l4,geo_l5,CHR_CODE
45678,85151,Mortagne-sur-Sèvre,0004,NaN,0004,4,ANCIENNE CURE,NaN,1 rue du Centre,Evrunes,NaN,NaN,85290,MORTAGNE SUR SEVRE,85-11,85-04,-0.971915,47.000255,0.95,housenumber,1 Rue du Centre 85290 Mortagne-sur-Sèvre,85151_0150_00001,G,1 RUE DU CENTRE,NaN,851514
65731,42154,Néronde,1,NaN,0001,1,ANCIENNE CURE,42510,NERONDE,NaN,NaN,NaN,42510,NÉRONDE,42-04,42-06,4.236545,45.838744,0.93,municipality,Néronde,42154,G,NERONDE,NaN,421541

In [ ]:
# PIERRE
bv_euro_brut = pd.read_csv("C:/Users/Christian/Desktop/IRIS_BV_final/Bureau_de_votes_louis/CORRIGER_VERSION_2/Resultats-definitifs-par-bureau-de-vote_access.txt",sep=";",header=0, dtype=str,encoding="iso-8859-1")
bv_euro =bv_euro_brut.copy()
print(bv_euro.shape )
bv_euro.head(1)

(69297, 226)

,Code_INSEE,Code_commune,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Code du bvote,Code du bvote_sans 0 devant,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,% Blancs/Vot,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,N°Liste_1,Libellé Abrégé Liste_1,Nom Tête de Liste_1,Voix_1,% Voix/Ins_1,% Voix/Exp_1,N°Liste_2,Libellé Abrégé Liste_2,Nom Tête de Liste_2,Voix_2,% Voix/Ins_2,% Voix/Exp_2,N°Liste_3,Libellé Abrégé Liste_3,Nom Tête de Liste_3,Voix_3,% Voix/Ins_3,% Voix/Exp_3,N°Liste_4,Libellé Abrégé Liste_4,Nom Tête de Liste_4,Voix_4,% Voix/Ins_4,% Voix/Exp_4,N°Liste_5,Libellé Abrégé Liste_5,Nom Tête de Liste_5,Voix_5,% Voix/Ins_5,% Voix/Exp_5,N°Liste_6,Libellé Abrégé Liste_6,Nom Tête de Liste_6,Voix_6,% Voix/Ins_6,% Voix/Exp_6,N°Liste_7,Libellé Abrégé Liste_7,Nom Tête de Liste_7,Voix_7,% Voix/Ins_7,% Voix/Exp_7,N°Liste_8,...,Libellé Abrégé Liste_24,Nom Tête de Liste_24,Voix_24,% Voix/Ins_24,% Voix/Exp_24,N°Liste_25,Libellé Abrégé Liste_25,Nom Tête de Liste_25,Voix_25,% Voix/Ins_25,% Voix/Exp_25,N°Liste_26,Libellé Abrégé Liste_26,Nom Tête de Liste_26,Voix_26,% Voix/Ins_26,% Voix/Exp_26,N°Liste_27,Libellé Abrégé Liste_27,Nom Tête de Liste_27,Voix_27,% Voix/Ins_27,% Voix/Exp_27,N°Liste_28,Libellé Abrégé Liste_28,Nom Tête de Liste_28,Voix_28,% Voix/Ins_28,% Voix/Exp_28,N°Liste_29,Libellé Abrégé Liste_29,Nom Tête de Liste_29,Voix_29,% Voix/Ins_29,% Voix/Exp_29,N°Liste_30,Libellé Abrégé Liste_30,Nom Tête de Liste_30,Voix_30,% Voix/Ins_30,% Voix/Exp_30,N°Liste_31,Libellé Abrégé Liste_31,Nom Tête de Liste_31,Voix_31,% Voix/Ins_31,% Voix/Exp_31,N°Liste_32,Libellé Abrégé Liste_32,Nom Tête de Liste_32,Voix_32,% Voix/Ins_32,% Voix/Exp_32,N°Liste_33,Libellé Abrégé Liste_33,Nom Tête de Liste_33,Voix_33,% Voix/Ins_33,% Voix/Exp_33,N°Liste_34,Libellé Abrégé Liste_34,Nom Tête de Liste_34,Voix_34,% Voix/Ins_34,% Voix/Exp_34
0,01004,01004,01,Ain,004,Ambérieu-en-Bugey,0008,8,978,476,"48,67",502,"51,33",16,"1,64","3,19",6,"0,61","1,20",480,"49,08","95,62",1,LA FRANCE INSOUMISE,AUBRY Manon,35,"3,58","7,29",2,UNE FRANCE ROYALE,DE PREVOISIN Robert,0,0,0,3,LA LIGNE CLAIRE,CAMUS Renaud,0,0,0,4,PARTI PIRATE,MARIE Florie,0,"0,00","0,00",5,RENAISSANCE,LOISEAU Nathalie,96,"9,82","20,00",6,DÉMOCRATIE REPRÉSENTATIVE,TRAORÉ Hamada,0,0,0,7,ENSEMBLE PATRIOTES,PHILIPPOT Florian,3,"0,31","0,63",8,...,NEUTRE ET ACTIF,CORBET Cathy Denise Ginette,0,0,0,25,RÉVOLUTIONNAIRE,SANCHEZ Antonio,0,0,0,26,ESPERANTO,DIEUMEGARD Pierre,0,"0,00","0,00",27,ÉVOLUTION CITOYENNE,CHALENÇON Christophe,0,0,0,28,ALLIANCE JAUNE,LALANNE Francis,3,"0,31","0,63",29,UNION DROITE-CENTRE,BELLAMY François-Xavier,50,"5,11","10,42",30,EUROPE ÉCOLOGIE,JADOT Yannick,66,"6,75","13,75",31,PARTI ANIMALISTE,THOUY Hélène,7,"0,72","1,46",32,LES OUBLIES DE L'EUROPE,BIDOU Olivier,2,"0,20","0,42",33,UDLEF,PERSON Christian Luc,0,0,0,34,EUROPE AU SERVICE PEUPLES,AZERGUI Nagib,1,"0,10","0,21"

In [ ]:
# EFFACER LES BV A L'ETRANGER
liste_a_effacer=["ZD","ZA","ZB","ZN","ZP","ZZ","ZM","ZC","ZX","ZS","ZW"]
inscrit_etranger=0
votant_etranger=0
for i in liste_a_effacer:
    inscrit_etranger = inscrit_etranger + bv_euro[bv_euro["Code du département"]==i]["Inscrits"].astype(int).sum()
    votant_etranger = votant_etranger + bv_euro[bv_euro["Code du département"]==i]["Votants"].astype(int).sum()
    
    bv_euro = bv_euro[bv_euro["Code du département"]!=i]
bv_euro.shape, inscrit_etranger, votant_etranger

((66578, 226), 3114713, 643090)

In [ ]:
## DROP COLONNES
bv_euro = bv_euro.iloc[:,:12]
bv_euro.head(1)

,Code_INSEE,Code_commune,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Code du bvote,Code du bvote_sans 0 devant,Inscrits,Abstentions,% Abs/Ins,Votants
0,01004,01004,01,Ain,004,Ambérieu-en-Bugey,0008,8,978,476,"48,67",502

In [ ]:
bv_euro["CHR_CODE"] = bv_euro["Code_commune"]+bv_euro["Code du bvote_sans 0 devant"]
bv_euro.head(1)

,Code_INSEE,Code_commune,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Code du bvote,Code du bvote_sans 0 devant,Inscrits,Abstentions,% Abs/Ins,Votants,CHR_CODE
0,01004,01004,01,Ain,004,Ambérieu-en-Bugey,0008,8,978,476,"48,67",502,010048

In [ ]:
jointure_interne = louis_sans_nan_doublons_sup_97501.merge(bv_euro, on = "CHR_CODE")
jointure_interne

,commune_code,libelle,code,code_corr,Code du bvote_x,Code du bvote_sans 0 devant_x,libelle_bv,num_voie,voie,complement1,complement2,lieu_dit,code_postal,commune,canton_code,circonscription_code,longitude,latitude,geo_score,geo_type,geo_adresse,geo_id,geo_ligne,geo_l4,geo_l5,CHR_CODE,Code_INSEE,Code_commune,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Code du bvote_y,Code du bvote_sans 0 devant_y,Inscrits,Abstentions,% Abs/Ins,Votants
0,59350,Lille,807,NaN,0807,807,ECOLE AMPERE,64,RUE D'IENA,NaN,NaN,NaN,59000,LILLE,59-27,59-11,3.043027,50.621124,0.96,street,Rue d'Iena 59000 Lille,59350_4658,G,RUE D IENA,NaN,59350807,59350,59350,59,Nord,350,Lille,0807,807,1476,956,"64,77",520
1,50502,Saint-Lô,008,NaN,0008,8,HARAS-Ecurie n°5 (BV 08),NaN,Rue de la Goubedière,HARAS-Ecurie n°5,NaN,NaN,50000,SAINT LO,50-23,50-01,-1.074428,49.117378,0.95,street,Rue de la Goubediere 50000 Saint-Lô,50502_1162,G,RUE DE LA GOUBEDIERE,NaN,505028,50502,50502,50,Manche,502,Saint-Lô,0008,8,815,470,"57,67",345
2,56121,Lorient,11,NaN,0011,11,GROUPE SCOLAIRE MERVILLE,1,AVENUE DE LA MARNE,NaN,NaN,NaN,56100,LORIENT,56-09,56-05,-3.36822,47.744513,0.96,housenumber,1 Avenue de la Marne 56100 Lorient,56121_3890_00001,G,1 AVENUE DE LA MARNE,NaN,5612111,56121,56121,56,Morbihan,121,Lorient,0011,11,868,374,"43,09",494
3,76558,Saint-Aubin-Celloville,1,NaN,0001,1,Bureau 1,NaN,Mairie de SAINT-AUBIN-CELLOVILLE,NaN,NaN,NaN,76520,SAINT-AUBIN-CELLOVILLE,76-06,76-02,1.156093,49.365456,0.92,street,Place de la Mairie 76520 Saint-Aubin-Celloville,76558_0035,G,PLACE DE LA MAIRIE,NaN,765581,76558,76558,76,Seine-Maritime,558,Saint-Aubin-Celloville,0001,1,808,326,"40,35",482
4,70407,Perrouse,1,NaN,0001,1,BUREAU UNIQUE,NaN,Mairie de PERROUSE,NaN,NaN,NaN,70190,PERROUSE,70-12,70-01,6.050185,47.361279,0.9,street,Rue de la Mairie 70190 Perrouse,70407_0045,G,RUE DE LA MAIRIE,NaN,704071,70407,70407,70,Haute-Saône,407,Perrouse,0001,1,208,81,"38,94",127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57431,77412,Saint-Germain-sur-École,1,NaN,0001,1,MAIRIE,NaN,Chemin des Portes,77930 SAINT GERMAIN SUR ECOLE,NaN,NaN,77930,SAINT-GERMAIN-SUR-ÉCOLE,77-07,77-01,2.509938,48.474254,0.93,street,Chemin des Portes 77930 Saint-Germain-sur-École,77412_0240,G,CHEMIN DES PORTES,NaN,774121,77412,77412,77,Seine-et-Marne,412,Saint-Germain-sur-Ecole,0001,1,295,144,"48,81",151
57432,67307,Mulhausen,01,NaN,0001,1,Bureau de vote 01,2,rue de la Mairie,NaN,NaN,NaN,67350,MULHAUSEN,67-08,67-07,7.551771,48.882282,0.94,housenumber,2 Rue de la Mairie 67350 Mulhausen,67307_0023_00002,G,2 RUE DE LA MAIRIE,NaN,673071,67307,67307,67,Bas-Rhin,307,Mulhausen,0001,1,353,113,"32,01",240
57433,02810,Villers-Cotterêts,007,NaN,0007,7,SALLE GERARD PHILIPE 1,NaN,Rue d'Artagnan,NaN,NaN,NaN,02600,VILLERS-COTTERETS,02-21,02-05,3.097397,49.260343,0.95,street,Rue d'Artagnan 02600 Villers-Cotterêts,02810_0051,G,RUE D ARTAGNAN,NaN,028107,02810,02810,02,Aisne,810,Villers-Cotterêts,0007,7,791,501,"63,34",290
57434,25040,Badevel,1,NaN,0001,1,Mairie,16,Grande Rue,25490 BADEVEL,NaN,NaN,25490,BADEVEL,25-01,25-04,6.939282,47.500913,0.94,housenumber,16 Grande Rue 25490 Badevel,25040_0113_00016,G,16 GRANDE RUE,NaN,250401,25040,25040,25,Doubs,040,Badevel,0001,1,551,256,"46,46",295
57435,14563,Saint-Benoît-d'Hébertot,001,NaN,0001,1,SAINT BENOIT D'HEBERTOT,185,route de l'Eglise,Mairie,NaN,NaN,14130,SAINT BENOIT D'HEBERTOT,14-21,14-04,0.27055,49.316366,0.62,street,Chemin de l'Eglise 14130 Saint-Benoît-d'Hébertot,14563_396noi,G,CHEMIN DE L EGLISE,NaN,145631,14563,14563,14,Calvados,563,Saint-Benoît-d'Hébertot,0001,1,309,147,"47,57",162

In [ ]:
data_louis_orig.shape, bv_euro.shape

((70048, 25), (66578, 13))

In [ ]:
inscri_total = bv_euro["Inscrits"].astype(int)
inscri_total.sum()

44230615

In [ ]:
inscri_recon = jointure_interne["Inscrits"].astype(int)
inscri_recon.sum()

39862311

In [ ]:
(44230615-39862311)/44230615

0.09876200003097402

In [ ]:
44230615 - 43269823, 961113 - 960792 # 961113 (taille de commune du fichier Pierre)

(960792, 321)

In [ ]:
################################ table_non_recon ###############################

In [ ]:
table_non_recon = bv_euro.merge(jointure_interne,on="CHR_CODE", how="left")[bv_euro.merge(jointure_interne,on="CHR_CODE", how="left")["Code_commune_y"].isnull()][["Code_commune_x","Libellé de la commune_x","Inscrits_x"] ] 
table_non_recon

      Code_commune_x Libellé de la commune_x Inscrits_x
4              01015         Arboys en Bugey        116
79             01045                 Birieux        200
113            01063                   Brion        379
118            01067                 Ceignes        208
124            01072               Ceyzériat       1055
...              ...                     ...        ...
66316          95447        Neuilly-en-Vexin        138
66352          95489                  Piscop        503
66360          95492       Le Plessis-Gassot         41
66389          95509       Puiseux-en-France        339
66515          95607                 Taverny        744

[9142 rows x 3 columns]

In [ ]:
table_non_recon["id"] = table_non_recon["Code_commune_x"]+table_non_recon["Libellé de la commune_x"]

In [ ]:
table_non_recon["Inscrits_x"] = table_non_recon["Inscrits_x"].astype(int)

In [ ]:
table_non_recon["id"].value_counts()

76351Le Havre                   112
30189Nîmes                       84
37261Tours                       84
84007Avignon                     70
17300La Rochelle                 40
                               ...
65439Tarasteix                    1
17484Port-des-Barques             1
60392Mélicocq                     1
25506Rougemontot                  1
23112Lourdoueix-Saint-Pierre      1
Name: id, Length: 6948, dtype: int64

In [ ]:
table_non_recon["Code_commune_x"].value_counts()

76351    112
30189     84
37261     84
84007     70
17300     40
        ...
64011      1
55060      1
42201      1
48174      1
85201      1
Name: Code_commune_x, Length: 6948, dtype: int64

In [ ]:
table_inscrit_x = table_non_recon.groupby(['Code_commune_x',"Libellé de la commune_x"]).sum().sort_values(by=['Inscrits_x'], ascending=False)
table_inscrit_x

                                        Inscrits_x
Code_commune_x Libellé de la commune_x
76351          Le Havre                     103885
30189          Nîmes                         87478
37261          Tours                         79122
84007          Avignon                       55029
17300          La Rochelle                   35932
...                                            ...
65379          Ris                              12
55394          Ornes                            11
52109          Charmes-en-l'Angle               11
26274          Rochefourchat                     8
54310          Leménil-Mitry                     5

[6948 rows x 1 columns]

In [ ]:
table_non_recon[table_non_recon["Code_commune_x"]=="76351"]["Inscrits_x"].sum()

103885

In [ ]:
bv_euro.shape

(66578, 13)

In [ ]:
57436+9142    #4368304 Inscrits_x"].astype(int).sum()

66578

In [ ]:

table_code_commune_x = pd.DataFrame(table_non_recon['Code_commune_x'].value_counts())
#table_code_commune_x
table_code_commune_x.rename(columns={'Code_commune_x':"Nb_non_reconcilies"}, inplace=True)
ttt= pd.DataFrame(table_code_commune_x.index,columns=["Code_commune_x"], index = range(table_code_commune_x.shape[0]))
#ttt

table_code_commune_x.index =range(table_code_commune_x.shape[0])
#table_code_commune_x
deux_col=pd.concat([ttt,table_code_commune_x], axis=1)
#deux_col
table_inscrit_x.merge(deux_col, on="Code_commune_x")

     Code_commune_x  Inscrits_x  Nb_non_reconcilies
0             76351      103885                 112
1             30189       87478                  84
2             37261       79122                  84
3             84007       55029                  70
4             17300       35932                  40
...             ...         ...                 ...
6943          65379          12                   1
6944          55394          11                   1
6945          52109          11                   1
6946          26274           8                   1
6947          54310           5                   1

[6948 rows x 3 columns]

In [ ]:
######################################################################
#                      ENREGISTREMENT
######################################################################
louis_sans_nan_doublons_sup_97501 = louis_sans_nan_doublons_sup_97501.drop(["CHR_CODE"], axis=1)
jointure_interne = jointure_interne.drop(["CHR_CODE"], axis=1)

louis_sans_nan_doublons_sup_97501.to_csv("C:/Users/Christian/Desktop/IRIS_BV_final/Bureau_de_votes_louis/CORRIGER_VERSION_2/louis_sans_nan_sans_doublons_FM.txt",sep=";", index=False)
jointure_interne.to_csv("C:/Users/Christian/Desktop/IRIS_BV_final/Bureau_de_votes_louis/CORRIGER_VERSION_2/jointure_sans_nan_sans_doublons_FM.txt",sep=";", index=False)

table_inscrit_x.to_csv("C:/Users/Christian/Desktop/IRIS_BV_final/Bureau_de_votes_louis/CORRIGER_VERSION_2/FM_commune_bv_non_reconciliees.txt",sep=";", index=False)

In [ ]:
###############################################################################################v
###############################################################################################