In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option("display.max_row",50)
pd.set_option("display.max_columns",130)

In [ ]:
# 6 PARTIES
"""
"LA FRANCE INSOUMISE"
"RENAISSANCE"
"ENVIE D'EUROPE"
"PRENEZ LE POUVOIR"
"UNION DROITE-CENTRE"
"EUROPE ÉCOLOGIE"

"""

'\n"LA FRANCE INSOUMISE"\n"RENAISSANCE"\n"ENVIE D\'EUROPE"\n"PRENEZ LE POUVOIR"\n"UNION DROITE-CENTRE"\n"EUROPE ÉCOLOGIE"\n\n'

In [ ]:
data_premier_orig = pd.read_csv("C:/Users/Christian/Desktop/IRIS_BV_final/EUROPEEN/europeen_6_partis.txt",sep=";", header=0, dtype=str)
data_premier = data_premier_orig.copy()
data_premier

,Code du département,Libellé du département,Code de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11
0,01,Ain,-,001,L'Abergement-Clémenciat,0001,601,268,333,1,18,314,LA FRANCE INSOUMISE,AUBRY Manon,13,RENAISSANCE,LOISEAU Nathalie,64,ENVIE D'EUROPE,GLUCKSMANN Raphaël,18,PRENEZ LE POUVOIR,BARDELLA Jordan,78,UNION DROITE-CENTRE,BELLAMY François-Xavier,28,EUROPE ÉCOLOGIE,JADOT Yannick,52
1,01,Ain,-,002,L'Abergement-de-Varey,0001,210,69,141,4,2,135,LA FRANCE INSOUMISE,AUBRY Manon,6,RENAISSANCE,LOISEAU Nathalie,29,ENVIE D'EUROPE,GLUCKSMANN Raphaël,6,PRENEZ LE POUVOIR,BARDELLA Jordan,22,UNION DROITE-CENTRE,BELLAMY François-Xavier,16,EUROPE ÉCOLOGIE,JADOT Yannick,36
2,01,Ain,-,004,Ambérieu-en-Bugey,0001,1050,548,502,15,13,474,LA FRANCE INSOUMISE,AUBRY Manon,39,RENAISSANCE,LOISEAU Nathalie,67,ENVIE D'EUROPE,GLUCKSMANN Raphaël,21,PRENEZ LE POUVOIR,BARDELLA Jordan,130,UNION DROITE-CENTRE,BELLAMY François-Xavier,44,EUROPE ÉCOLOGIE,JADOT Yannick,48
3,01,Ain,-,004,Ambérieu-en-Bugey,0002,1106,527,579,15,24,540,LA FRANCE INSOUMISE,AUBRY Manon,42,RENAISSANCE,LOISEAU Nathalie,102,ENVIE D'EUROPE,GLUCKSMANN Raphaël,38,PRENEZ LE POUVOIR,BARDELLA Jordan,155,UNION DROITE-CENTRE,BELLAMY François-Xavier,44,EUROPE ÉCOLOGIE,JADOT Yannick,60
4,01,Ain,-,004,Ambérieu-en-Bugey,0003,1058,485,573,14,8,551,LA FRANCE INSOUMISE,AUBRY Manon,31,RENAISSANCE,LOISEAU Nathalie,107,ENVIE D'EUROPE,GLUCKSMANN Raphaël,42,PRENEZ LE POUVOIR,BARDELLA Jordan,134,UNION DROITE-CENTRE,BELLAMY François-Xavier,44,EUROPE ÉCOLOGIE,JADOT Yannick,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69292,ZZ,Français établis hors de France,-,227,Yaounde,0001,1474,1156,318,4,2,312,LA FRANCE INSOUMISE,AUBRY Manon,21,RENAISSANCE,LOISEAU Nathalie,104,ENVIE D'EUROPE,GLUCKSMANN Raphaël,22,PRENEZ LE POUVOIR,BARDELLA Jordan,32,UNION DROITE-CENTRE,BELLAMY François-Xavier,40,EUROPE ÉCOLOGIE,JADOT Yannick,63
69293,ZZ,Français établis hors de France,-,228,Zagreb,0001,707,576,131,1,1,129,LA FRANCE INSOUMISE,AUBRY Manon,4,RENAISSANCE,LOISEAU Nathalie,36,ENVIE D'EUROPE,GLUCKSMANN Raphaël,8,PRENEZ LE POUVOIR,BARDELLA Jordan,27,UNION DROITE-CENTRE,BELLAMY François-Xavier,10,EUROPE ÉCOLOGIE,JADOT Yannick,14
69294,ZZ,Français établis hors de France,-,229,Zurich,0001,21276,15923,5353,11,96,5246,LA FRANCE INSOUMISE,AUBRY Manon,139,RENAISSANCE,LOISEAU Nathalie,2391,ENVIE D'EUROPE,GLUCKSMANN Raphaël,337,PRENEZ LE POUVOIR,BARDELLA Jordan,275,UNION DROITE-CENTRE,BELLAMY François-Xavier,376,EUROPE ÉCOLOGIE,JADOT Yannick,1132
69295,ZZ,Français établis hors de France,-,231,Taipeh,0001,1384,1018,366,1,6,359,LA FRANCE INSOUMISE,AUBRY Manon,27,RENAISSANCE,LOISEAU Nathalie,113,ENVIE D'EUROPE,GLUCKSMANN Raphaël,12,PRENEZ LE POUVOIR,BARDELLA Jordan,23,UNION DROITE-CENTRE,BELLAMY François-Xavier,24,EUROPE ÉCOLOGIE,JADOT Yannick,74
69296,ZZ,Français établis hors de France,-,233,Nur Sultan,0001,101,67,34,0,0,34,LA FRANCE INSOUMISE,AUBRY Manon,0,RENAISSANCE,LOISEAU Nathalie,14,ENVIE D'EUROPE,GLUCKSMANN Raphaël,1,PRENEZ LE POUVOIR,BARDELLA Jordan,1,UNION DROITE-CENTRE,BELLAMY François-Xavier,4,EUROPE ÉCOLOGIE,JADOT Yannick,10

In [ ]:
data_premier = data_premier[["Code du département","Libellé du département","Code de la circonscription",
"Code de la commune","Libellé de la commune","Code du bvote","Inscrits","Abstentions",
"Votants","Blancs","Nuls","Exprimés",
"Nom_1","Prénom_1","Voix_1",
"Nom_2","Prénom_2","Voix_2",
"Nom_3","Prénom_3","Voix_3",
"Nom_4","Prénom_4","Voix_4",
"Nom_9","Prénom_9","Voix_9",
"Nom_11","Prénom_11","Voix_11"]]

In [ ]:

#EFFACER LES BV A L'ETRANGER
liste_a_effacer=["ZD","ZA","ZB","ZN","ZP","ZZ","ZM","ZC","ZX","ZS","ZW"]
for i in liste_a_effacer:
    data_premier = data_premier[data_premier["Code du département"]!=i]
print(data_premier.shape)
print(len(data_premier["Code du département"].unique()))

(66578, 30)
96

In [ ]:
data_premier["Code du bvote_sans 0 devant"] = data_premier["Code du bvote"].copy()
data_premier.head(4)

,Code du département,Libellé du département,Code de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11,Code du bvote_sans 0 devant
0,01,Ain,-,001,L'Abergement-Clémenciat,0001,601,268,333,1,18,314,LA FRANCE INSOUMISE,AUBRY Manon,13,RENAISSANCE,LOISEAU Nathalie,64,ENVIE D'EUROPE,GLUCKSMANN Raphaël,18,PRENEZ LE POUVOIR,BARDELLA Jordan,78,UNION DROITE-CENTRE,BELLAMY François-Xavier,28,EUROPE ÉCOLOGIE,JADOT Yannick,52,0001
1,01,Ain,-,002,L'Abergement-de-Varey,0001,210,69,141,4,2,135,LA FRANCE INSOUMISE,AUBRY Manon,6,RENAISSANCE,LOISEAU Nathalie,29,ENVIE D'EUROPE,GLUCKSMANN Raphaël,6,PRENEZ LE POUVOIR,BARDELLA Jordan,22,UNION DROITE-CENTRE,BELLAMY François-Xavier,16,EUROPE ÉCOLOGIE,JADOT Yannick,36,0001
2,01,Ain,-,004,Ambérieu-en-Bugey,0001,1050,548,502,15,13,474,LA FRANCE INSOUMISE,AUBRY Manon,39,RENAISSANCE,LOISEAU Nathalie,67,ENVIE D'EUROPE,GLUCKSMANN Raphaël,21,PRENEZ LE POUVOIR,BARDELLA Jordan,130,UNION DROITE-CENTRE,BELLAMY François-Xavier,44,EUROPE ÉCOLOGIE,JADOT Yannick,48,0001
3,01,Ain,-,004,Ambérieu-en-Bugey,0002,1106,527,579,15,24,540,LA FRANCE INSOUMISE,AUBRY Manon,42,RENAISSANCE,LOISEAU Nathalie,102,ENVIE D'EUROPE,GLUCKSMANN Raphaël,38,PRENEZ LE POUVOIR,BARDELLA Jordan,155,UNION DROITE-CENTRE,BELLAMY François-Xavier,44,EUROPE ÉCOLOGIE,JADOT Yannick,60,0002

In [ ]:
data_premier = data_premier.drop(51452,0)
data_premier.iloc[51452-2:51452+2,:]

,Code du département,Libellé du département,Code de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11,Code du bvote_sans 0 devant
51450,74,Haute-Savoie,-,314,Vulbens,0001,855,415,440,8,7,425,LA FRANCE INSOUMISE,AUBRY Manon,13,RENAISSANCE,LOISEAU Nathalie,114,ENVIE D'EUROPE,GLUCKSMANN Raphaël,20,PRENEZ LE POUVOIR,BARDELLA Jordan,61,UNION DROITE-CENTRE,BELLAMY François-Xavier,55,EUROPE ÉCOLOGIE,JADOT Yannick,76,0001
51451,74,Haute-Savoie,-,315,Yvoire,0001,726,358,368,9,4,355,LA FRANCE INSOUMISE,AUBRY Manon,27,RENAISSANCE,LOISEAU Nathalie,96,ENVIE D'EUROPE,GLUCKSMANN Raphaël,22,PRENEZ LE POUVOIR,BARDELLA Jordan,36,UNION DROITE-CENTRE,BELLAMY François-Xavier,25,EUROPE ÉCOLOGIE,JADOT Yannick,71,0001
51453,75,Paris,-,056,Paris,0101,1061,425,636,4,5,627,LA FRANCE INSOUMISE,AUBRY Manon,15,RENAISSANCE,LOISEAU Nathalie,238,ENVIE D'EUROPE,GLUCKSMANN Raphaël,59,PRENEZ LE POUVOIR,BARDELLA Jordan,48,UNION DROITE-CENTRE,BELLAMY François-Xavier,76,EUROPE ÉCOLOGIE,JADOT Yannick,100,0101
51454,75,Paris,-,056,Paris,0102,1207,519,688,2,4,682,LA FRANCE INSOUMISE,AUBRY Manon,27,RENAISSANCE,LOISEAU Nathalie,286,ENVIE D'EUROPE,GLUCKSMANN Raphaël,48,PRENEZ LE POUVOIR,BARDELLA Jordan,38,UNION DROITE-CENTRE,BELLAMY François-Xavier,60,EUROPE ÉCOLOGIE,JADOT Yannick,134,0102

In [ ]:
# CORRIGER PARIS
for i in range(data_premier.shape[0]):
    if data_premier.iloc[i,1]=="Paris":
        data_premier.iloc[i,3]=str(75100+int(data_premier.iloc[i,5][:2]))[2:]
    if data_premier.iloc[i,4]=="Lyon":
        data_premier.iloc[i,3]=str(69380+int(data_premier.iloc[i,5][:2]))[2:]
    if data_premier.iloc[i,4]=="Marseille":
        data_premier.iloc[i,3]=str(13200+int(data_premier.iloc[i,5][:2]))[2:]

In [ ]:
for i in data_premier.index :
    if data_premier.loc[i,"Code du bvote_sans 0 devant"][0]=="0":
        data_premier.loc[i,"Code du bvote_sans 0 devant"] = data_premier.loc[i,"Code du bvote_sans 0 devant"][1:]
        if data_premier.loc[i,"Code du bvote_sans 0 devant"][0] =="0":
            data_premier.loc[i,"Code du bvote_sans 0 devant"] = data_premier.loc[i,"Code du bvote_sans 0 devant"][1:]
            if data_premier.loc[i,"Code du bvote_sans 0 devant"][0] =="0":
                data_premier.loc[i,"Code du bvote_sans 0 devant"] = data_premier.loc[i,"Code du bvote_sans 0 devant"][1:]

In [ ]:
data_premier

,Code du département,Libellé du département,Code de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11,Code du bvote_sans 0 devant
0,01,Ain,-,001,L'Abergement-Clémenciat,0001,601,268,333,1,18,314,LA FRANCE INSOUMISE,AUBRY Manon,13,RENAISSANCE,LOISEAU Nathalie,64,ENVIE D'EUROPE,GLUCKSMANN Raphaël,18,PRENEZ LE POUVOIR,BARDELLA Jordan,78,UNION DROITE-CENTRE,BELLAMY François-Xavier,28,EUROPE ÉCOLOGIE,JADOT Yannick,52,1
1,01,Ain,-,002,L'Abergement-de-Varey,0001,210,69,141,4,2,135,LA FRANCE INSOUMISE,AUBRY Manon,6,RENAISSANCE,LOISEAU Nathalie,29,ENVIE D'EUROPE,GLUCKSMANN Raphaël,6,PRENEZ LE POUVOIR,BARDELLA Jordan,22,UNION DROITE-CENTRE,BELLAMY François-Xavier,16,EUROPE ÉCOLOGIE,JADOT Yannick,36,1
2,01,Ain,-,004,Ambérieu-en-Bugey,0001,1050,548,502,15,13,474,LA FRANCE INSOUMISE,AUBRY Manon,39,RENAISSANCE,LOISEAU Nathalie,67,ENVIE D'EUROPE,GLUCKSMANN Raphaël,21,PRENEZ LE POUVOIR,BARDELLA Jordan,130,UNION DROITE-CENTRE,BELLAMY François-Xavier,44,EUROPE ÉCOLOGIE,JADOT Yannick,48,1
3,01,Ain,-,004,Ambérieu-en-Bugey,0002,1106,527,579,15,24,540,LA FRANCE INSOUMISE,AUBRY Manon,42,RENAISSANCE,LOISEAU Nathalie,102,ENVIE D'EUROPE,GLUCKSMANN Raphaël,38,PRENEZ LE POUVOIR,BARDELLA Jordan,155,UNION DROITE-CENTRE,BELLAMY François-Xavier,44,EUROPE ÉCOLOGIE,JADOT Yannick,60,2
4,01,Ain,-,004,Ambérieu-en-Bugey,0003,1058,485,573,14,8,551,LA FRANCE INSOUMISE,AUBRY Manon,31,RENAISSANCE,LOISEAU Nathalie,107,ENVIE D'EUROPE,GLUCKSMANN Raphaël,42,PRENEZ LE POUVOIR,BARDELLA Jordan,134,UNION DROITE-CENTRE,BELLAMY François-Xavier,44,EUROPE ÉCOLOGIE,JADOT Yannick,97,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66573,95,Val-d'Oise,-,680,Villiers-le-Bel,0011,1244,820,424,16,5,403,LA FRANCE INSOUMISE,AUBRY Manon,72,RENAISSANCE,LOISEAU Nathalie,40,ENVIE D'EUROPE,GLUCKSMANN Raphaël,32,PRENEZ LE POUVOIR,BARDELLA Jordan,104,UNION DROITE-CENTRE,BELLAMY François-Xavier,19,EUROPE ÉCOLOGIE,JADOT Yannick,30,11
66574,95,Val-d'Oise,-,680,Villiers-le-Bel,0012,843,513,330,9,9,312,LA FRANCE INSOUMISE,AUBRY Manon,46,RENAISSANCE,LOISEAU Nathalie,44,ENVIE D'EUROPE,GLUCKSMANN Raphaël,26,PRENEZ LE POUVOIR,BARDELLA Jordan,72,UNION DROITE-CENTRE,BELLAMY François-Xavier,17,EUROPE ÉCOLOGIE,JADOT Yannick,27,12
66575,95,Val-d'Oise,-,680,Villiers-le-Bel,0013,726,539,187,6,4,177,LA FRANCE INSOUMISE,AUBRY Manon,39,RENAISSANCE,LOISEAU Nathalie,21,ENVIE D'EUROPE,GLUCKSMANN Raphaël,17,PRENEZ LE POUVOIR,BARDELLA Jordan,31,UNION DROITE-CENTRE,BELLAMY François-Xavier,2,EUROPE ÉCOLOGIE,JADOT Yannick,9,13
66576,95,Val-d'Oise,-,682,Villiers-le-Sec,0001,109,46,63,2,0,61,LA FRANCE INSOUMISE,AUBRY Manon,5,RENAISSANCE,LOISEAU Nathalie,14,ENVIE D'EUROPE,GLUCKSMANN Raphaël,1,PRENEZ LE POUVOIR,BARDELLA Jordan,6,UNION DROITE-CENTRE,BELLAMY François-Xavier,7,EUROPE ÉCOLOGIE,JADOT Yannick,10,1
66577,95,Val-d'Oise,-,690,Wy-dit-Joli-Village,0001,295,121,174,0,3,171,LA FRANCE INSOUMISE,AUBRY Manon,7,RENAISSANCE,LOISEAU Nathalie,44,ENVIE D'EUROPE,GLUCKSMANN Raphaël,7,PRENEZ LE POUVOIR,BARDELLA Jordan,25,UNION DROITE-CENTRE,BELLAMY François-Xavier,18,EUROPE ÉCOLOGIE,JADOT Yannick,29,1

In [ ]:
# IL N'Y A PAS DE DOUBLONS

In [ ]:
data_premier["commune_code"]=data_premier["Code du département"]+data_premier["Code de la commune"]
data_premier.head(1)

,Code du département,Libellé du département,Code de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11,Code du bvote_sans 0 devant,commune_code
0,01,Ain,-,001,L'Abergement-Clémenciat,0001,601,268,333,1,18,314,LA FRANCE INSOUMISE,AUBRY Manon,13,RENAISSANCE,LOISEAU Nathalie,64,ENVIE D'EUROPE,GLUCKSMANN Raphaël,18,PRENEZ LE POUVOIR,BARDELLA Jordan,78,UNION DROITE-CENTRE,BELLAMY François-Xavier,28,EUROPE ÉCOLOGIE,JADOT Yannick,52,1,01001

In [ ]:
########################################################################
data_recensement_orig = pd.read_csv("C:/Users/Christian/Desktop/IRIS_BV_final/PRESIDENTIELLES/RECENSEMENT_IRIS__BV_reconcialiation.txt",sep=";", header=0, low_memory=False, dtype=str)
data_recensement = data_recensement_orig.copy()
data_recensement = data_recensement[data_recensement["ID_BV"]!="4145"]
print(data_recensement.shape)
data_recensement.head(1)

(78397, 81)

,IRIS,ID_BV,commune_code,libelle,code,Code du bvote,Code du bvote_sans 0 devant,libelle_bv,num_voie,voie,code_postal,commune,canton_code,circonscription_code,longitude,latitude,geo_score,C17_MEN,C17_MENPSEUL,C17_MENHSEUL,C17_MENFSEUL,C17_MENSFAM,C17_MENFAM,C17_MENCOUPSENF,C17_MENCOUPAENF,C17_MENFAMMONO,C17_PMEN,C17_PMEN_MENPSEUL,C17_PMEN_MENHSEUL,C17_PMEN_MENFSEUL,C17_PMEN_MENSFAM,C17_PMEN_MENFAM,C17_PMEN_MENCOUPSENF,C17_PMEN_MENCOUPAENF,C17_PMEN_MENFAMMONO,P17_POP15P,P17_POP1524,P17_POP2554,P17_POP5579,P17_POP80P,P17_POPMEN15P,P17_POPMEN1524,P17_POPMEN2554,P17_POPMEN5579,P17_POPMEN80P,P17_POP15P_PSEUL,P17_POP1524_PSEUL,P17_POP2554_PSEUL,P17_POP5579_PSEUL,P17_POP80P_PSEUL,P17_POP15P_MARIEE,P17_POP15P_PACSEE,P17_POP15P_CONCUB_UNION_LIBRE,P17_POP15P_VEUFS,P17_POP15P_DIVORCEE,P17_POP15P_CELIBATAIRE,C17_MEN_CS1,C17_MEN_CS2,C17_MEN_CS3,C17_MEN_CS4,C17_MEN_CS5,C17_MEN_CS6,C17_MEN_CS7,C17_MEN_CS8,C17_PMEN_CS1,C17_PMEN_CS2,C17_PMEN_CS3,C17_PMEN_CS4,C17_PMEN_CS5,C17_PMEN_CS6,C17_PMEN_CS7,C17_PMEN_CS8,C17_FAM,C17_COUPAENF,C17_FAMMONO,C17_COUPSENF,C17_NE24F0,C17_NE24F1,C17_NE24F2,C17_NE24F3,C17_NE24F4P
0,721910000,17428,72191,Mayet,1,0001,1,ECOLE ST EXUPERY NORD,NaN,Rue Paul FOURNIER,72360,MAYET,72-08,72-03,0.271986000000000,47.759019000000002,0.94,1372.65678220089,447.579121498123,172.928296942457,274.650824555666,25.0027324900068,900.074928212759,503.362514570496,331.497706032145,65.2147076101184,3032.89428399957,447.579121498123,172.928296942457,274.650824555666,69.8756207737611,2515.43954172768,1056.07476690597,1299.08322648915,160.28154833256,2586.4560091875,246.675066330521,1042.37837329437,920.389018607399,377.01355095521,2476.44042734743,246.675066330521,1042.37837329437,908.3873187703,278.999668952236,455.716923707181,13.2239285897173,125.118708964248,194.290027741231,123.084258411984,1288.91525550116,84.530200374592,324.373782323855,305.360627814329,136.621543950553,446.654599223008,35.2223295589629,85.279155520177,24.8624749303227,124.925647361331,194.850379405266,275.1411906951,591.734387098183,40.6412176315461,75.1515734910646,209.166325355455,84.1941983749051,357.77696798547,561.762877007348,755.406582053172,943.756209133682,45.6795505984689,900.074928212759,331.497706032145,65.2147076101184,503.362514570496,528.317902752867,135.04120453251,173.183821580618,49.0227639293319,14.5092354174314

In [ ]:
data_recensement=data_recensement[["IRIS","ID_BV","commune_code","libelle","Code du bvote_sans 0 devant","longitude","latitude"]]

for i in data_recensement.columns:
    data_recensement.loc[:,i]=data_recensement.loc[:,i].astype(str)

In [ ]:
data_recensement.info()
data_recensement.head(1)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 78397 entries, 0 to 78397
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IRIS                         78397 non-null  object
 1   ID_BV                        78397 non-null  object
 2   commune_code                 78397 non-null  object
 3   libelle                      78397 non-null  object
 4   Code du bvote_sans 0 devant  78397 non-null  object
 5   longitude                    78397 non-null  object
 6   latitude                     78397 non-null  object
dtypes: object(7)
memory usage: 4.8+ MB

,IRIS,ID_BV,commune_code,libelle,Code du bvote_sans 0 devant,longitude,latitude
0,721910000,17428,72191,Mayet,1,0.271986000000000,47.759019000000002

In [ ]:
# PAS DE 0
for i in data_recensement.index :
    try :
        data_recensement.loc[i,"Code du bvote_sans 0 devant"] = str(int(data_recensement.loc[i,"Code du bvote_sans 0 devant"]))
    except:
        continue
        
print((data_recensement["Code du bvote_sans 0 devant"]=="01").sum())

0

In [ ]:
for i in data_recensement.index :
    try:
        int(data_recensement.loc[i,"Code du bvote_sans 0 devant"])
    except:
        print(data_recensement.loc[i,"Code du bvote_sans 0 devant"])

1-1
1 - 2
1 - 1
L-2
L-1
L-3
1 - 2
24.1
1 - 1
1 - 1
17-84
17-81
17-82
17-83
18-43
18-41
18-42
16-11
16-42
16-13
16-41
16-43
16-12
15-36
15-35
15-33
15-31
15-32
15-37
15-34
1 - 2
1 - 1
1 - 1
2 - 1
1 - 2
1-2
1 - 1
1 - 1
1 - 1
1 - 1
2 - 2
2 - 1
1 - 1
1 - 1
1 - 1
2-1
1-1
1 - 2
83A
2-1
1-1
1-2
BUR
1 - 1
B04
1 - 2
15-41
15-21
15-22
15-42
1 - 1
1 - 1
1 - 1
1 - 2
H21
H11
M1
1 - 1
1 - 2
A-1
A-2
17-41
17-42
1 - 1
1 - 1
1 - 1
1 - 2
1 - 1
1 - 2
2 - 2
1-2
1 - 2
1 - 1
1 - 1
1 - 1
1 - 1
1 - 1
1 - 2
1 - 1
1 - 2
1 - 1
1 - 2
1 - 2
1 - 1
1 - 1
1 - 1
1 - 2
1 - 1
1 - 2
1 - 1
1-1
1 - 2
1 - 1
1-2
1 - 1
B02
B01
1 - 2
1 - 2
1 - 1
1 - 1
1 - 2
1 - 2
1 - 1
1-2
2-2
M1
1A
6C
5C
4B
2A
3B
E-3
E-1
E-2
1 - 2
1 - 2
192A
1 - 1
1-1
A1
1-2
1 - 1
Bureau 1
Bureau 2
1-1
1 - 1
15-71
15-72
15-73
1 - 1
1 - 1
1LC
1 - 2
1 - 2
A2
A1
1 - 2
1 - 1
1 - 3
1 - 1
1 - 2
1 - 1
1 - 1
1 - 3
16-31
16-34
16-36
16-33
16-32
16-35
1 - 2
1-1
1 - 1
F31
F11
1 - 1
A1
1-1
1 - 1
1 - 1
1-1
1.1
3.1
3.2
1-2
A1
A2
1 - 2
1 - 1
1-1
2 - 2
1-1
10.3
10.2
10.1
1 - 2
1 - 3
1 - 1
1 - 2
1 - 2
1 - 2
1-2
1 - 1
B12
B13
1-2
1 - 2
2 - 2
1 - 2
1 - 1
1 - 1
1 - 1
15.1
15.2
B11
5C
1A
1D
1C
5A
1E
5B
1-2
1 - 1
K-1
K-2
1 - 1
1 - 1
15-57
15-58
15-55
15-51
15-52
15-53
15-54
15-56
A1
1 - 2
1 - 1
1 - 1
2 - 1
1 - 2
1 - 1
1-2
3-2
4-2
B-1
B-2
1 - 1
1 - 2
1 - 1
1 - 2
1 - 1
G-1
G-2
1-3
2-2
1 - 1
B07
1 - 1
1 - 1
1 - 3
1-2
1 - 2
2 - 2
1 - 1
2 - 1
1 - 2
2 - 2
B1
1 - 1
69A
1 - 1
1 - 1
1 - 1
B15
B14
1 - 2
1 - 1
112A
1 - 1
81A
1N
2N
1 - 1
1-1
1-2
1 - 1
4.1
4.2
4.3
4.4
182A
1 - 1
1 - 1
17-11
17-12
1 - 1
1 - 1
1 - 2
1-1
D11
1-2
1 - 2
1-2
1 - 1
1 - 1
1-1
1 - 1
F-1
F-2
1 - 2
1-1
1 - 1
1 - 1
D21
A11
A21
1 - 2
1 - 2
18-51
1 - 1
1 - 2
1 - 1
1 - 1
1-2
A1
1 - 2
1 - 1
1 - 1
2 - 1
A1
A2
1 - 1
unique
17-71
17-72
3C
3D
3B
3A
3E
1 - 2
B11
1 - 2
1 - 1
1 - 2
1 - 2
17-31
17-32
1 - 1
J-2
J-1
1- 1
19.2
19.1
19.3
1 - 1
17-52
17-51
17-53
1 - 1
1 - 1
1-2
B1
1 - 2
1 - 1
1 - 1
1 - 1
1 - 1
198A
23.1
23.2
23.3
1 - 1
1 - 1
2 - 2
2 - 1
1 - 2
1 - 2
C-3
D-1
D-2
C-2
D-3
1 - 1
1 - 1
20.1
18.1
18.2
18.3
1-1
1 - 1
1 - 2
7A
8A
1 - 1
1-2
1 - 2
1-3
1 - 3
1 - 2
1 - 1
1 - 2
18-24
18-21
18-25
18-22
18-23
1 - 3
1 - 2
1-1
1 - 1
1 - 2
1 - 1
C21
F21
G11
G21
1 - 3
1 - 1
1 - 1
1 - 2
1 - 1
1 - 1
1 - 1
1 - 2
1-2
1 - 2
1 - 1
1 - 1
1 - 1
1 - 1
1 - 2
1 - 1
1 - 2
1 - 2
1 - 1
2-2
1-2
1 - 2
B06
14.1
14.2
1 - 1
1 - 1
15-61
15-62
15-63
1-1
2-1
1-1
1 - 2
1 - 3
1 - 2
H-1
1 - 1
1 - 2
1 - 1
1 - 1
2S
1S
1 - 2
1 - 1
1-2
1C
4C
2C
3C
A1
18-31
1 - 1
1 - 1
C-1
2-2
1-2
3-2
3-3
4-3
4-2
1 - 2
1 - 1
1 - 2
1 - 1
1 - 1
1 - 2
1 - 3
2A
3A
4A
6A
5A
1A
1 - 1
1 - 1
16-61
16-62
1 - 2
1 - 1
22.1
22.2
1 - 1
1 - 1
1 - 1
1 - 2
1 - 1
1 - 2
1 - 1
1 - 1
1 - 2
1 - 1
M1 - 3
1 - 1
1 - 2
1 - 1
1 - 2
1 - 2
2.2
2.1
16-52
16-51
1 - 1
E31
E21
E11
E41
1 - 2
18-32
1 - 1
1 - 2
1 - 1
6.1
6.2
1 - 1
1 - 1
1 - 1
1 - 3
1 - 2
B08
18-64
18-62
18-61
18-63
1 - 1
1 - 1
1 - 1
1 - 1
1 - 1
11.3
11.1
11.2
1 - 1
15-82
15-81
1 - 2
B03
1-3
1-2
9.2
9.1
7.1
7.2
9.3
7.3
1 - 1
1-1
1 - 2
1 - 1
1 - 1
1 - 1
B01
B02
B03
B05
1 - 2
1 - 1
1 - 1
12.1
18-11
18-12
17-21
B1
1-1
1 - 1
1 - 1
17-62
17-63
17-61
17-64
1 - 1
1 - 2
1-1
1 - 2
38B
1B
1-1
1 - 2
1 - 2
21.1
21.2
1 - 1
1-2
1 - 2
16.2
16.1
16.3
16.4
1 - 1
1 -1
1 - 1
16-23
16-21
16-22
1 - 2
B05
B10
1 - 1
1 - 1
1-1
1 - 1
1-2
1 - 2
1-3
1 - 1
1 -1
1 - 2
1 - 2
1 - 1
1 - 3
1 - 1
1-3
N-1
N-2
1 - 1
1 - 1
1 - 1
2 -1
17.1
17.3
17.2
1 - 1
1 -1
1 - 1
1 - 1
1 - 2
1 - 2
1-2
1 - 1
1 - 1
A5
A1
A2
A6
A4
A3
1 - 2
1-2
1 - 1
1-1
1 - 1
3 - 1
4 - 1
2 - 1
13 - 2
3 - 1
B01
B05
B03
B04
B06
B02
1 - 1
1 - 2
1 - 1
1 - 2
1 - 1
1 - 1
1 - 1
Unique
UN
1 - 1
1 - 2
1 - 1
B04
1 - 1
15-11
13.3
13.1
13.2
C09
1 - 1
8.1
1 - 1
1 - 1
1 - 1
1-1
1-1
1-2
1 - 1
1-2
1 - 1
5.2
5.1
M-1
1 - 2
198A
unique
7.1
7.2
7.3
3C
3D
3B
3A
3E
E-3
E-1
E-2
1 - 1
16-23
16-21
16-22
1 - 1
1 - 1
2 - 2
A2
1 - 1
1 - 2
1 - 1
J-2
J-1
1-2
1A
6C
5C
4B
2A
3B
1 - 2
15-36
15-35
15-33
15-31
15-32
15-37
15-34
1 - 1
1 - 2
81A
16-52
16-51
K-1
K-2
4.1
4.2
4.3
4.4
18-64
18-62
18-61
18-63
69A
1 - 1
15-61
15-62
15-63
17-62
17-63
17-61
17-64
1-1
1 - 1
81A
3 - 1
4 - 1
1 - 1
1A
1D
1C
1E
1 - 2
14.1
14.2
18.1
18.2
18.3
F31
F11
22.1
22.2
5.2
5.1
3.1
3.2
3C
3D
3B
3A
3E
16-31
16-34
16-36
16-33
16-32
16-35
1 - 1
1 - 1
1 - 1
18-43
18-41
18-42
6.1
6.2
1 - 2
4.1
4.2
4.3
4.4
1 - 1
1 - 1
1 - 2
F31
F11
1 - 1
1 -1
1 - 2
112A
19.2
19.1
19.3
F31
F11
1-2
15.1
15.2
23.1
23.2
23.3
D11
1 - 1
16-31
16-34
16-36
16-33
16-32
16-35
1 - 2
1 -1
1-2
15-21
15-22
21.1
21.2
1 - 1
17.1
17.3
17.2
1 - 1
1 - 2
1 - 1
81A
18-11
18-12
1 - 1
17-11
17-12
1 - 2
1 - 1
1 - 1
15-57
15-58
15-55
15-51
15-52
15-53
15-54
15-56
1 - 2
18-51
1 - 1
1 - 1
1 - 2
1 - 1
1 - 1
1 - 1
10.3
10.2
10.1
112A
B11
16-61
16-62
1-2
1-2
1 - 2
2-2
15-57
15-58
15-55
15-51
15-52
15-53
15-54
15-56
5C
5A
5B
69A
1-2
17-62
17-63
17-61
17-64
16-52
16-51
1 - 2
7.1
7.2
7.3
1 - 2
1 - 1
1 - 2
81A
1 - 2
3-2
1 - 2
2 - 2
2 - 1
1 - 1
B10
5.2
5.1
13.3
13.1
13.2
1 - 2
17-71
17-72
B01
B05
B03
B04
B06
B02
1 - 1
A2
18-64
18-62
18-61
18-63
1-2
16.2
16.1
16.3
16.4
1B
1-1
1 - 2
20.1
1 - 2
1 - 2
1 - 1
16-42
16-41
16-43
23.1
23.2
23.3
1 - 1
1 - 2
1 - 1
1 - 2
20.1
1-2
1-1
17-41
17-42
1 - 1
15-36
15-35
15-33
15-31
15-32
15-37
15-34
1 - 1
1A
6C
5C
4B
2A
3B
1- 1
15-57
15-58
15-55
15-51
15-52
15-53
15-54
15-56
E31
E21
E11
E41
D-1
D-2
D-3
A1
1 -1
14.1
14.2
J-2
J-1
15-41
15-42
M1
1- 1
1-1
18-24
18-21
18-25
18-22
18-23
3.1
3.2
1 - 3
L-3
1 - 1
1-2
1 - 1
1 - 1
1A
1D
1C
1E
1 - 1
182A
1 - 1
15-57
15-58
15-55
15-51
15-52
15-53
15-54
15-56
1-2
2S
1S
1 - 1
7.1
7.2
7.3
1 - 1
18.1
18.2
18.3
B15
17-52
17-51
17-53
22.1
22.2
1 - 1
5C
5A
5B
1 - 1
1 - 1
1 - 1
1 - 2
15-41
15-42
7.1
7.2
7.3
1 - 1
1-2
1 - 1
16-31
16-34
16-36
16-33
16-32
16-35
B01
B05
B03
B04
B06
B02
A11
A21
1-1
1 - 1
1 - 2

In [ ]:

# 
print(data_premier.shape, data_recensement.shape)

data_premier.head(1)
data_recensement.head(1)

(66577, 32) (78397, 7)

,IRIS,ID_BV,commune_code,libelle,Code du bvote_sans 0 devant,longitude,latitude
0,721910000,17428,72191,Mayet,1,0.271986000000000,47.759019000000002

In [ ]:
####
CREATION=pd.read_csv("C:/Users/Christian/Desktop/IRIS_BV_final/PRESIDENTIELLES/CREATION/CREATION.txt",sep=";", header=0, dtype=str)
CREATION=CREATION[CREATION["ID_BV"]!="4145"]
CREATION.head(2)

CREATION["FLAG"]="0"

In [ ]:
jjj = data_recensement.merge(CREATION, how="left")
flag = jjj[jjj["longitude"].isnull()==False] # tous la

In [ ]:
flag_0 = flag[flag["FLAG"]=="0"] # ok
flag_1 = flag[flag["FLAG"]!="0"] # absent
#flag_1 = flag_1.fillna("1")

In [ ]:
flag_0["IRIS"].value_counts().shape[0]+flag_1["IRIS"].value_counts().shape[0]

48595

In [ ]:

IRIS_COMPLET = flag_0.merge(data_premier, on = ["commune_code","Code du bvote_sans 0 devant"],how= "left")
print(IRIS_COMPLET.shape)
IRIS_COMPLET.head(2)

(59032, 38)

,IRIS,ID_BV,commune_code,libelle,Code du bvote_sans 0 devant,longitude,latitude,FLAG,Code du département,Libellé du département,Code de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11
0,721910000,17428,72191,Mayet,1,0.271986000000000,47.759019000000002,0,72,Sarthe,-,191,Mayet,0001,1381,660,721,34,36,651,LA FRANCE INSOUMISE,AUBRY Manon,44,RENAISSANCE,LOISEAU Nathalie,94,ENVIE D'EUROPE,GLUCKSMANN Raphaël,31,PRENEZ LE POUVOIR,BARDELLA Jordan,242,UNION DROITE-CENTRE,BELLAMY François-Xavier,42,EUROPE ÉCOLOGIE,JADOT Yannick,67
1,721910000,55161,72191,Mayet,2,0.271986000000000,47.759019000000002,0,72,Sarthe,-,191,Mayet,0002,899,433,466,14,13,439,LA FRANCE INSOUMISE,AUBRY Manon,29,RENAISSANCE,LOISEAU Nathalie,66,ENVIE D'EUROPE,GLUCKSMANN Raphaël,31,PRENEZ LE POUVOIR,BARDELLA Jordan,149,UNION DROITE-CENTRE,BELLAMY François-Xavier,43,EUROPE ÉCOLOGIE,JADOT Yannick,39

In [ ]:
IRIS_COMPLET_OUI = IRIS_COMPLET[IRIS_COMPLET["Voix_11"].isnull()==False]
IRIS_COMPLET_NON = IRIS_COMPLET[IRIS_COMPLET["Voix_11"].isnull()] #absent

IRIS_COMPLET_OUI["IRIS"].value_counts().shape[0],IRIS_COMPLET_NON["IRIS"].value_counts().shape[0]

(36236, 1034)

In [ ]:
# CA VEUT DIRE QU'IL Y A DES IRIS DANS OUI ET NON
IRIS_COMPLET_OUI["IRIS"].value_counts().shape[0]+IRIS_COMPLET_NON["IRIS"].value_counts().shape[0]#-IRIS_COMPLET["IRIS"].value_counts().shape[0]

37270

In [ ]:
join_left = data_recensement.merge(IRIS_COMPLET_OUI, on="IRIS", how="left")
IRIS_A_COMPLETER = join_left[join_left["Voix_11"].isnull()][["IRIS","commune_code_x","libelle_x"]].drop_duplicates(subset="IRIS")
IRIS_A_COMPLETER.columns=["IRIS","commune_code","libelle"]
IRIS_A_COMPLETER

             IRIS commune_code                    libelle
23      231670000        23167                     Sannat
508     422620000        42262  Saint-Maurice-en-Gourgois
990     714540000        71454       Saint-Martin-du-Mont
1109    710410000        71041          Bois-Sainte-Marie
1121    593110000        59311                   Honnechy
...           ...          ...                        ...
160921  930050101        93005           Aulnay-sous-Bois
160923  910270114        91027                 Athis-Mons
160925  104300000        51377                 Montépreux
160926  394510000        39452                       Rans
160927  930010501        93001              Aubervilliers

[12354 rows x 3 columns]

In [ ]:
IRIS_COMPLET_OUI["IRIS"].value_counts().shape[0]+IRIS_A_COMPLETER["IRIS"].value_counts().shape[0]

48590

In [ ]:
pd.concat([IRIS_COMPLET_OUI,IRIS_A_COMPLETER], axis=0)["IRIS"].value_counts().shape[0]

48590

In [ ]:
IRIS_A_COMPLETER["IRIS"].value_counts().shape[0]

12354

In [ ]:
IRIS_COMPLET_OUI[IRIS_COMPLET_OUI["libelle"]=="Les Sables-d'Olonne"][["IRIS","Code du bvote_sans 0 devant","commune_code","Inscrits"]]#["Inscrits"].astype(int).sum()

            IRIS Code du bvote_sans 0 devant commune_code Inscrits
1216   851940301                          13        85194     1172
1217   851940301                          14        85194     1157
1218   851940301                          21        85194     1194
8446   851940103                           4        85194     1175
8447   851940103                           3        85194     1085
22719  851940204                          23        85194     1146
22720  851940204                          32        85194      843
22721  851940204                          31        85194     1157
22722  851940204                          24        85194     1337
22723  851940204                          25        85194     1113
26177  851940101                           8        85194     1159
30544  851940203                          33        85194     1170
31973  851940106                          11        85194     1185
31974  851940106                          12        85194     1149
31975  851940106                           5        85194     1230
34420  851940104                           1        85194     1134
34421  851940104                           2        85194     1077
34422  851940104                           9        85194     1045
34423  851940104                          10        85194     1290
35764  851940302                          17        85194     1424
35765  851940302                          22        85194      996
35766  851940302                          16        85194     1406
39907  851940303                          15        85194     1356
43825  851940305                          20        85194     1118
44045  851940201                           6        85194     1215
44046  851940201                          30        85194     1415
44047  851940201                          29        85194      841
44048  851940201                          28        85194      920
44049  851940201                          27        85194     1094
49393  851940102                           7        85194     1201
54712  851940304                          19        85194     1404
54713  851940304                          18        85194     1269
58978  851940205                          26        85194     1344

In [ ]:
data_premier[data_premier["Libellé de la commune"]=="Les Sables-d'Olonne"][["Code du bvote_sans 0 devant","commune_code","Inscrits"]]

      Code du bvote_sans 0 devant commune_code Inscrits
59841                           1        85194     1134
59842                           2        85194     1077
59843                           3        85194     1085
59844                           4        85194     1175
59845                           5        85194     1230
59846                           6        85194     1215
59847                           7        85194     1201
59848                           8        85194     1159
59849                           9        85194     1045
59850                          10        85194     1290
59851                          11        85194     1185
59852                          12        85194     1149
59853                          13        85194     1172
59854                          14        85194     1157
59855                          15        85194     1356
59856                          16        85194     1406
59857                          17        85194     1424
59858                          18        85194     1269
59859                          19        85194     1404
59860                          20        85194     1118
59861                          21        85194     1194
59862                          22        85194      996
59863                          23        85194     1146
59864                          24        85194     1337
59865                          25        85194     1113
59866                          26        85194     1344
59867                          27        85194     1094
59868                          28        85194      920
59869                          29        85194      841
59870                          30        85194     1415
59871                          31        85194     1157
59872                          32        85194      843
59873                          33        85194     1170

In [ ]:
###COMPLETER LES IRIS PAR LES COMMUNES : ON CHERCHE LES COMMUNES POUR LEQUELS IL Y A UNE SEUL BV
table_nb_bv_par_commune = CREATION[["commune_code","Code du bvote_sans 0 devant"]].groupby("commune_code", as_index=False).count()
table_nb_bv_par_commune.columns = ["commune_code","nb_bv_par_commune"]
table_nb_bv_par_commune

      commune_code  nb_bv_par_commune
0            01001                  1
1            01002                  1
2            01004                  8
3            01005                  1
4            01006                  1
...            ...                ...
29172        95676                  1
29173        95678                  1
29174        95680                 13
29175        95682                  1
29176        95690                  1

[29177 rows x 2 columns]

In [ ]:
# commune nb bv
table_1 = table_nb_bv_par_commune[table_nb_bv_par_commune["nb_bv_par_commune"]==1]
table_2 = table_nb_bv_par_commune[table_nb_bv_par_commune["nb_bv_par_commune"]!=1]
table_1

      commune_code  nb_bv_par_commune
0            01001                  1
1            01002                  1
3            01005                  1
4            01006                  1
6            01008                  1
...            ...                ...
29171        95675                  1
29172        95676                  1
29173        95678                  1
29175        95682                  1
29176        95690                  1

[23043 rows x 2 columns]

In [ ]:
# TEST
IRIS_A_COMPLETER.merge(table_1, how="left")

            IRIS commune_code                    libelle  nb_bv_par_commune
0      231670000        23167                     Sannat                1.0
1      422620000        42262  Saint-Maurice-en-Gourgois                1.0
2      714540000        71454       Saint-Martin-du-Mont                1.0
3      710410000        71041          Bois-Sainte-Marie                1.0
4      593110000        59311                   Honnechy                1.0
...          ...          ...                        ...                ...
12349  930050101        93005           Aulnay-sous-Bois                NaN
12350  910270114        91027                 Athis-Mons                NaN
12351  104300000        51377                 Montépreux                1.0
12352  394510000        39452                       Rans                1.0
12353  930010501        93001              Aubervilliers                NaN

[12354 rows x 4 columns]

In [ ]:
IRIS_A_COMPLETER_1 = IRIS_A_COMPLETER.merge(table_1) #, how="left")
IRIS_A_COMPLETER_2 = IRIS_A_COMPLETER.merge(table_2)
IRIS_A_COMPLETER_1

           IRIS commune_code                    libelle  nb_bv_par_commune
0     231670000        23167                     Sannat                  1
1     422620000        42262  Saint-Maurice-en-Gourgois                  1
2     714540000        71454       Saint-Martin-du-Mont                  1
3     710410000        71041          Bois-Sainte-Marie                  1
4     711410000        71041          Bois-Sainte-Marie                  1
...         ...          ...                        ...                ...
5586  574140000        57380   Laneuveville-lès-Lorquin                  1
5587  100850000        10085                    Charmoy                  1
5588  084700000        08098              Champigneulle                  1
5589  621620000        62286               Ecquedecques                  1
5590  050680000        05176                  Valserres                  1

[5591 rows x 4 columns]

In [ ]:
######################## RESULTATS PAR COMMUNE #########################
for k in ["Inscrits","Abstentions","Votants","Blancs","Nuls","Exprimés","Voix_1","Voix_2","Voix_3","Voix_4","Voix_9","Voix_11"]:
    data_premier.loc[:,k] = data_premier.loc[:,k].astype(float)

somme_commune = data_premier[["commune_code","Inscrits","Abstentions","Votants","Blancs","Nuls","Exprimés","Voix_1","Voix_2","Voix_3","Voix_4","Voix_9","Voix_11"]].groupby("commune_code", as_index=False).sum()
somme_commune

,commune_code,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,01001,601.0,268.0,333.0,1.0,18.0,314.0,13.0,64.0,18.0,78.0,28.0,52.0
1,01002,210.0,69.0,141.0,4.0,2.0,135.0,6.0,29.0,6.0,22.0,16.0,36.0
2,01004,8110.0,3975.0,4135.0,97.0,83.0,3955.0,307.0,726.0,230.0,1027.0,368.0,471.0
3,01005,1188.0,596.0,592.0,16.0,12.0,564.0,24.0,119.0,22.0,178.0,57.0,68.0
4,01006,100.0,34.0,66.0,1.0,0.0,65.0,2.0,12.0,2.0,16.0,9.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34869,95676,383.0,167.0,216.0,5.0,2.0,209.0,12.0,37.0,6.0,65.0,35.0,21.0
34870,95678,592.0,226.0,366.0,1.0,5.0,360.0,14.0,88.0,20.0,86.0,21.0,48.0
34871,95680,12288.0,8177.0,4111.0,120.0,97.0,3894.0,662.0,630.0,285.0,828.0,155.0,306.0
34872,95682,109.0,46.0,63.0,2.0,0.0,61.0,5.0,14.0,1.0,6.0,7.0,10.0
34873,95690,295.0,121.0,174.0,0.0,3.0,171.0,7.0,44.0,7.0,25.0,18.0,29.0

In [ ]:
# ON COMPLETE LES IRIS 

IRIS_COMPLET_1 = IRIS_A_COMPLETER_1.merge(somme_commune)
IRIS_COMPLET_1

,IRIS,commune_code,libelle,nb_bv_par_commune,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,231670000,23167,Sannat,1,298.0,139.0,159.0,14.0,7.0,138.0,13.0,33.0,9.0,26.0,12.0,15.0
1,422620000,42262,Saint-Maurice-en-Gourgois,1,1227.0,510.0,717.0,21.0,11.0,685.0,36.0,140.0,20.0,220.0,82.0,79.0
2,714540000,71454,Saint-Martin-du-Mont,1,132.0,51.0,81.0,4.0,5.0,72.0,3.0,14.0,2.0,13.0,11.0,15.0
3,710410000,71041,Bois-Sainte-Marie,1,83.0,37.0,46.0,4.0,1.0,41.0,3.0,10.0,0.0,10.0,4.0,3.0
4,711410000,71041,Bois-Sainte-Marie,1,83.0,37.0,46.0,4.0,1.0,41.0,3.0,10.0,0.0,10.0,4.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5586,574140000,57380,Laneuveville-lès-Lorquin,1,85.0,33.0,52.0,4.0,1.0,47.0,1.0,10.0,0.0,18.0,1.0,6.0
5587,100850000,10085,Charmoy,1,48.0,13.0,35.0,1.0,2.0,32.0,1.0,1.0,2.0,7.0,14.0,3.0
5588,084700000,08098,Champigneulle,1,54.0,18.0,36.0,1.0,1.0,34.0,0.0,8.0,0.0,13.0,2.0,2.0
5589,621620000,62286,Ecquedecques,1,359.0,152.0,207.0,7.0,8.0,192.0,10.0,29.0,8.0,73.0,16.0,17.0
5590,050680000,05176,Valserres,1,193.0,76.0,117.0,4.0,2.0,111.0,13.0,21.0,6.0,27.0,4.0,17.0

In [ ]:
IRIS_COMPLET_2 = IRIS_A_COMPLETER_2.merge(somme_commune)
IRIS_COMPLET_2

,IRIS,commune_code,libelle,nb_bv_par_commune,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,900100201,90010,Belfort,28,24758.0,13304.0,11454.0,231.0,276.0,10947.0,840.0,2297.0,541.0,2465.0,1157.0,1494.0
1,900100502,90010,Belfort,28,24758.0,13304.0,11454.0,231.0,276.0,10947.0,840.0,2297.0,541.0,2465.0,1157.0,1494.0
2,900100102,90010,Belfort,28,24758.0,13304.0,11454.0,231.0,276.0,10947.0,840.0,2297.0,541.0,2465.0,1157.0,1494.0
3,900100203,90010,Belfort,28,24758.0,13304.0,11454.0,231.0,276.0,10947.0,840.0,2297.0,541.0,2465.0,1157.0,1494.0
4,900100501,90010,Belfort,28,24758.0,13304.0,11454.0,231.0,276.0,10947.0,840.0,2297.0,541.0,2465.0,1157.0,1494.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6758,614610000,61167,La Ferté-en-Ouche,10,2307.0,1054.0,1253.0,30.0,40.0,1183.0,46.0,257.0,51.0,386.0,141.0,75.0
6759,850740000,85135,Mareuil-sur-Lay-Dissais,3,2123.0,950.0,1173.0,31.0,52.0,1090.0,63.0,318.0,64.0,275.0,94.0,114.0
6760,371980000,49228,Noyant-Villages,14,4213.0,1983.0,2230.0,85.0,76.0,2069.0,107.0,401.0,91.0,651.0,191.0,174.0
6761,470850000,47207,Pompiey,2,171.0,67.0,104.0,2.0,2.0,100.0,4.0,9.0,4.0,46.0,6.0,6.0
6762,352780103,35189,Montgermont,3,2489.0,957.0,1532.0,25.0,26.0,1481.0,48.0,494.0,168.0,156.0,84.0,307.0

In [ ]:
IRIS_COMPLET_1["IRIS"].value_counts().shape[0]+IRIS_COMPLET_2["IRIS"].value_counts().shape[0]

12354

In [ ]:
pd.concat([IRIS_COMPLET_1,IRIS_COMPLET_2], axis=0)["IRIS"].value_counts().shape[0]

12354

In [ ]:
IRIS_COMPLET_1["IRIS"].value_counts().shape[0]+IRIS_COMPLET_2["IRIS"].value_counts().shape[0]+IRIS_COMPLET_OUI["IRIS"].value_counts().shape[0]

48590

In [ ]:
pd.concat([IRIS_COMPLET_1,IRIS_COMPLET_2, IRIS_COMPLET_OUI], axis=0)["IRIS"].value_counts().shape[0]

48590

In [ ]:
# changer les flags
IRIS_COMPLET_1 = IRIS_COMPLET_1.rename(columns={"nb_bv_par_commune":"FLAG"})
IRIS_COMPLET_2 = IRIS_COMPLET_2.rename(columns={"nb_bv_par_commune":"FLAG"})
IRIS_COMPLET_2["FLAG"] = 2

In [ ]:
IRIS_COMPLET_1.head(1)

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,231670000,23167,Sannat,1,298.0,139.0,159.0,14.0,7.0,138.0,13.0,33.0,9.0,26.0,12.0,15.0

In [ ]:
IRIS_COMPLET_1["Voix/Exprimés_1"] = round(IRIS_COMPLET_1["Voix_1"]/IRIS_COMPLET_1["Exprimés"]*100,2)
IRIS_COMPLET_1["Voix/Exprimés_2"] = round(IRIS_COMPLET_1["Voix_2"]/IRIS_COMPLET_1["Exprimés"]*100,2)
IRIS_COMPLET_1["Voix/Exprimés_3"] = round(IRIS_COMPLET_1["Voix_3"]/IRIS_COMPLET_1["Exprimés"]*100,2)
IRIS_COMPLET_1["Voix/Exprimés_4"] = round(IRIS_COMPLET_1["Voix_4"]/IRIS_COMPLET_1["Exprimés"]*100,2)
IRIS_COMPLET_1["Voix/Exprimés_9"] = round(IRIS_COMPLET_1["Voix_9"]/IRIS_COMPLET_1["Exprimés"]*100,2)
IRIS_COMPLET_1["Voix/Exprimés_11"] = round(IRIS_COMPLET_1["Voix_11"]/IRIS_COMPLET_1["Exprimés"]*100,2)

In [ ]:
IRIS_COMPLET_2["Voix/Exprimés_1"] = round(IRIS_COMPLET_2["Voix_1"]/IRIS_COMPLET_2["Exprimés"]*100,2)
IRIS_COMPLET_2["Voix/Exprimés_2"] = round(IRIS_COMPLET_2["Voix_2"]/IRIS_COMPLET_2["Exprimés"]*100,2)
IRIS_COMPLET_2["Voix/Exprimés_3"] = round(IRIS_COMPLET_2["Voix_3"]/IRIS_COMPLET_2["Exprimés"]*100,2)
IRIS_COMPLET_2["Voix/Exprimés_4"] = round(IRIS_COMPLET_2["Voix_4"]/IRIS_COMPLET_2["Exprimés"]*100,2)
IRIS_COMPLET_2["Voix/Exprimés_9"] = round(IRIS_COMPLET_2["Voix_9"]/IRIS_COMPLET_2["Exprimés"]*100,2)
IRIS_COMPLET_2["Voix/Exprimés_11"] = round(IRIS_COMPLET_2["Voix_11"]/IRIS_COMPLET_2["Exprimés"]*100,2)

In [ ]:
for k in ["Inscrits","Abstentions","Votants","Blancs","Nuls","Exprimés","Voix_1","Voix_2","Voix_3","Voix_4","Voix_9","Voix_11"]:
    IRIS_COMPLET_OUI[k] = IRIS_COMPLET_OUI[k].astype(float)

<ipython-input-47-92c7c0d58c8f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IRIS_COMPLET_OUI[k] = IRIS_COMPLET_OUI[k].astype(float)

In [ ]:
IRIS_COMPLET_1

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
0,231670000,23167,Sannat,1,298.0,139.0,159.0,14.0,7.0,138.0,13.0,33.0,9.0,26.0,12.0,15.0,9.42,23.91,6.52,18.84,8.70,10.87
1,422620000,42262,Saint-Maurice-en-Gourgois,1,1227.0,510.0,717.0,21.0,11.0,685.0,36.0,140.0,20.0,220.0,82.0,79.0,5.26,20.44,2.92,32.12,11.97,11.53
2,714540000,71454,Saint-Martin-du-Mont,1,132.0,51.0,81.0,4.0,5.0,72.0,3.0,14.0,2.0,13.0,11.0,15.0,4.17,19.44,2.78,18.06,15.28,20.83
3,710410000,71041,Bois-Sainte-Marie,1,83.0,37.0,46.0,4.0,1.0,41.0,3.0,10.0,0.0,10.0,4.0,3.0,7.32,24.39,0.00,24.39,9.76,7.32
4,711410000,71041,Bois-Sainte-Marie,1,83.0,37.0,46.0,4.0,1.0,41.0,3.0,10.0,0.0,10.0,4.0,3.0,7.32,24.39,0.00,24.39,9.76,7.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5586,574140000,57380,Laneuveville-lès-Lorquin,1,85.0,33.0,52.0,4.0,1.0,47.0,1.0,10.0,0.0,18.0,1.0,6.0,2.13,21.28,0.00,38.30,2.13,12.77
5587,100850000,10085,Charmoy,1,48.0,13.0,35.0,1.0,2.0,32.0,1.0,1.0,2.0,7.0,14.0,3.0,3.12,3.12,6.25,21.88,43.75,9.38
5588,084700000,08098,Champigneulle,1,54.0,18.0,36.0,1.0,1.0,34.0,0.0,8.0,0.0,13.0,2.0,2.0,0.00,23.53,0.00,38.24,5.88,5.88
5589,621620000,62286,Ecquedecques,1,359.0,152.0,207.0,7.0,8.0,192.0,10.0,29.0,8.0,73.0,16.0,17.0,5.21,15.10,4.17,38.02,8.33,8.85
5590,050680000,05176,Valserres,1,193.0,76.0,117.0,4.0,2.0,111.0,13.0,21.0,6.0,27.0,4.0,17.0,11.71,18.92,5.41,24.32,3.60,15.32

In [ ]:
IRIS_COMPLET_2[IRIS_COMPLET_2["libelle"]=="Les Sables-d'Olonne"]

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
1625,851940105,85194,Les Sables-d'Olonne,2,38821.0,17575.0,21246.0,364.0,656.0,20226.0,641.0,5954.0,1111.0,4318.0,2286.0,2433.0,3.17,29.44,5.49,21.35,11.3,12.03

In [ ]:
#### SOMME 
#IRIS_COMPLET_OUI[IRIS_COMPLET_OUI["libelle"]=="Les Sables-d'Olonne"]
iris_somme_complet_oui= IRIS_COMPLET_OUI[["IRIS","Inscrits","Abstentions","Votants","Blancs","Nuls","Exprimés","Voix_1","Voix_2","Voix_3","Voix_4","Voix_9","Voix_11"]].groupby("IRIS", as_index=False).sum() 
iris_somme_complet_oui

,IRIS,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,010010000,601.0,268.0,333.0,1.0,18.0,314.0,13.0,64.0,18.0,78.0,28.0,52.0
1,010020000,210.0,69.0,141.0,4.0,2.0,135.0,6.0,29.0,6.0,22.0,16.0,36.0
2,010040101,4040.0,2072.0,1968.0,44.0,56.0,1868.0,166.0,316.0,98.0,525.0,162.0,193.0
3,010040201,1018.0,477.0,541.0,13.0,6.0,522.0,41.0,96.0,29.0,116.0,50.0,62.0
4,010040202,3052.0,1426.0,1626.0,40.0,21.0,1565.0,100.0,314.0,103.0,386.0,156.0,216.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36231,956800109,2120.0,1446.0,674.0,30.0,11.0,633.0,116.0,135.0,38.0,131.0,22.0,45.0
36232,956800110,3273.0,2144.0,1129.0,33.0,29.0,1067.0,174.0,150.0,82.0,261.0,40.0,94.0
36233,956800113,2639.0,1869.0,770.0,23.0,18.0,729.0,165.0,105.0,48.0,108.0,31.0,49.0
36234,956820000,109.0,46.0,63.0,2.0,0.0,61.0,5.0,14.0,1.0,6.0,7.0,10.0
36235,956900000,295.0,121.0,174.0,0.0,3.0,171.0,7.0,44.0,7.0,25.0,18.0,29.0

In [ ]:
IRIS_COMPLET_OUI_FINAL = IRIS_COMPLET_OUI[["IRIS","commune_code","libelle"]].drop_duplicates(subset="IRIS").merge(iris_somme_complet_oui)
IRIS_COMPLET_OUI_FINAL

,IRIS,commune_code,libelle,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,721910000,72191,Mayet,2280.0,1093.0,1187.0,48.0,49.0,1090.0,73.0,160.0,62.0,391.0,85.0,106.0
1,811990000,81199,Padiès,165.0,68.0,97.0,5.0,0.0,92.0,10.0,23.0,9.0,23.0,6.0,6.0
2,592250102,59225,Feignies,896.0,433.0,463.0,6.0,14.0,443.0,40.0,38.0,17.0,211.0,16.0,19.0
3,603970000,60397,Le Mesnil-Conteville,71.0,19.0,52.0,1.0,0.0,51.0,0.0,10.0,3.0,18.0,9.0,3.0
4,383820104,38382,Saint-Égrève,1745.0,634.0,1111.0,14.0,12.0,1085.0,43.0,388.0,113.0,113.0,93.0,206.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36231,674822901,67482,Strasbourg,889.0,595.0,294.0,2.0,3.0,289.0,31.0,53.0,16.0,86.0,12.0,25.0
36232,385450101,38545,Vif,4617.0,2367.0,2250.0,47.0,21.0,2182.0,111.0,492.0,144.0,560.0,175.0,315.0
36233,740630000,74063,Châtel,1000.0,536.0,464.0,11.0,8.0,445.0,7.0,88.0,11.0,102.0,103.0,57.0
36234,951010000,95101,Bray-et-Lû,635.0,344.0,291.0,10.0,0.0,281.0,25.0,30.0,19.0,106.0,6.0,23.0
36235,384030000,38403,Saint-Jean-d'Hérans,291.0,114.0,177.0,10.0,5.0,162.0,9.0,21.0,22.0,32.0,13.0,32.0

In [ ]:
 
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_1"] = round(IRIS_COMPLET_OUI_FINAL["Voix_1"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_2"] = round(IRIS_COMPLET_OUI_FINAL["Voix_2"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_3"] = round(IRIS_COMPLET_OUI_FINAL["Voix_3"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_4"] = round(IRIS_COMPLET_OUI_FINAL["Voix_4"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_9"] = round(IRIS_COMPLET_OUI_FINAL["Voix_9"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_11"] = round(IRIS_COMPLET_OUI_FINAL["Voix_11"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)

In [ ]:
IRIS_COMPLET_OUI_FINAL

,IRIS,commune_code,libelle,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
0,721910000,72191,Mayet,2280.0,1093.0,1187.0,48.0,49.0,1090.0,73.0,160.0,62.0,391.0,85.0,106.0,6.70,14.68,5.69,35.87,7.80,9.72
1,811990000,81199,Padiès,165.0,68.0,97.0,5.0,0.0,92.0,10.0,23.0,9.0,23.0,6.0,6.0,10.87,25.00,9.78,25.00,6.52,6.52
2,592250102,59225,Feignies,896.0,433.0,463.0,6.0,14.0,443.0,40.0,38.0,17.0,211.0,16.0,19.0,9.03,8.58,3.84,47.63,3.61,4.29
3,603970000,60397,Le Mesnil-Conteville,71.0,19.0,52.0,1.0,0.0,51.0,0.0,10.0,3.0,18.0,9.0,3.0,0.00,19.61,5.88,35.29,17.65,5.88
4,383820104,38382,Saint-Égrève,1745.0,634.0,1111.0,14.0,12.0,1085.0,43.0,388.0,113.0,113.0,93.0,206.0,3.96,35.76,10.41,10.41,8.57,18.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36231,674822901,67482,Strasbourg,889.0,595.0,294.0,2.0,3.0,289.0,31.0,53.0,16.0,86.0,12.0,25.0,10.73,18.34,5.54,29.76,4.15,8.65
36232,385450101,38545,Vif,4617.0,2367.0,2250.0,47.0,21.0,2182.0,111.0,492.0,144.0,560.0,175.0,315.0,5.09,22.55,6.60,25.66,8.02,14.44
36233,740630000,74063,Châtel,1000.0,536.0,464.0,11.0,8.0,445.0,7.0,88.0,11.0,102.0,103.0,57.0,1.57,19.78,2.47,22.92,23.15,12.81
36234,951010000,95101,Bray-et-Lû,635.0,344.0,291.0,10.0,0.0,281.0,25.0,30.0,19.0,106.0,6.0,23.0,8.90,10.68,6.76,37.72,2.14,8.19
36235,384030000,38403,Saint-Jean-d'Hérans,291.0,114.0,177.0,10.0,5.0,162.0,9.0,21.0,22.0,32.0,13.0,32.0,5.56,12.96,13.58,19.75,8.02,19.75

In [ ]:
IRIS_COMPLET_OUI_FINAL[IRIS_COMPLET_OUI_FINAL["libelle"]=="Les Sables-d'Olonne"]["Exprimés"].sum()

20226.0

In [ ]:
IRIS_COMPLET_2[IRIS_COMPLET_2["libelle"]=="Les Sables-d'Olonne"]

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
1625,851940105,85194,Les Sables-d'Olonne,2,38821.0,17575.0,21246.0,364.0,656.0,20226.0,641.0,5954.0,1111.0,4318.0,2286.0,2433.0,3.17,29.44,5.49,21.35,11.3,12.03

In [ ]:
# BV COORDONNEES IMPRECISES : IRIS_COMPLET_OUI.drop_duplicates(subset=["IRIS", "commune_code"])

In [ ]:
IRIS_COMPLET_1_2 = pd.concat([IRIS_COMPLET_1,IRIS_COMPLET_2], axis=0).drop(['Inscrits', 'Abstentions',
       'Votants', 'Blancs', 'Nuls', 'Exprimés', 'Voix_1', 'Voix_2', 'Voix_3',
       'Voix_4', 'Voix_9', 'Voix_11'], axis=1)
IRIS_COMPLET_1_2

,IRIS,commune_code,libelle,FLAG,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
0,231670000,23167,Sannat,1,9.42,23.91,6.52,18.84,8.70,10.87
1,422620000,42262,Saint-Maurice-en-Gourgois,1,5.26,20.44,2.92,32.12,11.97,11.53
2,714540000,71454,Saint-Martin-du-Mont,1,4.17,19.44,2.78,18.06,15.28,20.83
3,710410000,71041,Bois-Sainte-Marie,1,7.32,24.39,0.00,24.39,9.76,7.32
4,711410000,71041,Bois-Sainte-Marie,1,7.32,24.39,0.00,24.39,9.76,7.32
...,...,...,...,...,...,...,...,...,...,...
6758,614610000,61167,La Ferté-en-Ouche,2,3.89,21.72,4.31,32.63,11.92,6.34
6759,850740000,85135,Mareuil-sur-Lay-Dissais,2,5.78,29.17,5.87,25.23,8.62,10.46
6760,371980000,49228,Noyant-Villages,2,5.17,19.38,4.40,31.46,9.23,8.41
6761,470850000,47207,Pompiey,2,4.00,9.00,4.00,46.00,6.00,6.00
6762,352780103,35189,Montgermont,2,3.24,33.36,11.34,10.53,5.67,20.73

In [ ]:
IRIS_COMPLET_1_2["IRIS"].value_counts().shape[0]+IRIS_COMPLET_OUI_FINAL["IRIS"].value_counts().shape[0]

48590

In [ ]:
pd.concat([IRIS_COMPLET_1_2["IRIS"],IRIS_COMPLET_OUI_FINAL["IRIS"] ], axis=0).value_counts().shape[0]

48590

In [ ]:
IRIS_COMPLET_OUI_FINAL["FLAG"]=0
IRIS_COMPLET_OUI_FINAL = IRIS_COMPLET_OUI_FINAL[['IRIS', 'commune_code', 'libelle', 'FLAG', 'Inscrits', 'Abstentions', 'Votants',
       'Blancs', 'Nuls', 'Exprimés', 'Voix_1', 'Voix_2', 'Voix_3', 'Voix_4',
       'Voix_9', 'Voix_11', 'Voix/Exprimés_1', 'Voix/Exprimés_2',
       'Voix/Exprimés_3', 'Voix/Exprimés_4', 'Voix/Exprimés_9',
       'Voix/Exprimés_11']] 
IRIS_COMPLET_OUI_FINAL

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
0,721910000,72191,Mayet,0,2280.0,1093.0,1187.0,48.0,49.0,1090.0,73.0,160.0,62.0,391.0,85.0,106.0,6.70,14.68,5.69,35.87,7.80,9.72
1,811990000,81199,Padiès,0,165.0,68.0,97.0,5.0,0.0,92.0,10.0,23.0,9.0,23.0,6.0,6.0,10.87,25.00,9.78,25.00,6.52,6.52
2,592250102,59225,Feignies,0,896.0,433.0,463.0,6.0,14.0,443.0,40.0,38.0,17.0,211.0,16.0,19.0,9.03,8.58,3.84,47.63,3.61,4.29
3,603970000,60397,Le Mesnil-Conteville,0,71.0,19.0,52.0,1.0,0.0,51.0,0.0,10.0,3.0,18.0,9.0,3.0,0.00,19.61,5.88,35.29,17.65,5.88
4,383820104,38382,Saint-Égrève,0,1745.0,634.0,1111.0,14.0,12.0,1085.0,43.0,388.0,113.0,113.0,93.0,206.0,3.96,35.76,10.41,10.41,8.57,18.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36231,674822901,67482,Strasbourg,0,889.0,595.0,294.0,2.0,3.0,289.0,31.0,53.0,16.0,86.0,12.0,25.0,10.73,18.34,5.54,29.76,4.15,8.65
36232,385450101,38545,Vif,0,4617.0,2367.0,2250.0,47.0,21.0,2182.0,111.0,492.0,144.0,560.0,175.0,315.0,5.09,22.55,6.60,25.66,8.02,14.44
36233,740630000,74063,Châtel,0,1000.0,536.0,464.0,11.0,8.0,445.0,7.0,88.0,11.0,102.0,103.0,57.0,1.57,19.78,2.47,22.92,23.15,12.81
36234,951010000,95101,Bray-et-Lû,0,635.0,344.0,291.0,10.0,0.0,281.0,25.0,30.0,19.0,106.0,6.0,23.0,8.90,10.68,6.76,37.72,2.14,8.19
36235,384030000,38403,Saint-Jean-d'Hérans,0,291.0,114.0,177.0,10.0,5.0,162.0,9.0,21.0,22.0,32.0,13.0,32.0,5.56,12.96,13.58,19.75,8.02,19.75

In [ ]:
"LA FRANCE INSOUMISE" # Libellé Abrégé Liste_1
"RENAISSANCE" # Libellé Abrégé Liste_5
"ENVIE D'EUROPE" # Libellé Abrégé Liste_12
"PRENEZ LE POUVOIR" # Libellé Abrégé Liste_23
"UNION DROITE-CENTRE" # Libellé Abrégé Liste_29
"EUROPE ÉCOLOGIE" # Libellé Abrégé Liste_30

#AJOUTER CANDIDAT
for k in [IRIS_COMPLET_OUI_FINAL,IRIS_COMPLET_1_2 ]:
    
    k['Nom_1']="LA FRANCE INSOUMISE";k['Prénom_1']="AUBRY Manon"
    k['Nom_2']="RENAISSANCE";k['Prénom_2']="LOISEAU Nathalie"
    k['Nom_3']="ENVIE D'EUROPE";k['Prénom_3']="GLUCKSMANN Raphaël"
    k['Nom_4']="PRENEZ LE POUVOIR";k['Prénom_4']="BARDELLA Jordan"
    k['Nom_9']="UNION DROITE-CENTRE"; k['Prénom_9']="BELLAMY François-Xavier"
    k['Nom_11']="EUROPE ÉCOLOGIE";k['Prénom_11']="JADOT Yannick"

<ipython-input-61-f5ff1e5729b8>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_1']="LA FRANCE INSOUMISE";k['Prénom_1']="AUBRY Manon"
<ipython-input-61-f5ff1e5729b8>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_2']="RENAISSANCE";k['Prénom_2']="LOISEAU Nathalie"
<ipython-input-61-f5ff1e5729b8>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_3']="ENVIE D'EUROPE";k['Prénom_3']="GLUCKSMANN Raphaël"
<ipython-input-61-f5ff1e5729b8>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_4']="PRENEZ LE POUVOIR";k['Prénom_4']="BARDELLA Jordan"
<ipython-input-61-f5ff1e5729b8>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_9']="UNION DROITE-CENTRE"; k['Prénom_9']="BELLAMY François-Xavier"
<ipython-input-61-f5ff1e5729b8>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_11']="EUROPE ÉCOLOGIE";k['Prénom_11']="JADOT Yannick"

In [ ]:
IRIS_COMPLET_1_2.columns

Index(['IRIS', 'commune_code', 'libelle', 'FLAG', 'Voix/Exprimés_1',
       'Voix/Exprimés_2', 'Voix/Exprimés_3', 'Voix/Exprimés_4',
       'Voix/Exprimés_9', 'Voix/Exprimés_11', 'Nom_1', 'Prénom_1', 'Nom_2',
       'Prénom_2', 'Nom_3', 'Prénom_3', 'Nom_4', 'Prénom_4', 'Nom_9',
       'Prénom_9', 'Nom_11', 'Prénom_11'],
      dtype='object')

In [ ]:
IRIS_COMPLET_OUI_FINAL = IRIS_COMPLET_OUI_FINAL[['IRIS', 'commune_code', 'libelle', 'FLAG', 'Inscrits', 'Abstentions',
       'Votants', 'Blancs', 'Nuls', 'Exprimés', 'Nom_1', 'Prénom_1', 'Voix_1', 'Nom_2', 'Prénom_2', 'Voix_2', 'Nom_3',
       'Prénom_3', 'Voix_3',
        'Nom_4', 'Prénom_4','Voix_4', 'Nom_9', 'Prénom_9','Voix_9', 'Nom_11',
       'Prénom_11', 'Voix_11', 'Voix/Exprimés_1', 'Voix/Exprimés_2',
       'Voix/Exprimés_3', 'Voix/Exprimés_4', 'Voix/Exprimés_9',
       'Voix/Exprimés_11']]

In [ ]:
IRIS_COMPLET_1_2 = IRIS_COMPLET_1_2[['IRIS', 'commune_code', 'libelle', 'FLAG',  'Nom_1', 'Prénom_1', 'Voix/Exprimés_1',
       'Nom_2','Prénom_2','Voix/Exprimés_2', 'Nom_3', 'Prénom_3', 'Voix/Exprimés_3', 'Nom_4', 'Prénom_4', 'Voix/Exprimés_4',
       'Nom_9','Prénom_9','Voix/Exprimés_9',  'Nom_11', 'Prénom_11', 'Voix/Exprimés_11']]

In [ ]:
FINAL_POURCENTAGE =pd.concat([IRIS_COMPLET_OUI_FINAL[IRIS_COMPLET_1_2.columns], IRIS_COMPLET_1_2], axis=0)

In [ ]:
# CHANGEMENT DE NOM prénom et nom
IRIS_COMPLET_OUI_FINAL = IRIS_COMPLET_OUI_FINAL.rename(columns={"Nom_1":"Parti_1","Prénom_1":"Nom_Prénom_1",
                                      "Nom_2":"Parti_2","Prénom_2":"Nom_Prénom_2",
                                       "Nom_3":"Parti_3","Prénom_3":"Nom_Prénom_3",
                                       "Nom_4":"Parti_4","Prénom_4":"Nom_Prénom_4",
                                       "Nom_9":"Parti_9","Prénom_9":"Nom_Prénom_9",
                                       "Nom_11":"Parti_11","Prénom_11":"Nom_Prénom_11",
                                      })

IRIS_COMPLET_1_2 = IRIS_COMPLET_1_2.rename(columns={"Nom_1":"Parti_1","Prénom_1":"Nom_Prénom_1",
                                      "Nom_2":"Parti_2","Prénom_2":"Nom_Prénom_2",
                                       "Nom_3":"Parti_3","Prénom_3":"Nom_Prénom_3",
                                       "Nom_4":"Parti_4","Prénom_4":"Nom_Prénom_4",
                                       "Nom_9":"Parti_9","Prénom_9":"Nom_Prénom_9",
                                       "Nom_11":"Parti_11","Prénom_11":"Nom_Prénom_11",
                                      })
FINAL_POURCENTAGE = FINAL_POURCENTAGE.rename(columns={"Nom_1":"Parti_1","Prénom_1":"Nom_Prénom_1",
                                      "Nom_2":"Parti_2","Prénom_2":"Nom_Prénom_2",
                                       "Nom_3":"Parti_3","Prénom_3":"Nom_Prénom_3",
                                       "Nom_4":"Parti_4","Prénom_4":"Nom_Prénom_4",
                                       "Nom_9":"Parti_9","Prénom_9":"Nom_Prénom_9",
                                       "Nom_11":"Parti_11","Prénom_11":"Nom_Prénom_11",
                                      })

In [ ]:
#ENREGISTREMENT
IRIS_COMPLET_OUI_FINAL.to_csv("C:/Users/Christian/Desktop/IRIS_BV_final/EUROPEEN/IRIS_FLAG_0_INSCRITS_POURCENTAGE_EUROPEEN.txt",sep=";", index=False)
IRIS_COMPLET_1_2.to_csv("C:/Users/Christian/Desktop/IRIS_BV_final/EUROPEEN/IRIS_FLAG_1_2_POURCENTAGE_EUROPEEN.txt",sep=";", index=False)
FINAL_POURCENTAGE.to_csv("C:/Users/Christian/Desktop/IRIS_BV_final/EUROPEEN/IRIS_FINAL_POURCENTAGE_EUROPEEN.txt",sep=";", index=False)

In [ ]:
FINAL_POURCENTAGE

,IRIS,commune_code,libelle,FLAG,Parti_1,Nom_Prénom_1,Voix/Exprimés_1,Parti_2,Nom_Prénom_2,Voix/Exprimés_2,Parti_3,Nom_Prénom_3,Voix/Exprimés_3,Parti_4,Nom_Prénom_4,Voix/Exprimés_4,Parti_9,Nom_Prénom_9,Voix/Exprimés_9,Parti_11,Nom_Prénom_11,Voix/Exprimés_11
0,721910000,72191,Mayet,0,LA FRANCE INSOUMISE,AUBRY Manon,6.70,RENAISSANCE,LOISEAU Nathalie,14.68,ENVIE D'EUROPE,GLUCKSMANN Raphaël,5.69,PRENEZ LE POUVOIR,BARDELLA Jordan,35.87,UNION DROITE-CENTRE,BELLAMY François-Xavier,7.80,EUROPE ÉCOLOGIE,JADOT Yannick,9.72
1,811990000,81199,Padiès,0,LA FRANCE INSOUMISE,AUBRY Manon,10.87,RENAISSANCE,LOISEAU Nathalie,25.00,ENVIE D'EUROPE,GLUCKSMANN Raphaël,9.78,PRENEZ LE POUVOIR,BARDELLA Jordan,25.00,UNION DROITE-CENTRE,BELLAMY François-Xavier,6.52,EUROPE ÉCOLOGIE,JADOT Yannick,6.52
2,592250102,59225,Feignies,0,LA FRANCE INSOUMISE,AUBRY Manon,9.03,RENAISSANCE,LOISEAU Nathalie,8.58,ENVIE D'EUROPE,GLUCKSMANN Raphaël,3.84,PRENEZ LE POUVOIR,BARDELLA Jordan,47.63,UNION DROITE-CENTRE,BELLAMY François-Xavier,3.61,EUROPE ÉCOLOGIE,JADOT Yannick,4.29
3,603970000,60397,Le Mesnil-Conteville,0,LA FRANCE INSOUMISE,AUBRY Manon,0.00,RENAISSANCE,LOISEAU Nathalie,19.61,ENVIE D'EUROPE,GLUCKSMANN Raphaël,5.88,PRENEZ LE POUVOIR,BARDELLA Jordan,35.29,UNION DROITE-CENTRE,BELLAMY François-Xavier,17.65,EUROPE ÉCOLOGIE,JADOT Yannick,5.88
4,383820104,38382,Saint-Égrève,0,LA FRANCE INSOUMISE,AUBRY Manon,3.96,RENAISSANCE,LOISEAU Nathalie,35.76,ENVIE D'EUROPE,GLUCKSMANN Raphaël,10.41,PRENEZ LE POUVOIR,BARDELLA Jordan,10.41,UNION DROITE-CENTRE,BELLAMY François-Xavier,8.57,EUROPE ÉCOLOGIE,JADOT Yannick,18.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6758,614610000,61167,La Ferté-en-Ouche,2,LA FRANCE INSOUMISE,AUBRY Manon,3.89,RENAISSANCE,LOISEAU Nathalie,21.72,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.31,PRENEZ LE POUVOIR,BARDELLA Jordan,32.63,UNION DROITE-CENTRE,BELLAMY François-Xavier,11.92,EUROPE ÉCOLOGIE,JADOT Yannick,6.34
6759,850740000,85135,Mareuil-sur-Lay-Dissais,2,LA FRANCE INSOUMISE,AUBRY Manon,5.78,RENAISSANCE,LOISEAU Nathalie,29.17,ENVIE D'EUROPE,GLUCKSMANN Raphaël,5.87,PRENEZ LE POUVOIR,BARDELLA Jordan,25.23,UNION DROITE-CENTRE,BELLAMY François-Xavier,8.62,EUROPE ÉCOLOGIE,JADOT Yannick,10.46
6760,371980000,49228,Noyant-Villages,2,LA FRANCE INSOUMISE,AUBRY Manon,5.17,RENAISSANCE,LOISEAU Nathalie,19.38,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.40,PRENEZ LE POUVOIR,BARDELLA Jordan,31.46,UNION DROITE-CENTRE,BELLAMY François-Xavier,9.23,EUROPE ÉCOLOGIE,JADOT Yannick,8.41
6761,470850000,47207,Pompiey,2,LA FRANCE INSOUMISE,AUBRY Manon,4.00,RENAISSANCE,LOISEAU Nathalie,9.00,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.00,PRENEZ LE POUVOIR,BARDELLA Jordan,46.00,UNION DROITE-CENTRE,BELLAMY François-Xavier,6.00,EUROPE ÉCOLOGIE,JADOT Yannick,6.00
6762,352780103,35189,Montgermont,2,LA FRANCE INSOUMISE,AUBRY Manon,3.24,RENAISSANCE,LOISEAU Nathalie,33.36,ENVIE D'EUROPE,GLUCKSMANN Raphaël,11.34,PRENEZ LE POUVOIR,BARDELLA Jordan,10.53,UNION DROITE-CENTRE,BELLAMY François-Xavier,5.67,EUROPE ÉCOLOGIE,JADOT Yannick,20.73

In [ ]:
(275.0+83.0)/(1096.0+281.0)*100

25.998547567175017

In [ ]:
IRIS_COMPLET_OUI_FINAL[IRIS_COMPLET_OUI_FINAL["commune_code"]=="85194"]["Exprimés"].sum()

20226.0

In [ ]:
641.0/20226.0*100

3.169188173637892

In [ ]:
IRIS_COMPLET_1_2[IRIS_COMPLET_1_2["commune_code"]=="85194"] # Saint-Martin-du-Mont

,IRIS,commune_code,libelle,FLAG,Parti_1,Nom_Prénom_1,Voix/Exprimés_1,Parti_2,Nom_Prénom_2,Voix/Exprimés_2,Parti_3,Nom_Prénom_3,Voix/Exprimés_3,Parti_4,Nom_Prénom_4,Voix/Exprimés_4,Parti_9,Nom_Prénom_9,Voix/Exprimés_9,Parti_11,Nom_Prénom_11,Voix/Exprimés_11
1625,851940105,85194,Les Sables-d'Olonne,2,LA FRANCE INSOUMISE,AUBRY Manon,3.17,RENAISSANCE,LOISEAU Nathalie,29.44,ENVIE D'EUROPE,GLUCKSMANN Raphaël,5.49,PRENEZ LE POUVOIR,BARDELLA Jordan,21.35,UNION DROITE-CENTRE,BELLAMY François-Xavier,11.3,EUROPE ÉCOLOGIE,JADOT Yannick,12.03

In [ ]:
IRIS_COMPLET_1_2

,IRIS,commune_code,libelle,FLAG,Parti_1,Nom_Prénom_1,Voix/Exprimés_1,Parti_2,Nom_Prénom_2,Voix/Exprimés_2,Parti_3,Nom_Prénom_3,Voix/Exprimés_3,Parti_4,Nom_Prénom_4,Voix/Exprimés_4,Parti_9,Nom_Prénom_9,Voix/Exprimés_9,Parti_11,Nom_Prénom_11,Voix/Exprimés_11
0,231670000,23167,Sannat,1,LA FRANCE INSOUMISE,AUBRY Manon,9.42,RENAISSANCE,LOISEAU Nathalie,23.91,ENVIE D'EUROPE,GLUCKSMANN Raphaël,6.52,PRENEZ LE POUVOIR,BARDELLA Jordan,18.84,UNION DROITE-CENTRE,BELLAMY François-Xavier,8.70,EUROPE ÉCOLOGIE,JADOT Yannick,10.87
1,422620000,42262,Saint-Maurice-en-Gourgois,1,LA FRANCE INSOUMISE,AUBRY Manon,5.26,RENAISSANCE,LOISEAU Nathalie,20.44,ENVIE D'EUROPE,GLUCKSMANN Raphaël,2.92,PRENEZ LE POUVOIR,BARDELLA Jordan,32.12,UNION DROITE-CENTRE,BELLAMY François-Xavier,11.97,EUROPE ÉCOLOGIE,JADOT Yannick,11.53
2,714540000,71454,Saint-Martin-du-Mont,1,LA FRANCE INSOUMISE,AUBRY Manon,4.17,RENAISSANCE,LOISEAU Nathalie,19.44,ENVIE D'EUROPE,GLUCKSMANN Raphaël,2.78,PRENEZ LE POUVOIR,BARDELLA Jordan,18.06,UNION DROITE-CENTRE,BELLAMY François-Xavier,15.28,EUROPE ÉCOLOGIE,JADOT Yannick,20.83
3,710410000,71041,Bois-Sainte-Marie,1,LA FRANCE INSOUMISE,AUBRY Manon,7.32,RENAISSANCE,LOISEAU Nathalie,24.39,ENVIE D'EUROPE,GLUCKSMANN Raphaël,0.00,PRENEZ LE POUVOIR,BARDELLA Jordan,24.39,UNION DROITE-CENTRE,BELLAMY François-Xavier,9.76,EUROPE ÉCOLOGIE,JADOT Yannick,7.32
4,711410000,71041,Bois-Sainte-Marie,1,LA FRANCE INSOUMISE,AUBRY Manon,7.32,RENAISSANCE,LOISEAU Nathalie,24.39,ENVIE D'EUROPE,GLUCKSMANN Raphaël,0.00,PRENEZ LE POUVOIR,BARDELLA Jordan,24.39,UNION DROITE-CENTRE,BELLAMY François-Xavier,9.76,EUROPE ÉCOLOGIE,JADOT Yannick,7.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6758,614610000,61167,La Ferté-en-Ouche,2,LA FRANCE INSOUMISE,AUBRY Manon,3.89,RENAISSANCE,LOISEAU Nathalie,21.72,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.31,PRENEZ LE POUVOIR,BARDELLA Jordan,32.63,UNION DROITE-CENTRE,BELLAMY François-Xavier,11.92,EUROPE ÉCOLOGIE,JADOT Yannick,6.34
6759,850740000,85135,Mareuil-sur-Lay-Dissais,2,LA FRANCE INSOUMISE,AUBRY Manon,5.78,RENAISSANCE,LOISEAU Nathalie,29.17,ENVIE D'EUROPE,GLUCKSMANN Raphaël,5.87,PRENEZ LE POUVOIR,BARDELLA Jordan,25.23,UNION DROITE-CENTRE,BELLAMY François-Xavier,8.62,EUROPE ÉCOLOGIE,JADOT Yannick,10.46
6760,371980000,49228,Noyant-Villages,2,LA FRANCE INSOUMISE,AUBRY Manon,5.17,RENAISSANCE,LOISEAU Nathalie,19.38,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.40,PRENEZ LE POUVOIR,BARDELLA Jordan,31.46,UNION DROITE-CENTRE,BELLAMY François-Xavier,9.23,EUROPE ÉCOLOGIE,JADOT Yannick,8.41
6761,470850000,47207,Pompiey,2,LA FRANCE INSOUMISE,AUBRY Manon,4.00,RENAISSANCE,LOISEAU Nathalie,9.00,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.00,PRENEZ LE POUVOIR,BARDELLA Jordan,46.00,UNION DROITE-CENTRE,BELLAMY François-Xavier,6.00,EUROPE ÉCOLOGIE,JADOT Yannick,6.00
6762,352780103,35189,Montgermont,2,LA FRANCE INSOUMISE,AUBRY Manon,3.24,RENAISSANCE,LOISEAU Nathalie,33.36,ENVIE D'EUROPE,GLUCKSMANN Raphaël,11.34,PRENEZ LE POUVOIR,BARDELLA Jordan,10.53,UNION DROITE-CENTRE,BELLAMY François-Xavier,5.67,EUROPE ÉCOLOGIE,JADOT Yannick,20.73

In [ ]:
IRIS_COMPLET_1_2[IRIS_COMPLET_1_2['FLAG']==2]

,IRIS,commune_code,libelle,FLAG,Parti_1,Nom_Prénom_1,Voix/Exprimés_1,Parti_2,Nom_Prénom_2,Voix/Exprimés_2,Parti_3,Nom_Prénom_3,Voix/Exprimés_3,Parti_4,Nom_Prénom_4,Voix/Exprimés_4,Parti_9,Nom_Prénom_9,Voix/Exprimés_9,Parti_11,Nom_Prénom_11,Voix/Exprimés_11
0,900100201,90010,Belfort,2,LA FRANCE INSOUMISE,AUBRY Manon,7.67,RENAISSANCE,LOISEAU Nathalie,20.98,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.94,PRENEZ LE POUVOIR,BARDELLA Jordan,22.52,UNION DROITE-CENTRE,BELLAMY François-Xavier,10.57,EUROPE ÉCOLOGIE,JADOT Yannick,13.65
1,900100502,90010,Belfort,2,LA FRANCE INSOUMISE,AUBRY Manon,7.67,RENAISSANCE,LOISEAU Nathalie,20.98,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.94,PRENEZ LE POUVOIR,BARDELLA Jordan,22.52,UNION DROITE-CENTRE,BELLAMY François-Xavier,10.57,EUROPE ÉCOLOGIE,JADOT Yannick,13.65
2,900100102,90010,Belfort,2,LA FRANCE INSOUMISE,AUBRY Manon,7.67,RENAISSANCE,LOISEAU Nathalie,20.98,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.94,PRENEZ LE POUVOIR,BARDELLA Jordan,22.52,UNION DROITE-CENTRE,BELLAMY François-Xavier,10.57,EUROPE ÉCOLOGIE,JADOT Yannick,13.65
3,900100203,90010,Belfort,2,LA FRANCE INSOUMISE,AUBRY Manon,7.67,RENAISSANCE,LOISEAU Nathalie,20.98,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.94,PRENEZ LE POUVOIR,BARDELLA Jordan,22.52,UNION DROITE-CENTRE,BELLAMY François-Xavier,10.57,EUROPE ÉCOLOGIE,JADOT Yannick,13.65
4,900100501,90010,Belfort,2,LA FRANCE INSOUMISE,AUBRY Manon,7.67,RENAISSANCE,LOISEAU Nathalie,20.98,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.94,PRENEZ LE POUVOIR,BARDELLA Jordan,22.52,UNION DROITE-CENTRE,BELLAMY François-Xavier,10.57,EUROPE ÉCOLOGIE,JADOT Yannick,13.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6758,614610000,61167,La Ferté-en-Ouche,2,LA FRANCE INSOUMISE,AUBRY Manon,3.89,RENAISSANCE,LOISEAU Nathalie,21.72,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.31,PRENEZ LE POUVOIR,BARDELLA Jordan,32.63,UNION DROITE-CENTRE,BELLAMY François-Xavier,11.92,EUROPE ÉCOLOGIE,JADOT Yannick,6.34
6759,850740000,85135,Mareuil-sur-Lay-Dissais,2,LA FRANCE INSOUMISE,AUBRY Manon,5.78,RENAISSANCE,LOISEAU Nathalie,29.17,ENVIE D'EUROPE,GLUCKSMANN Raphaël,5.87,PRENEZ LE POUVOIR,BARDELLA Jordan,25.23,UNION DROITE-CENTRE,BELLAMY François-Xavier,8.62,EUROPE ÉCOLOGIE,JADOT Yannick,10.46
6760,371980000,49228,Noyant-Villages,2,LA FRANCE INSOUMISE,AUBRY Manon,5.17,RENAISSANCE,LOISEAU Nathalie,19.38,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.40,PRENEZ LE POUVOIR,BARDELLA Jordan,31.46,UNION DROITE-CENTRE,BELLAMY François-Xavier,9.23,EUROPE ÉCOLOGIE,JADOT Yannick,8.41
6761,470850000,47207,Pompiey,2,LA FRANCE INSOUMISE,AUBRY Manon,4.00,RENAISSANCE,LOISEAU Nathalie,9.00,ENVIE D'EUROPE,GLUCKSMANN Raphaël,4.00,PRENEZ LE POUVOIR,BARDELLA Jordan,46.00,UNION DROITE-CENTRE,BELLAMY François-Xavier,6.00,EUROPE ÉCOLOGIE,JADOT Yannick,6.00
6762,352780103,35189,Montgermont,2,LA FRANCE INSOUMISE,AUBRY Manon,3.24,RENAISSANCE,LOISEAU Nathalie,33.36,ENVIE D'EUROPE,GLUCKSMANN Raphaël,11.34,PRENEZ LE POUVOIR,BARDELLA Jordan,10.53,UNION DROITE-CENTRE,BELLAMY François-Xavier,5.67,EUROPE ÉCOLOGIE,JADOT Yannick,20.73

In [ ]:
somme_commune[somme_commune["commune_code"]=="85194"]

,commune_code,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
32788,85194,38821.0,17575.0,21246.0,364.0,656.0,20226.0,641.0,5954.0,1111.0,4318.0,2286.0,2433.0

In [ ]:
448.0/10558.0*100

4.243227884068952

In [ ]:
657.0/17846.0*100

3.6814972542866746