In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option("display.max_row",50)
pd.set_option("display.max_columns",130)

In [ ]:
# 6 PARTIES
"""
"LA FRANCE INSOUMISE"
"RENAISSANCE"
"ENVIE D'EUROPE"
"PRENEZ LE POUVOIR"
"UNION DROITE-CENTRE"
"EUROPE ÉCOLOGIE"

#PRESIDENTIELLES

DUPONT-AIGNAN
LE PEN
MACRON
HAMON
MÉLENCHON
FILLON
"""

'\n"LA FRANCE INSOUMISE"\n"RENAISSANCE"\n"ENVIE D\'EUROPE"\n"PRENEZ LE POUVOIR"\n"UNION DROITE-CENTRE"\n"EUROPE ÉCOLOGIE"\n\n#PRESIDENTIELLES\n\nDUPONT-AIGNAN\nLE PEN\nMACRON\nHAMON\nMÉLENCHON\nFILLON\n'

In [ ]:
data_premier_orig = pd.read_csv("C:/Users/Christian/Desktop/IRIS_BV_final/PRESIDENTIELLES/PR17_BVot_T1_FE.txt",sep=";", header=0, dtype=str)
data_premier = data_premier_orig.copy()
data_premier

,Code du département,Libellé du département,Code de la circonscription,Libellé de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,% Blancs/Vot,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,N°Panneau_1,Sexe_1,Nom_1,Prénom_1,Voix_1,% Voix/Ins_1,% Voix/Exp_1,N°Panneau_2,Sexe_2,Nom_2,Prénom_2,Voix_2,% Voix/Ins_2,% Voix/Exp_2,N°Panneau_3,Sexe_3,Nom_3,Prénom_3,Voix_3,% Voix/Ins_3,% Voix/Exp_3,N°Panneau_4,Sexe_4,Nom_4,Prénom_4,Voix_4,% Voix/Ins_4,% Voix/Exp_4,N°Panneau_5,Sexe_5,Nom_5,Prénom_5,Voix_5,% Voix/Ins_5,% Voix/Exp_5,N°Panneau_6,Sexe_6,Nom_6,Prénom_6,Voix_6,% Voix/Ins_6,% Voix/Exp_6,N°Panneau_7,Sexe_7,Nom_7,Prénom_7,Voix_7,% Voix/Ins_7,% Voix/Exp_7,N°Panneau_8,Sexe_8,Nom_8,Prénom_8,Voix_8,% Voix/Ins_8,% Voix/Exp_8,N°Panneau_9,Sexe_9,Nom_9,Prénom_9,Voix_9,% Voix/Ins_9,% Voix/Exp_9,N°Panneau_10,Sexe_10,Nom_10,Prénom_10,Voix_10,% Voix/Ins_10,% Voix/Exp_10,N°Panneau_11,Sexe_11,Nom_11,Prénom_11,Voix_11,% Voix/Ins_11,% Voix/Exp_11,Voix_ARTHAUD,Voix_ASSELINEAU,Voix_CHEMINADE,Voix_DUPONT-AIGNAN,Voix_FILLON,Voix_HAMON,Voix_LASSALLE,Voix_LE PEN,Voix_MACRON,Voix_MÉLENCHON,Voix_POUTOU,TOT,%ARTHAUD,%ASSELINEAU,%CHEMINADE,%DUPONT-AIGNAN,%FILLON,%HAMON,%LASSALLE,%LE PEN,%MACRON,%MÉLENCHON,%POUTOU
0,01,Ain,04,4ème circonscription,001,L'Abergement-Clémenciat,0001,598,92,"15,38",506,"84,62",2,"0,33","0,40",9,"1,51","1,78",495,"82,78","97,83",1,M,DUPONT-AIGNAN,Nicolas,34,"5,69","6,87",2,F,LE PEN,Marine,126,"21,07","25,45",3,M,MACRON,Emmanuel,119,"19,90","24,04",4,M,HAMON,Benoît,29,"4,85","5,86",5,F,ARTHAUD,Nathalie,4,"0,67","0,81",6,M,POUTOU,Philippe,4,"0,67","0,81",7,M,CHEMINADE,Jacques,2,"0,33","0,40",8,M,LASSALLE,Jean,2,"0,33","0,40",9,M,MÉLENCHON,Jean-Luc,59,"9,87","11,92",10,M,ASSELINEAU,François,6,"1,00","1,21",11,M,FILLON,François,110,"18,39","22,22",4,6,2,34,110,29,2,126,119,59,4,495,"0,80","1,21","0,40","6,86","22,22","5,85","0,40","25,45","24,04","11,91","0,80"
1,01,Ain,05,5ème circonscription,002,L'Abergement-de-Varey,0001,209,25,"11,96",184,"88,04",6,"2,87","3,26",2,"0,96","1,09",176,"84,21","95,65",1,M,DUPONT-AIGNAN,Nicolas,6,"2,87","3,41",2,F,LE PEN,Marine,48,"22,97","27,27",3,M,MACRON,Emmanuel,37,"17,70","21,02",4,M,HAMON,Benoît,13,"6,22","7,39",5,F,ARTHAUD,Nathalie,2,"0,96","1,14",6,M,POUTOU,Philippe,2,"0,96","1,14",7,M,CHEMINADE,Jacques,0,"0,00","0,00",8,M,LASSALLE,Jean,0,"0,00","0,00",9,M,MÉLENCHON,Jean-Luc,33,"15,79","18,75",10,M,ASSELINEAU,François,1,"0,48","0,57",11,M,FILLON,François,34,"16,27","19,32",2,1,0,6,34,13,0,48,37,33,2,176,"1,13","0,56","0,00","3,40","19,31","7,38","0,00","27,27","21,02","18,75","1,13"
2,01,Ain,05,5ème circonscription,004,Ambérieu-en-Bugey,0001,1116,233,"20,88",883,"79,12",17,"1,52","1,93",6,"0,54","0,68",860,"77,06","97,40",1,M,DUPONT-AIGNAN,Nicolas,58,"5,20","6,74",2,F,LE PEN,Marine,233,"20,88","27,09",3,M,MACRON,Emmanuel,156,"13,98","18,14",4,M,HAMON,Benoît,47,"4,21","5,47",5,F,ARTHAUD,Nathalie,6,"0,54","0,70",6,M,POUTOU,Philippe,15,"1,34","1,74",7,M,CHEMINADE,Jacques,0,"0,00","0,00",8,M,LASSALLE,Jean,6,"0,54","0,70",9,M,MÉLENCHON,Jean-Luc,216,"19,35","25,12",10,M,ASSELINEAU,François,7,"0,63","0,81",11,M,FILLON,François,116,"10,39","13,49",6,7,0,58,116,47,6,233,156,216,15,860,"0,69","0,81","0,00","6,74","13,48","5,46","0,69","27,09","18,13","25,11","1,74"
3,01,Ain,05,5ème circonscription,004,Ambérieu-en-Bugey,0002,1128,256,"22,70",872,"77,30",19,"1,68","2,18",3,"0,27","0,34",850,"75,35","97,48",1,M,DUPONT-AIGNAN,Nicolas,42,"3,72","4,94",2,F,LE PEN,Marine,234,"20,74","27,53",3,M,MACRON,Emmanuel,183,"16,22","21,53",4,M,HAMON,Benoît,51,"4,52","6,00",5,F,ARTHAUD,Nathalie,5,"0,44","0,59",6,M,POUTOU,Philippe,16,"1,42","1,88",7,M,CHEMINADE,Jacques,1,"0,09","0,12",8,M,LASSALLE,Jean,8,"0,71","0,94",9,M,MÉLENCHON,Jean-Luc,175,"15,51","20,59",10,M,ASSELINEAU,François,11,"0,98","1,29",11,M,FILLON,François,124,"10,99","14,59",5,11,1,42,124,51,8,234,183,175,16,850,"0,58","1,29","0,11","4,94","14,58","6,00","0,94","27,52","21,52","20,58","1,88"
4,01,Ain,05,5ème circonscription,004,Ambérieu-en-Bugey,0003,1116,227,"20,34",889,"79,66",11,"0,99","1,24",4,"0,36","0,45",874,"78,32","98,31",1,M,DUPONT-AIGNAN,Nicolas,47,"4,21","5,38",2,F,LE PEN,Marine,218,"19,53","24,94",3,M,MACRON,Emmanuel,191,"17,11","21,85",4,M,HAMON,Benoît,53,"4,75","6,06",5,F,ARTHAUD,Nathalie,4,"0,36","0,46",6,M,POUTOU,Philippe,12,"1,08","1,37",7,M,CHEMINADE,Jacques,0,"0,00","0,00",8,M,LASSALLE,Jean,11,"0,99","1,26",9,M,MÉLENCHON,Jean-Luc,182,"16,31","20,82",10,M,ASSELINEAU,François,7,"0,63","0,80",11,M,FILLON,François,149,"13,35","17,05",4,7,0,47,149,53,11,218,191,182,12,874,"0,45","0,80","0,00","5,37","17,04","6,06","1,25","24,94","21,85","20,82","1,37"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69237,ZZ,Français établis hors de France,11,11ème circonscription,226,Wuhan,0001,369,129,"34,96",240,"65,04",2,"0,54","0,83",2,"0,54","0,83",236,"63,96","98,33",1,M,DUPONT-AIGNAN,Nicolas,1,"0,27","0,42",2,F,LE PEN,Marine,16,"4,34","6,78",3,M,MACRON,Emmanuel,115,"31,17","48,73",4,M,HAMON,Benoît,10,"2,71","4,24",5,F,ARTHAUD,Nathalie,2,"0,54","0,85",6,M,POUTOU,Philippe,1,"0,27","0,42",7,M,CHEMINADE,Jacques,0,"0,00","0,00",8,M,LASSALLE,Jean,0,"0,00","0,00",9,M,MÉLENCHON,Jean-Luc,26,"7,05","11,02",10,M,ASSELINEAU,François,3,"0,81","1,27",11,M,FILLON,François,62,"16,80","26,27",2,3,0,1,62,10,0,16,115,26,1,236,"0,84","1,27","0,00","0,42","26,27","4,23","0,00","6,77","48,72","11,01","0,42"
69238,ZZ,Français établis hors de France,10,10ème circonscription,227,Yaounde,0001,1514,800,"52,84",714,"47,16",3,"0,20","0,42",0,"0,00","0,00",711,"46,96","99,58",1,M,DUPONT-AIGNAN,Nicolas,13,"0,86","1,83",2,F,LE PEN,Marine,49,"3,24","6,89",3,M,MACRON,Emmanuel,251,"16,58","35,30",4,M,HAMON,Benoît,63,"4,16","8,86",5,F,ARTHAUD,Nathalie,0,"0,00","0,00",6,M,POUTOU,Philippe,1,"0,07","0,14",7,M,CHEMINADE,Jacques,0,"0,00","0,00",8,M,LASSALLE,Jean,2,"0,13","0,28",9,M,MÉLENCHON,Jean-Luc,131,"8,65","18,42",10,M,ASSELINEAU,François,4,"0,26","0,56",11,M,FILLON,François,197,"13,01","27,71",0,4,0,13,197,63,2,49,251,131,1,711,"0,00","0,56","0,00","1,82","27,70","8,86","0,28","6,89","35,30","18,42","0,14"
69239,ZZ,Français établis hors de France,07,7ème circonscription,228,Zagreb,0001,655,401,"61,22",254,"38,78",2,"0,31","0,79",1,"0,15","0,39",251,"38,32","98,82",1,M,DUPONT-AIGNAN,Nicolas,8,"1,22","3,19",2,F,LE PEN,Marine,35,"5,34","13,94",3,M,MACRON,Emmanuel,92,"14,05","36,65",4,M,HAMON,Benoît,14,"2,14","5,58",5,F,ARTHAUD,Nathalie,0,"0,00","0,00",6,M,POUTOU,Philippe,0,"0,00","0,00",7,M,CHEMINADE,Jacques,0,"0,00","0,00",8,M,LASSALLE,Jean,1,"0,15","0,40",9,M,MÉLENCHON,Jean-Luc,30,"4,58","11,95",10,M,ASSELINEAU,François,6,"0,92","2,39",11,M,FILLON,François,65,"9,92","25,90",0,6,0,8,65,14,1,35,92,30,0,251,"0,00","2,39","0,00","3,18","25,89","5,57","0,39","13,94","36,65","11,95","0,00"
69240,ZZ,Français établis hors de France,06,6ème circonscription,229,Zurich,0001,21477,11129,"51,82",10348,"48,18",47,"0,22","0,45",58,"0,27","0,56",10243,"47,69","98,99",1,M,DUPONT-AIGNAN,Nicolas,205,"0,95","2,00",2,F,LE PEN,Marine,622,"2,90","6,07",3,M,MACRON,Emmanuel,4672,"21,75","45,61",4,M,HAMON,Benoît,567,"2,64","5,54",5,F,ARTHAUD,Nathalie,27,"0,13","0,26",6,M,POUTOU,Philippe,61,"0,28","0,60",7,M,CHEMINADE,Jacques,18,"0,08","0,18",8,M,LASSALLE,Jean,41,"0,19","0,40",9,M,MÉLENCHON,Jean-Luc,1050,"4,89","10,25",10,M,ASSELINEAU,François,87,"0,41","0,85",11,M,FILLON,François,2893,"13,47","28,24",27,87,18,205,2893,567,41,622,4672,1050,61,10243,"0,26","0,84","0,17","2,00","28,24","5,53","0,40","6,07","45,61","10,25","0,59"
69241,ZZ,Français établis hors de France,11,11ème circonscription,231,Taipeh,0001,1204,519,"43,11",685,"56,89",8,"0,66","1,17",1,"0,08","0,15",676,"56,15","98,69",1,M,DUPONT-AIGNAN,Nicolas,8,"0,66","1,18",2,F,LE PEN,Marine,45,"3,74","6,66",3,M,MACRON,Emmanuel,260,"21,59","38,46",4,M,HAMON,Benoît,47,"3,90","6,95",5,F,ARTHAUD,Nathalie,1,"0,08","0,15",6,M,POUTOU,Philippe,2,"0,17","0,30",7,M,CHEMINADE,Jacques,3,"0,25","0,44",8,M,LASSALLE,Jean,6,"0,50","0,89",9,M,MÉLENCHON,Jean-Luc,156,"12,96","23,08",10,M,ASSELINEAU,François,35,"2,91","5,18",11,M,FILLON,François,113,"9,39","16,72",1,35,3,8,113,47,6,45,260,156,2,676,"0,14","5,17","0,44","1,18","16,71","6,95","0,88","6,65","38,46","23,07","0,29"

In [ ]:
data_premier = data_premier[["Code du département","Libellé du département","Code de la circonscription",
"Code de la commune","Libellé de la commune","Code du bvote","Inscrits","Abstentions",
"Votants","Blancs","Nuls","Exprimés",
"Nom_1","Prénom_1","Voix_1",
"Nom_2","Prénom_2","Voix_2",
"Nom_3","Prénom_3","Voix_3",
"Nom_4","Prénom_4","Voix_4",
"Nom_9","Prénom_9","Voix_9",
"Nom_11","Prénom_11","Voix_11"]]

In [ ]:

#EFFACER LES BV A L'ETRANGER
liste_a_effacer=["ZD","ZA","ZB","ZN","ZP","ZZ","ZM","ZC","ZX","ZS","ZW"]
for i in liste_a_effacer:
    data_premier = data_premier[data_premier["Code du département"]!=i]
print(data_premier.shape)
print(len(data_premier["Code du département"].unique()))

(66544, 30)
96

In [ ]:
data_premier["Code du bvote_sans 0 devant"] = data_premier["Code du bvote"].copy()
data_premier.head(4)

,Code du département,Libellé du département,Code de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11,Code du bvote_sans 0 devant
0,01,Ain,04,001,L'Abergement-Clémenciat,0001,598,92,506,2,9,495,DUPONT-AIGNAN,Nicolas,34,LE PEN,Marine,126,MACRON,Emmanuel,119,HAMON,Benoît,29,MÉLENCHON,Jean-Luc,59,FILLON,François,110,0001
1,01,Ain,05,002,L'Abergement-de-Varey,0001,209,25,184,6,2,176,DUPONT-AIGNAN,Nicolas,6,LE PEN,Marine,48,MACRON,Emmanuel,37,HAMON,Benoît,13,MÉLENCHON,Jean-Luc,33,FILLON,François,34,0001
2,01,Ain,05,004,Ambérieu-en-Bugey,0001,1116,233,883,17,6,860,DUPONT-AIGNAN,Nicolas,58,LE PEN,Marine,233,MACRON,Emmanuel,156,HAMON,Benoît,47,MÉLENCHON,Jean-Luc,216,FILLON,François,116,0001
3,01,Ain,05,004,Ambérieu-en-Bugey,0002,1128,256,872,19,3,850,DUPONT-AIGNAN,Nicolas,42,LE PEN,Marine,234,MACRON,Emmanuel,183,HAMON,Benoît,51,MÉLENCHON,Jean-Luc,175,FILLON,François,124,0002

In [ ]:
# CORRIGER PARIS
for i in range(data_premier.shape[0]):
    if data_premier.iloc[i,1]=="Paris":
        data_premier.iloc[i,3]=str(75100+int(data_premier.iloc[i,5][:2]))[2:]
    if data_premier.iloc[i,4]=="Lyon":
        data_premier.iloc[i,3]=str(69380+int(data_premier.iloc[i,5][:2]))[2:]
    if data_premier.iloc[i,4]=="Marseille":
        data_premier.iloc[i,3]=str(13200+int(data_premier.iloc[i,5][:2]))[2:]

In [ ]:
for i in data_premier.index :
    if data_premier.loc[i,"Code du bvote_sans 0 devant"][0]=="0":
        data_premier.loc[i,"Code du bvote_sans 0 devant"] = data_premier.loc[i,"Code du bvote_sans 0 devant"][1:]
        if data_premier.loc[i,"Code du bvote_sans 0 devant"][0] =="0":
            data_premier.loc[i,"Code du bvote_sans 0 devant"] = data_premier.loc[i,"Code du bvote_sans 0 devant"][1:]
            if data_premier.loc[i,"Code du bvote_sans 0 devant"][0] =="0":
                data_premier.loc[i,"Code du bvote_sans 0 devant"] = data_premier.loc[i,"Code du bvote_sans 0 devant"][1:]

In [ ]:
data_premier

,Code du département,Libellé du département,Code de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11,Code du bvote_sans 0 devant
0,01,Ain,04,001,L'Abergement-Clémenciat,0001,598,92,506,2,9,495,DUPONT-AIGNAN,Nicolas,34,LE PEN,Marine,126,MACRON,Emmanuel,119,HAMON,Benoît,29,MÉLENCHON,Jean-Luc,59,FILLON,François,110,1
1,01,Ain,05,002,L'Abergement-de-Varey,0001,209,25,184,6,2,176,DUPONT-AIGNAN,Nicolas,6,LE PEN,Marine,48,MACRON,Emmanuel,37,HAMON,Benoît,13,MÉLENCHON,Jean-Luc,33,FILLON,François,34,1
2,01,Ain,05,004,Ambérieu-en-Bugey,0001,1116,233,883,17,6,860,DUPONT-AIGNAN,Nicolas,58,LE PEN,Marine,233,MACRON,Emmanuel,156,HAMON,Benoît,47,MÉLENCHON,Jean-Luc,216,FILLON,François,116,1
3,01,Ain,05,004,Ambérieu-en-Bugey,0002,1128,256,872,19,3,850,DUPONT-AIGNAN,Nicolas,42,LE PEN,Marine,234,MACRON,Emmanuel,183,HAMON,Benoît,51,MÉLENCHON,Jean-Luc,175,FILLON,François,124,2
4,01,Ain,05,004,Ambérieu-en-Bugey,0003,1116,227,889,11,4,874,DUPONT-AIGNAN,Nicolas,47,LE PEN,Marine,218,MACRON,Emmanuel,191,HAMON,Benoît,53,MÉLENCHON,Jean-Luc,182,FILLON,François,149,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66539,95,Val-d'Oise,08,680,Villiers-le-Bel,0011,1199,345,854,13,7,834,DUPONT-AIGNAN,Nicolas,27,LE PEN,Marine,135,MACRON,Emmanuel,157,HAMON,Benoît,58,MÉLENCHON,Jean-Luc,283,FILLON,François,132,11
66540,95,Val-d'Oise,08,680,Villiers-le-Bel,0012,981,317,664,11,9,644,DUPONT-AIGNAN,Nicolas,17,LE PEN,Marine,96,MACRON,Emmanuel,157,HAMON,Benoît,67,MÉLENCHON,Jean-Luc,193,FILLON,François,87,12
66541,95,Val-d'Oise,08,680,Villiers-le-Bel,0013,713,275,438,12,13,413,DUPONT-AIGNAN,Nicolas,5,LE PEN,Marine,41,MACRON,Emmanuel,92,HAMON,Benoît,41,MÉLENCHON,Jean-Luc,192,FILLON,François,28,13
66542,95,Val-d'Oise,09,682,Villiers-le-Sec,0001,120,10,110,3,1,106,DUPONT-AIGNAN,Nicolas,5,LE PEN,Marine,17,MACRON,Emmanuel,26,HAMON,Benoît,10,MÉLENCHON,Jean-Luc,21,FILLON,François,21,1
66543,95,Val-d'Oise,01,690,Wy-dit-Joli-Village,0001,309,46,263,2,0,261,DUPONT-AIGNAN,Nicolas,14,LE PEN,Marine,47,MACRON,Emmanuel,70,HAMON,Benoît,8,MÉLENCHON,Jean-Luc,45,FILLON,François,72,1

In [ ]:
# IL N'Y A PAS DE DOUBLONS

In [ ]:
data_premier["commune_code"]=data_premier["Code du département"]+data_premier["Code de la commune"]
data_premier.head(1)

,Code du département,Libellé du département,Code de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11,Code du bvote_sans 0 devant,commune_code
0,01,Ain,04,001,L'Abergement-Clémenciat,0001,598,92,506,2,9,495,DUPONT-AIGNAN,Nicolas,34,LE PEN,Marine,126,MACRON,Emmanuel,119,HAMON,Benoît,29,MÉLENCHON,Jean-Luc,59,FILLON,François,110,1,01001

In [ ]:
########################################################################
data_recensement_orig = pd.read_csv("C:/Users/Christian/Desktop/IRIS_BV_final/PRESIDENTIELLES/RECENSEMENT_IRIS__BV_reconcialiation.txt",sep=";", header=0, low_memory=False, dtype=str)
data_recensement = data_recensement_orig.copy()
data_recensement = data_recensement[data_recensement["ID_BV"]!="4145"]
print(data_recensement.shape)
data_recensement.head(1)

(78397, 81)

,IRIS,ID_BV,commune_code,libelle,code,Code du bvote,Code du bvote_sans 0 devant,libelle_bv,num_voie,voie,code_postal,commune,canton_code,circonscription_code,longitude,latitude,geo_score,C17_MEN,C17_MENPSEUL,C17_MENHSEUL,C17_MENFSEUL,C17_MENSFAM,C17_MENFAM,C17_MENCOUPSENF,C17_MENCOUPAENF,C17_MENFAMMONO,C17_PMEN,C17_PMEN_MENPSEUL,C17_PMEN_MENHSEUL,C17_PMEN_MENFSEUL,C17_PMEN_MENSFAM,C17_PMEN_MENFAM,C17_PMEN_MENCOUPSENF,C17_PMEN_MENCOUPAENF,C17_PMEN_MENFAMMONO,P17_POP15P,P17_POP1524,P17_POP2554,P17_POP5579,P17_POP80P,P17_POPMEN15P,P17_POPMEN1524,P17_POPMEN2554,P17_POPMEN5579,P17_POPMEN80P,P17_POP15P_PSEUL,P17_POP1524_PSEUL,P17_POP2554_PSEUL,P17_POP5579_PSEUL,P17_POP80P_PSEUL,P17_POP15P_MARIEE,P17_POP15P_PACSEE,P17_POP15P_CONCUB_UNION_LIBRE,P17_POP15P_VEUFS,P17_POP15P_DIVORCEE,P17_POP15P_CELIBATAIRE,C17_MEN_CS1,C17_MEN_CS2,C17_MEN_CS3,C17_MEN_CS4,C17_MEN_CS5,C17_MEN_CS6,C17_MEN_CS7,C17_MEN_CS8,C17_PMEN_CS1,C17_PMEN_CS2,C17_PMEN_CS3,C17_PMEN_CS4,C17_PMEN_CS5,C17_PMEN_CS6,C17_PMEN_CS7,C17_PMEN_CS8,C17_FAM,C17_COUPAENF,C17_FAMMONO,C17_COUPSENF,C17_NE24F0,C17_NE24F1,C17_NE24F2,C17_NE24F3,C17_NE24F4P
0,721910000,17428,72191,Mayet,1,0001,1,ECOLE ST EXUPERY NORD,NaN,Rue Paul FOURNIER,72360,MAYET,72-08,72-03,0.271986000000000,47.759019000000002,0.94,1372.65678220089,447.579121498123,172.928296942457,274.650824555666,25.0027324900068,900.074928212759,503.362514570496,331.497706032145,65.2147076101184,3032.89428399957,447.579121498123,172.928296942457,274.650824555666,69.8756207737611,2515.43954172768,1056.07476690597,1299.08322648915,160.28154833256,2586.4560091875,246.675066330521,1042.37837329437,920.389018607399,377.01355095521,2476.44042734743,246.675066330521,1042.37837329437,908.3873187703,278.999668952236,455.716923707181,13.2239285897173,125.118708964248,194.290027741231,123.084258411984,1288.91525550116,84.530200374592,324.373782323855,305.360627814329,136.621543950553,446.654599223008,35.2223295589629,85.279155520177,24.8624749303227,124.925647361331,194.850379405266,275.1411906951,591.734387098183,40.6412176315461,75.1515734910646,209.166325355455,84.1941983749051,357.77696798547,561.762877007348,755.406582053172,943.756209133682,45.6795505984689,900.074928212759,331.497706032145,65.2147076101184,503.362514570496,528.317902752867,135.04120453251,173.183821580618,49.0227639293319,14.5092354174314

In [ ]:
data_recensement=data_recensement[["IRIS","ID_BV","commune_code","libelle","Code du bvote_sans 0 devant","longitude","latitude"]]

for i in data_recensement.columns:
    data_recensement.loc[:,i]=data_recensement.loc[:,i].astype(str)

In [ ]:
data_recensement.info()
data_recensement.head(1)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 78397 entries, 0 to 78397
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IRIS                         78397 non-null  object
 1   ID_BV                        78397 non-null  object
 2   commune_code                 78397 non-null  object
 3   libelle                      78397 non-null  object
 4   Code du bvote_sans 0 devant  78397 non-null  object
 5   longitude                    78397 non-null  object
 6   latitude                     78397 non-null  object
dtypes: object(7)
memory usage: 4.8+ MB

,IRIS,ID_BV,commune_code,libelle,Code du bvote_sans 0 devant,longitude,latitude
0,721910000,17428,72191,Mayet,1,0.271986000000000,47.759019000000002

In [ ]:
# PAS DE 0
for i in data_recensement.index :
    try :
        data_recensement.loc[i,"Code du bvote_sans 0 devant"] = str(int(data_recensement.loc[i,"Code du bvote_sans 0 devant"]))
    except:
        continue
        
print((data_recensement["Code du bvote_sans 0 devant"]=="01").sum())

0

In [ ]:
for i in data_recensement.index :
    try:
        int(data_recensement.loc[i,"Code du bvote_sans 0 devant"])
    except:
        print(data_recensement.loc[i,"Code du bvote_sans 0 devant"])

1-1
1 - 2
1 - 1
L-2
L-1
L-3
1 - 2
24.1
1 - 1
1 - 1
17-84
17-81
17-82
17-83
18-43
18-41
18-42
16-11
16-42
16-13
16-41
16-43
16-12
15-36
15-35
15-33
15-31
15-32
15-37
15-34
1 - 2
1 - 1
1 - 1
2 - 1
1 - 2
1-2
1 - 1
1 - 1
1 - 1
1 - 1
2 - 2
2 - 1
1 - 1
1 - 1
1 - 1
2-1
1-1
1 - 2
83A
2-1
1-1
1-2
BUR
1 - 1
B04
1 - 2
15-41
15-21
15-22
15-42
1 - 1
1 - 1
1 - 1
1 - 2
H21
H11
M1
1 - 1
1 - 2
A-1
A-2
17-41
17-42
1 - 1
1 - 1
1 - 1
1 - 2
1 - 1
1 - 2
2 - 2
1-2
1 - 2
1 - 1
1 - 1
1 - 1
1 - 1
1 - 1
1 - 2
1 - 1
1 - 2
1 - 1
1 - 2
1 - 2
1 - 1
1 - 1
1 - 1
1 - 2
1 - 1
1 - 2
1 - 1
1-1
1 - 2
1 - 1
1-2
1 - 1
B02
B01
1 - 2
1 - 2
1 - 1
1 - 1
1 - 2
1 - 2
1 - 1
1-2
2-2
M1
1A
6C
5C
4B
2A
3B
E-3
E-1
E-2
1 - 2
1 - 2
192A
1 - 1
1-1
A1
1-2
1 - 1
Bureau 1
Bureau 2
1-1
1 - 1
15-71
15-72
15-73
1 - 1
1 - 1
1LC
1 - 2
1 - 2
A2
A1
1 - 2
1 - 1
1 - 3
1 - 1
1 - 2
1 - 1
1 - 1
1 - 3
16-31
16-34
16-36
16-33
16-32
16-35
1 - 2
1-1
1 - 1
F31
F11
1 - 1
A1
1-1
1 - 1
1 - 1
1-1
1.1
3.1
3.2
1-2
A1
A2
1 - 2
1 - 1
1-1
2 - 2
1-1
10.3
10.2
10.1
1 - 2
1 - 3
1 - 1
1 - 2
1 - 2
1 - 2
1-2
1 - 1
B12
B13
1-2
1 - 2
2 - 2
1 - 2
1 - 1
1 - 1
1 - 1
15.1
15.2
B11
5C
1A
1D
1C
5A
1E
5B
1-2
1 - 1
K-1
K-2
1 - 1
1 - 1
15-57
15-58
15-55
15-51
15-52
15-53
15-54
15-56
A1
1 - 2
1 - 1
1 - 1
2 - 1
1 - 2
1 - 1
1-2
3-2
4-2
B-1
B-2
1 - 1
1 - 2
1 - 1
1 - 2
1 - 1
G-1
G-2
1-3
2-2
1 - 1
B07
1 - 1
1 - 1
1 - 3
1-2
1 - 2
2 - 2
1 - 1
2 - 1
1 - 2
2 - 2
B1
1 - 1
69A
1 - 1
1 - 1
1 - 1
B15
B14
1 - 2
1 - 1
112A
1 - 1
81A
1N
2N
1 - 1
1-1
1-2
1 - 1
4.1
4.2
4.3
4.4
182A
1 - 1
1 - 1
17-11
17-12
1 - 1
1 - 1
1 - 2
1-1
D11
1-2
1 - 2
1-2
1 - 1
1 - 1
1-1
1 - 1
F-1
F-2
1 - 2
1-1
1 - 1
1 - 1
D21
A11
A21
1 - 2
1 - 2
18-51
1 - 1
1 - 2
1 - 1
1 - 1
1-2
A1
1 - 2
1 - 1
1 - 1
2 - 1
A1
A2
1 - 1
unique
17-71
17-72
3C
3D
3B
3A
3E
1 - 2
B11
1 - 2
1 - 1
1 - 2
1 - 2
17-31
17-32
1 - 1
J-2
J-1
1- 1
19.2
19.1
19.3
1 - 1
17-52
17-51
17-53
1 - 1
1 - 1
1-2
B1
1 - 2
1 - 1
1 - 1
1 - 1
1 - 1
198A
23.1
23.2
23.3
1 - 1
1 - 1
2 - 2
2 - 1
1 - 2
1 - 2
C-3
D-1
D-2
C-2
D-3
1 - 1
1 - 1
20.1
18.1
18.2
18.3
1-1
1 - 1
1 - 2
7A
8A
1 - 1
1-2
1 - 2
1-3
1 - 3
1 - 2
1 - 1
1 - 2
18-24
18-21
18-25
18-22
18-23
1 - 3
1 - 2
1-1
1 - 1
1 - 2
1 - 1
C21
F21
G11
G21
1 - 3
1 - 1
1 - 1
1 - 2
1 - 1
1 - 1
1 - 1
1 - 2
1-2
1 - 2
1 - 1
1 - 1
1 - 1
1 - 1
1 - 2
1 - 1
1 - 2
1 - 2
1 - 1
2-2
1-2
1 - 2
B06
14.1
14.2
1 - 1
1 - 1
15-61
15-62
15-63
1-1
2-1
1-1
1 - 2
1 - 3
1 - 2
H-1
1 - 1
1 - 2
1 - 1
1 - 1
2S
1S
1 - 2
1 - 1
1-2
1C
4C
2C
3C
A1
18-31
1 - 1
1 - 1
C-1
2-2
1-2
3-2
3-3
4-3
4-2
1 - 2
1 - 1
1 - 2
1 - 1
1 - 1
1 - 2
1 - 3
2A
3A
4A
6A
5A
1A
1 - 1
1 - 1
16-61
16-62
1 - 2
1 - 1
22.1
22.2
1 - 1
1 - 1
1 - 1
1 - 2
1 - 1
1 - 2
1 - 1
1 - 1
1 - 2
1 - 1
M1 - 3
1 - 1
1 - 2
1 - 1
1 - 2
1 - 2
2.2
2.1
16-52
16-51
1 - 1
E31
E21
E11
E41
1 - 2
18-32
1 - 1
1 - 2
1 - 1
6.1
6.2
1 - 1
1 - 1
1 - 1
1 - 3
1 - 2
B08
18-64
18-62
18-61
18-63
1 - 1
1 - 1
1 - 1
1 - 1
1 - 1
11.3
11.1
11.2
1 - 1
15-82
15-81
1 - 2
B03
1-3
1-2
9.2
9.1
7.1
7.2
9.3
7.3
1 - 1
1-1
1 - 2
1 - 1
1 - 1
1 - 1
B01
B02
B03
B05
1 - 2
1 - 1
1 - 1
12.1
18-11
18-12
17-21
B1
1-1
1 - 1
1 - 1
17-62
17-63
17-61
17-64
1 - 1
1 - 2
1-1
1 - 2
38B
1B
1-1
1 - 2
1 - 2
21.1
21.2
1 - 1
1-2
1 - 2
16.2
16.1
16.3
16.4
1 - 1
1 -1
1 - 1
16-23
16-21
16-22
1 - 2
B05
B10
1 - 1
1 - 1
1-1
1 - 1
1-2
1 - 2
1-3
1 - 1
1 -1
1 - 2
1 - 2
1 - 1
1 - 3
1 - 1
1-3
N-1
N-2
1 - 1
1 - 1
1 - 1
2 -1
17.1
17.3
17.2
1 - 1
1 -1
1 - 1
1 - 1
1 - 2
1 - 2
1-2
1 - 1
1 - 1
A5
A1
A2
A6
A4
A3
1 - 2
1-2
1 - 1
1-1
1 - 1
3 - 1
4 - 1
2 - 1
13 - 2
3 - 1
B01
B05
B03
B04
B06
B02
1 - 1
1 - 2
1 - 1
1 - 2
1 - 1
1 - 1
1 - 1
Unique
UN
1 - 1
1 - 2
1 - 1
B04
1 - 1
15-11
13.3
13.1
13.2
C09
1 - 1
8.1
1 - 1
1 - 1
1 - 1
1-1
1-1
1-2
1 - 1
1-2
1 - 1
5.2
5.1
M-1
1 - 2
198A
unique
7.1
7.2
7.3
3C
3D
3B
3A
3E
E-3
E-1
E-2
1 - 1
16-23
16-21
16-22
1 - 1
1 - 1
2 - 2
A2
1 - 1
1 - 2
1 - 1
J-2
J-1
1-2
1A
6C
5C
4B
2A
3B
1 - 2
15-36
15-35
15-33
15-31
15-32
15-37
15-34
1 - 1
1 - 2
81A
16-52
16-51
K-1
K-2
4.1
4.2
4.3
4.4
18-64
18-62
18-61
18-63
69A
1 - 1
15-61
15-62
15-63
17-62
17-63
17-61
17-64
1-1
1 - 1
81A
3 - 1
4 - 1
1 - 1
1A
1D
1C
1E
1 - 2
14.1
14.2
18.1
18.2
18.3
F31
F11
22.1
22.2
5.2
5.1
3.1
3.2
3C
3D
3B
3A
3E
16-31
16-34
16-36
16-33
16-32
16-35
1 - 1
1 - 1
1 - 1
18-43
18-41
18-42
6.1
6.2
1 - 2
4.1
4.2
4.3
4.4
1 - 1
1 - 1
1 - 2
F31
F11
1 - 1
1 -1
1 - 2
112A
19.2
19.1
19.3
F31
F11
1-2
15.1
15.2
23.1
23.2
23.3
D11
1 - 1
16-31
16-34
16-36
16-33
16-32
16-35
1 - 2
1 -1
1-2
15-21
15-22
21.1
21.2
1 - 1
17.1
17.3
17.2
1 - 1
1 - 2
1 - 1
81A
18-11
18-12
1 - 1
17-11
17-12
1 - 2
1 - 1
1 - 1
15-57
15-58
15-55
15-51
15-52
15-53
15-54
15-56
1 - 2
18-51
1 - 1
1 - 1
1 - 2
1 - 1
1 - 1
1 - 1
10.3
10.2
10.1
112A
B11
16-61
16-62
1-2
1-2
1 - 2
2-2
15-57
15-58
15-55
15-51
15-52
15-53
15-54
15-56
5C
5A
5B
69A
1-2
17-62
17-63
17-61
17-64
16-52
16-51
1 - 2
7.1
7.2
7.3
1 - 2
1 - 1
1 - 2
81A
1 - 2
3-2
1 - 2
2 - 2
2 - 1
1 - 1
B10
5.2
5.1
13.3
13.1
13.2
1 - 2
17-71
17-72
B01
B05
B03
B04
B06
B02
1 - 1
A2
18-64
18-62
18-61
18-63
1-2
16.2
16.1
16.3
16.4
1B
1-1
1 - 2
20.1
1 - 2
1 - 2
1 - 1
16-42
16-41
16-43
23.1
23.2
23.3
1 - 1
1 - 2
1 - 1
1 - 2
20.1
1-2
1-1
17-41
17-42
1 - 1
15-36
15-35
15-33
15-31
15-32
15-37
15-34
1 - 1
1A
6C
5C
4B
2A
3B
1- 1
15-57
15-58
15-55
15-51
15-52
15-53
15-54
15-56
E31
E21
E11
E41
D-1
D-2
D-3
A1
1 -1
14.1
14.2
J-2
J-1
15-41
15-42
M1
1- 1
1-1
18-24
18-21
18-25
18-22
18-23
3.1
3.2
1 - 3
L-3
1 - 1
1-2
1 - 1
1 - 1
1A
1D
1C
1E
1 - 1
182A
1 - 1
15-57
15-58
15-55
15-51
15-52
15-53
15-54
15-56
1-2
2S
1S
1 - 1
7.1
7.2
7.3
1 - 1
18.1
18.2
18.3
B15
17-52
17-51
17-53
22.1
22.2
1 - 1
5C
5A
5B
1 - 1
1 - 1
1 - 1
1 - 2
15-41
15-42
7.1
7.2
7.3
1 - 1
1-2
1 - 1
16-31
16-34
16-36
16-33
16-32
16-35
B01
B05
B03
B04
B06
B02
A11
A21
1-1
1 - 1
1 - 2

In [ ]:

# 
print(data_premier.shape, data_recensement.shape)

data_premier.head(1)
data_recensement.head(1)

(66544, 32) (78397, 7)

,IRIS,ID_BV,commune_code,libelle,Code du bvote_sans 0 devant,longitude,latitude
0,721910000,17428,72191,Mayet,1,0.271986000000000,47.759019000000002

In [ ]:
####
CREATION=pd.read_csv("C:/Users/Christian/Desktop/IRIS_BV_final/PRESIDENTIELLES/CREATION/CREATION.txt",sep=";", header=0, dtype=str)
CREATION=CREATION[CREATION["ID_BV"]!="4145"]
CREATION.head(2)

CREATION["FLAG"]="0"

In [ ]:
jjj = data_recensement.merge(CREATION, how="left")
flag = jjj[jjj["longitude"].isnull()==False] # tous la

In [ ]:
flag_0 = flag[flag["FLAG"]=="0"] # ok
flag_1 = flag[flag["FLAG"]!="0"] # absent
#flag_1 = flag_1.fillna("1")

In [ ]:
flag_0["IRIS"].value_counts().shape[0]+flag_1["IRIS"].value_counts().shape[0]

48595

In [ ]:

IRIS_COMPLET = flag_0.merge(data_premier, on = ["commune_code","Code du bvote_sans 0 devant"],how= "left")
print(IRIS_COMPLET.shape)
IRIS_COMPLET.head(2)

(59032, 38)

,IRIS,ID_BV,commune_code,libelle,Code du bvote_sans 0 devant,longitude,latitude,FLAG,Code du département,Libellé du département,Code de la circonscription,Code de la commune,Libellé de la commune,Code du bvote,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11
0,721910000,17428,72191,Mayet,1,0.271986000000000,47.759019000000002,0,72,Sarthe,03,191,Mayet,0001,1405,223,1182,29,11,1142,DUPONT-AIGNAN,Nicolas,48,LE PEN,Marine,332,MACRON,Emmanuel,185,HAMON,Benoît,45,MÉLENCHON,Jean-Luc,178,FILLON,François,298
1,721910000,55161,72191,Mayet,2,0.271986000000000,47.759019000000002,0,72,Sarthe,03,191,Mayet,0002,916,160,756,15,5,736,DUPONT-AIGNAN,Nicolas,33,LE PEN,Marine,190,MACRON,Emmanuel,125,HAMON,Benoît,37,MÉLENCHON,Jean-Luc,124,FILLON,François,200

In [ ]:
IRIS_COMPLET_OUI = IRIS_COMPLET[IRIS_COMPLET["Voix_11"].isnull()==False]
IRIS_COMPLET_NON = IRIS_COMPLET[IRIS_COMPLET["Voix_11"].isnull()] #absent

IRIS_COMPLET_OUI["IRIS"].value_counts().shape[0],IRIS_COMPLET_NON["IRIS"].value_counts().shape[0]

(36185, 1370)

In [ ]:
# CA VEUT DIRE QU'IL Y A DES IRIS DANS OUI ET NON
IRIS_COMPLET_OUI["IRIS"].value_counts().shape[0]+IRIS_COMPLET_NON["IRIS"].value_counts().shape[0]#-IRIS_COMPLET["IRIS"].value_counts().shape[0]

37555

In [ ]:
join_left = data_recensement.merge(IRIS_COMPLET_OUI, on="IRIS", how="left")
IRIS_A_COMPLETER = join_left[join_left["Voix_11"].isnull()][["IRIS","commune_code_x","libelle_x"]].drop_duplicates(subset="IRIS")
IRIS_A_COMPLETER.columns=["IRIS","commune_code","libelle"]
IRIS_A_COMPLETER

             IRIS commune_code                    libelle
23      231670000        23167                     Sannat
506     422620000        42262  Saint-Maurice-en-Gourgois
990     714540000        71454       Saint-Martin-du-Mont
1109    710410000        71041          Bois-Sainte-Marie
1121    593110000        59311                   Honnechy
...           ...          ...                        ...
159024  930050101        93005           Aulnay-sous-Bois
159026  910270114        91027                 Athis-Mons
159028  104300000        51377                 Montépreux
159029  394510000        39452                       Rans
159030  930010501        93001              Aubervilliers

[12405 rows x 3 columns]

In [ ]:
IRIS_COMPLET_OUI["IRIS"].value_counts().shape[0]+IRIS_A_COMPLETER["IRIS"].value_counts().shape[0]

48590

In [ ]:
pd.concat([IRIS_COMPLET_OUI,IRIS_A_COMPLETER], axis=0)["IRIS"].value_counts().shape[0]

48590

In [ ]:
IRIS_COMPLET_OUI[IRIS_COMPLET_OUI["libelle"]=="Les Sables-d'Olonne"][["IRIS","Code du bvote_sans 0 devant","commune_code","Inscrits"]]#["Inscrits"].astype(int).sum()

            IRIS Code du bvote_sans 0 devant commune_code Inscrits
8446   851940103                           4        85194     1179
8447   851940103                           3        85194     1084
26177  851940101                           8        85194     1196
31973  851940106                          11        85194     1168
31974  851940106                          12        85194     1156
31975  851940106                           5        85194     1231
34420  851940104                           1        85194     1147
34421  851940104                           2        85194     1084
34422  851940104                           9        85194     1050
34423  851940104                          10        85194     1195
44045  851940201                           6        85194     1174
49393  851940102                           7        85194     1226

In [ ]:
data_premier[data_premier["Libellé de la commune"]=="Les Sables-d'Olonne"][["Code du bvote_sans 0 devant","commune_code","Inscrits"]]

      Code du bvote_sans 0 devant commune_code Inscrits
59844                           1        85194     1147
59845                           2        85194     1084
59846                           3        85194     1084
59847                           4        85194     1179
59848                           5        85194     1231
59849                           6        85194     1174
59850                           7        85194     1226
59851                           8        85194     1196
59852                           9        85194     1050
59853                          10        85194     1195
59854                          11        85194     1168
59855                          12        85194     1156

In [ ]:
###COMPLETER LES IRIS PAR LES COMMUNES : ON CHERCHE LES COMMUNES POUR LEQUELS IL Y A UNE SEUL BV
table_nb_bv_par_commune = CREATION[["commune_code","Code du bvote_sans 0 devant"]].groupby("commune_code", as_index=False).count()
table_nb_bv_par_commune.columns = ["commune_code","nb_bv_par_commune"]
table_nb_bv_par_commune

      commune_code  nb_bv_par_commune
0            01001                  1
1            01002                  1
2            01004                  8
3            01005                  1
4            01006                  1
...            ...                ...
29172        95676                  1
29173        95678                  1
29174        95680                 13
29175        95682                  1
29176        95690                  1

[29177 rows x 2 columns]

In [ ]:
# commune nb bv
table_1 = table_nb_bv_par_commune[table_nb_bv_par_commune["nb_bv_par_commune"]==1]
table_2 = table_nb_bv_par_commune[table_nb_bv_par_commune["nb_bv_par_commune"]!=1]
table_1

      commune_code  nb_bv_par_commune
0            01001                  1
1            01002                  1
3            01005                  1
4            01006                  1
6            01008                  1
...            ...                ...
29171        95675                  1
29172        95676                  1
29173        95678                  1
29175        95682                  1
29176        95690                  1

[23043 rows x 2 columns]

In [ ]:
IRIS_A_COMPLETER_1 = IRIS_A_COMPLETER.merge(table_1) #, how="left")
IRIS_A_COMPLETER_2 = IRIS_A_COMPLETER.merge(table_2)
IRIS_A_COMPLETER_1

           IRIS commune_code                    libelle  nb_bv_par_commune
0     231670000        23167                     Sannat                  1
1     422620000        42262  Saint-Maurice-en-Gourgois                  1
2     714540000        71454       Saint-Martin-du-Mont                  1
3     710410000        71041          Bois-Sainte-Marie                  1
4     711410000        71041          Bois-Sainte-Marie                  1
...         ...          ...                        ...                ...
5595  574140000        57380   Laneuveville-lès-Lorquin                  1
5596  100850000        10085                    Charmoy                  1
5597  084700000        08098              Champigneulle                  1
5598  621620000        62286               Ecquedecques                  1
5599  050680000        05176                  Valserres                  1

[5600 rows x 4 columns]

In [ ]:
######################## RESULTATS PAR COMMUNE #########################
for k in ["Inscrits","Abstentions","Votants","Blancs","Nuls","Exprimés","Voix_1","Voix_2","Voix_3","Voix_4","Voix_9","Voix_11"]:
    data_premier.loc[:,k] = data_premier.loc[:,k].astype(float)

somme_commune = data_premier[["commune_code","Inscrits","Abstentions","Votants","Blancs","Nuls","Exprimés","Voix_1","Voix_2","Voix_3","Voix_4","Voix_9","Voix_11"]].groupby("commune_code", as_index=False).sum()
somme_commune

,commune_code,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,01001,598.0,92.0,506.0,2.0,9.0,495.0,34.0,126.0,119.0,29.0,59.0,110.0
1,01002,209.0,25.0,184.0,6.0,2.0,176.0,6.0,48.0,37.0,13.0,33.0,34.0
2,01004,8586.0,1962.0,6624.0,114.0,58.0,6452.0,346.0,1667.0,1332.0,344.0,1412.0,1084.0
3,01005,1172.0,215.0,957.0,21.0,3.0,933.0,45.0,306.0,191.0,37.0,126.0,197.0
4,01006,99.0,20.0,79.0,2.0,0.0,77.0,4.0,18.0,15.0,3.0,19.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35318,95676,382.0,43.0,339.0,5.0,0.0,334.0,16.0,75.0,47.0,10.0,64.0,110.0
35319,95678,593.0,48.0,545.0,8.0,2.0,535.0,33.0,112.0,124.0,27.0,85.0,139.0
35320,95680,13213.0,4392.0,8821.0,163.0,100.0,8558.0,210.0,1256.0,1936.0,728.0,2932.0,1109.0
35321,95682,120.0,10.0,110.0,3.0,1.0,106.0,5.0,17.0,26.0,10.0,21.0,21.0
35322,95690,309.0,46.0,263.0,2.0,0.0,261.0,14.0,47.0,70.0,8.0,45.0,72.0

In [ ]:
# ON COMPLETE LES IRIS 

IRIS_COMPLET_1 = IRIS_A_COMPLETER_1.merge(somme_commune)
IRIS_COMPLET_1

,IRIS,commune_code,libelle,nb_bv_par_commune,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,231670000,23167,Sannat,1,299.0,45.0,254.0,8.0,3.0,243.0,11.0,36.0,64.0,17.0,53.0,47.0
1,422620000,42262,Saint-Maurice-en-Gourgois,1,1206.0,179.0,1027.0,13.0,5.0,1009.0,62.0,374.0,193.0,54.0,123.0,168.0
2,714540000,71454,Saint-Martin-du-Mont,1,141.0,25.0,116.0,3.0,2.0,111.0,7.0,24.0,33.0,5.0,19.0,19.0
3,710410000,71041,Bois-Sainte-Marie,1,87.0,15.0,72.0,1.0,1.0,70.0,4.0,24.0,13.0,3.0,9.0,14.0
4,711410000,71041,Bois-Sainte-Marie,1,87.0,15.0,72.0,1.0,1.0,70.0,4.0,24.0,13.0,3.0,9.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5595,574140000,57380,Laneuveville-lès-Lorquin,1,88.0,14.0,74.0,2.0,0.0,72.0,6.0,30.0,11.0,0.0,11.0,13.0
5596,100850000,10085,Charmoy,1,48.0,6.0,42.0,2.0,0.0,40.0,2.0,6.0,8.0,1.0,5.0,17.0
5597,084700000,08098,Champigneulle,1,59.0,7.0,52.0,1.0,0.0,51.0,4.0,17.0,12.0,0.0,5.0,12.0
5598,621620000,62286,Ecquedecques,1,360.0,51.0,309.0,2.0,1.0,306.0,21.0,98.0,57.0,13.0,49.0,52.0
5599,050680000,05176,Valserres,1,194.0,30.0,164.0,2.0,1.0,161.0,14.0,36.0,26.0,12.0,42.0,20.0

In [ ]:
IRIS_COMPLET_2 = IRIS_A_COMPLETER_2.merge(somme_commune)
IRIS_COMPLET_2

,IRIS,commune_code,libelle,nb_bv_par_commune,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,900100201,90010,Belfort,28,26162.0,7806.0,18356.0,338.0,172.0,17846.0,657.0,3625.0,3863.0,1376.0,4162.0,3314.0
1,900100502,90010,Belfort,28,26162.0,7806.0,18356.0,338.0,172.0,17846.0,657.0,3625.0,3863.0,1376.0,4162.0,3314.0
2,900100102,90010,Belfort,28,26162.0,7806.0,18356.0,338.0,172.0,17846.0,657.0,3625.0,3863.0,1376.0,4162.0,3314.0
3,900100203,90010,Belfort,28,26162.0,7806.0,18356.0,338.0,172.0,17846.0,657.0,3625.0,3863.0,1376.0,4162.0,3314.0
4,900100501,90010,Belfort,28,26162.0,7806.0,18356.0,338.0,172.0,17846.0,657.0,3625.0,3863.0,1376.0,4162.0,3314.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6800,614610000,61167,La Ferté-en-Ouche,10,2323.0,443.0,1880.0,19.0,13.0,1848.0,125.0,543.0,298.0,60.0,219.0,527.0
6801,850740000,85135,Mareuil-sur-Lay-Dissais,3,2094.0,314.0,1780.0,30.0,12.0,1738.0,87.0,369.0,477.0,76.0,265.0,390.0
6802,371980000,49228,Noyant-Villages,14,4179.0,831.0,3348.0,51.0,18.0,3279.0,169.0,888.0,548.0,147.0,445.0,907.0
6803,470850000,47207,Pompiey,2,168.0,15.0,153.0,4.0,2.0,147.0,8.0,45.0,27.0,9.0,26.0,17.0
6804,352780103,35189,Montgermont,3,2420.0,251.0,2169.0,33.0,15.0,2121.0,92.0,185.0,839.0,192.0,359.0,397.0

In [ ]:
IRIS_COMPLET_1["IRIS"].value_counts().shape[0]+IRIS_COMPLET_2["IRIS"].value_counts().shape[0]

12405

In [ ]:
pd.concat([IRIS_COMPLET_1,IRIS_COMPLET_2], axis=0)["IRIS"].value_counts().shape[0]

12405

In [ ]:
pd.concat([IRIS_COMPLET_1,IRIS_COMPLET_2, IRIS_COMPLET_OUI], axis=0)["IRIS"].value_counts().shape[0]

48590

In [ ]:
# changer les flags
IRIS_COMPLET_1 = IRIS_COMPLET_1.rename(columns={"nb_bv_par_commune":"FLAG"})
IRIS_COMPLET_2 = IRIS_COMPLET_2.rename(columns={"nb_bv_par_commune":"FLAG"})
IRIS_COMPLET_2["FLAG"] = 2

In [ ]:
IRIS_COMPLET_1.head(1)

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,231670000,23167,Sannat,1,299.0,45.0,254.0,8.0,3.0,243.0,11.0,36.0,64.0,17.0,53.0,47.0

In [ ]:
IRIS_COMPLET_1["Voix/Exprimés_1"] = round(IRIS_COMPLET_1["Voix_1"]/IRIS_COMPLET_1["Exprimés"]*100,2)
IRIS_COMPLET_1["Voix/Exprimés_2"] = round(IRIS_COMPLET_1["Voix_2"]/IRIS_COMPLET_1["Exprimés"]*100,2)
IRIS_COMPLET_1["Voix/Exprimés_3"] = round(IRIS_COMPLET_1["Voix_3"]/IRIS_COMPLET_1["Exprimés"]*100,2)
IRIS_COMPLET_1["Voix/Exprimés_4"] = round(IRIS_COMPLET_1["Voix_4"]/IRIS_COMPLET_1["Exprimés"]*100,2)
IRIS_COMPLET_1["Voix/Exprimés_9"] = round(IRIS_COMPLET_1["Voix_9"]/IRIS_COMPLET_1["Exprimés"]*100,2)
IRIS_COMPLET_1["Voix/Exprimés_11"] = round(IRIS_COMPLET_1["Voix_11"]/IRIS_COMPLET_1["Exprimés"]*100,2)

In [ ]:
IRIS_COMPLET_2["Voix/Exprimés_1"] = round(IRIS_COMPLET_2["Voix_1"]/IRIS_COMPLET_2["Exprimés"]*100,2)
IRIS_COMPLET_2["Voix/Exprimés_2"] = round(IRIS_COMPLET_2["Voix_2"]/IRIS_COMPLET_2["Exprimés"]*100,2)
IRIS_COMPLET_2["Voix/Exprimés_3"] = round(IRIS_COMPLET_2["Voix_3"]/IRIS_COMPLET_2["Exprimés"]*100,2)
IRIS_COMPLET_2["Voix/Exprimés_4"] = round(IRIS_COMPLET_2["Voix_4"]/IRIS_COMPLET_2["Exprimés"]*100,2)
IRIS_COMPLET_2["Voix/Exprimés_9"] = round(IRIS_COMPLET_2["Voix_9"]/IRIS_COMPLET_2["Exprimés"]*100,2)
IRIS_COMPLET_2["Voix/Exprimés_11"] = round(IRIS_COMPLET_2["Voix_11"]/IRIS_COMPLET_2["Exprimés"]*100,2)

In [ ]:
for k in ["Inscrits","Abstentions","Votants","Blancs","Nuls","Exprimés","Voix_1","Voix_2","Voix_3","Voix_4","Voix_9","Voix_11"]:
    IRIS_COMPLET_OUI[k] = IRIS_COMPLET_OUI[k].astype(float)

<ipython-input-44-302b5e36aab4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  IRIS_COMPLET_OUI[k] = IRIS_COMPLET_OUI[k].astype(float)

' \nIRIS_COMPLET_OUI["Voix/Exprimés_1"] = round(IRIS_COMPLET_OUI["Voix_1"]/IRIS_COMPLET_OUI["Exprimés"]*100,2)\nIRIS_COMPLET_OUI["Voix/Exprimés_2"] = round(IRIS_COMPLET_OUI["Voix_2"]/IRIS_COMPLET_OUI["Exprimés"]*100,2)\nIRIS_COMPLET_OUI["Voix/Exprimés_3"] = round(IRIS_COMPLET_OUI["Voix_3"]/IRIS_COMPLET_OUI["Exprimés"]*100,2)\nIRIS_COMPLET_OUI["Voix/Exprimés_4"] = round(IRIS_COMPLET_OUI["Voix_4"]/IRIS_COMPLET_OUI["Exprimés"]*100,2)\nIRIS_COMPLET_OUI["Voix/Exprimés_9"] = round(IRIS_COMPLET_OUI["Voix_9"]/IRIS_COMPLET_OUI["Exprimés"]*100,2)\nIRIS_COMPLET_OUI["Voix/Exprimés_11"] = round(IRIS_COMPLET_OUI["Voix_11"]/IRIS_COMPLET_OUI["Exprimés"]*100,2)\n'

In [ ]:
IRIS_COMPLET_1

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
0,231670000,23167,Sannat,1,299.0,45.0,254.0,8.0,3.0,243.0,11.0,36.0,64.0,17.0,53.0,47.0,4.53,14.81,26.34,7.00,21.81,19.34
1,422620000,42262,Saint-Maurice-en-Gourgois,1,1206.0,179.0,1027.0,13.0,5.0,1009.0,62.0,374.0,193.0,54.0,123.0,168.0,6.14,37.07,19.13,5.35,12.19,16.65
2,714540000,71454,Saint-Martin-du-Mont,1,141.0,25.0,116.0,3.0,2.0,111.0,7.0,24.0,33.0,5.0,19.0,19.0,6.31,21.62,29.73,4.50,17.12,17.12
3,710410000,71041,Bois-Sainte-Marie,1,87.0,15.0,72.0,1.0,1.0,70.0,4.0,24.0,13.0,3.0,9.0,14.0,5.71,34.29,18.57,4.29,12.86,20.00
4,711410000,71041,Bois-Sainte-Marie,1,87.0,15.0,72.0,1.0,1.0,70.0,4.0,24.0,13.0,3.0,9.0,14.0,5.71,34.29,18.57,4.29,12.86,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5595,574140000,57380,Laneuveville-lès-Lorquin,1,88.0,14.0,74.0,2.0,0.0,72.0,6.0,30.0,11.0,0.0,11.0,13.0,8.33,41.67,15.28,0.00,15.28,18.06
5596,100850000,10085,Charmoy,1,48.0,6.0,42.0,2.0,0.0,40.0,2.0,6.0,8.0,1.0,5.0,17.0,5.00,15.00,20.00,2.50,12.50,42.50
5597,084700000,08098,Champigneulle,1,59.0,7.0,52.0,1.0,0.0,51.0,4.0,17.0,12.0,0.0,5.0,12.0,7.84,33.33,23.53,0.00,9.80,23.53
5598,621620000,62286,Ecquedecques,1,360.0,51.0,309.0,2.0,1.0,306.0,21.0,98.0,57.0,13.0,49.0,52.0,6.86,32.03,18.63,4.25,16.01,16.99
5599,050680000,05176,Valserres,1,194.0,30.0,164.0,2.0,1.0,161.0,14.0,36.0,26.0,12.0,42.0,20.0,8.70,22.36,16.15,7.45,26.09,12.42

In [ ]:
IRIS_COMPLET_2[IRIS_COMPLET_2["libelle"]=="Les Sables-d'Olonne"]

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
201,851940301,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
202,851940204,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
203,851940203,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
204,851940302,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
205,851940303,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
206,851940305,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
207,851940304,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
208,851940205,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
209,851940105,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72

In [ ]:
#### SOMME 
#IRIS_COMPLET_OUI[IRIS_COMPLET_OUI["libelle"]=="Les Sables-d'Olonne"]
iris_somme_complet_oui= IRIS_COMPLET_OUI[["IRIS","Inscrits","Abstentions","Votants","Blancs","Nuls","Exprimés","Voix_1","Voix_2","Voix_3","Voix_4","Voix_9","Voix_11"]].groupby("IRIS", as_index=False).sum() 
iris_somme_complet_oui

,IRIS,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,010010000,598.0,92.0,506.0,2.0,9.0,495.0,34.0,126.0,119.0,29.0,59.0,110.0
1,010020000,209.0,25.0,184.0,6.0,2.0,176.0,6.0,48.0,37.0,13.0,33.0,34.0
2,010040101,4301.0,1011.0,3290.0,69.0,28.0,3193.0,172.0,861.0,624.0,172.0,754.0,463.0
3,010040201,1108.0,262.0,846.0,8.0,10.0,828.0,45.0,196.0,183.0,45.0,170.0,151.0
4,010040202,3177.0,689.0,2488.0,37.0,20.0,2431.0,129.0,610.0,525.0,127.0,488.0,470.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
36180,956800109,2418.0,898.0,1520.0,35.0,21.0,1464.0,38.0,195.0,344.0,111.0,576.0,131.0
36181,956800110,3331.0,1001.0,2330.0,36.0,25.0,2269.0,60.0,361.0,470.0,194.0,764.0,301.0
36182,956800113,2829.0,1048.0,1781.0,40.0,22.0,1719.0,33.0,195.0,412.0,151.0,675.0,184.0
36183,956820000,120.0,10.0,110.0,3.0,1.0,106.0,5.0,17.0,26.0,10.0,21.0,21.0
36184,956900000,309.0,46.0,263.0,2.0,0.0,261.0,14.0,47.0,70.0,8.0,45.0,72.0

In [ ]:
IRIS_COMPLET_OUI_FINAL = IRIS_COMPLET_OUI[["IRIS","commune_code","libelle"]].drop_duplicates(subset="IRIS").merge(iris_somme_complet_oui)
IRIS_COMPLET_OUI_FINAL

,IRIS,commune_code,libelle,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
0,721910000,72191,Mayet,2321.0,383.0,1938.0,44.0,16.0,1878.0,81.0,522.0,310.0,82.0,302.0,498.0
1,811990000,81199,Padiès,168.0,26.0,142.0,1.0,4.0,137.0,13.0,27.0,32.0,8.0,30.0,20.0
2,592250102,59225,Feignies,881.0,217.0,664.0,10.0,3.0,651.0,32.0,282.0,98.0,30.0,124.0,59.0
3,603970000,60397,Le Mesnil-Conteville,82.0,9.0,73.0,6.0,0.0,67.0,3.0,20.0,7.0,2.0,9.0,24.0
4,383820104,38382,Saint-Égrève,1815.0,345.0,1470.0,15.0,3.0,1452.0,45.0,144.0,562.0,103.0,271.0,291.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36180,674822901,67482,Strasbourg,832.0,273.0,559.0,8.0,3.0,548.0,20.0,153.0,87.0,40.0,162.0,46.0
36181,385450101,38545,Vif,4562.0,848.0,3714.0,60.0,12.0,3642.0,209.0,997.0,860.0,250.0,603.0,606.0
36182,740630000,74063,Châtel,1019.0,187.0,832.0,11.0,3.0,818.0,43.0,185.0,89.0,17.0,42.0,407.0
36183,951010000,95101,Bray-et-Lû,626.0,110.0,516.0,10.0,5.0,501.0,35.0,189.0,95.0,36.0,86.0,49.0
36184,384030000,38403,Saint-Jean-d'Hérans,291.0,57.0,234.0,2.0,1.0,231.0,9.0,53.0,58.0,26.0,47.0,32.0

In [ ]:
 
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_1"] = round(IRIS_COMPLET_OUI_FINAL["Voix_1"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_2"] = round(IRIS_COMPLET_OUI_FINAL["Voix_2"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_3"] = round(IRIS_COMPLET_OUI_FINAL["Voix_3"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_4"] = round(IRIS_COMPLET_OUI_FINAL["Voix_4"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_9"] = round(IRIS_COMPLET_OUI_FINAL["Voix_9"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)
IRIS_COMPLET_OUI_FINAL["Voix/Exprimés_11"] = round(IRIS_COMPLET_OUI_FINAL["Voix_11"]/IRIS_COMPLET_OUI_FINAL["Exprimés"]*100,2)

In [ ]:
IRIS_COMPLET_OUI_FINAL

,IRIS,commune_code,libelle,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
0,721910000,72191,Mayet,2321.0,383.0,1938.0,44.0,16.0,1878.0,81.0,522.0,310.0,82.0,302.0,498.0,4.31,27.80,16.51,4.37,16.08,26.52
1,811990000,81199,Padiès,168.0,26.0,142.0,1.0,4.0,137.0,13.0,27.0,32.0,8.0,30.0,20.0,9.49,19.71,23.36,5.84,21.90,14.60
2,592250102,59225,Feignies,881.0,217.0,664.0,10.0,3.0,651.0,32.0,282.0,98.0,30.0,124.0,59.0,4.92,43.32,15.05,4.61,19.05,9.06
3,603970000,60397,Le Mesnil-Conteville,82.0,9.0,73.0,6.0,0.0,67.0,3.0,20.0,7.0,2.0,9.0,24.0,4.48,29.85,10.45,2.99,13.43,35.82
4,383820104,38382,Saint-Égrève,1815.0,345.0,1470.0,15.0,3.0,1452.0,45.0,144.0,562.0,103.0,271.0,291.0,3.10,9.92,38.71,7.09,18.66,20.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36180,674822901,67482,Strasbourg,832.0,273.0,559.0,8.0,3.0,548.0,20.0,153.0,87.0,40.0,162.0,46.0,3.65,27.92,15.88,7.30,29.56,8.39
36181,385450101,38545,Vif,4562.0,848.0,3714.0,60.0,12.0,3642.0,209.0,997.0,860.0,250.0,603.0,606.0,5.74,27.38,23.61,6.86,16.56,16.64
36182,740630000,74063,Châtel,1019.0,187.0,832.0,11.0,3.0,818.0,43.0,185.0,89.0,17.0,42.0,407.0,5.26,22.62,10.88,2.08,5.13,49.76
36183,951010000,95101,Bray-et-Lû,626.0,110.0,516.0,10.0,5.0,501.0,35.0,189.0,95.0,36.0,86.0,49.0,6.99,37.72,18.96,7.19,17.17,9.78
36184,384030000,38403,Saint-Jean-d'Hérans,291.0,57.0,234.0,2.0,1.0,231.0,9.0,53.0,58.0,26.0,47.0,32.0,3.90,22.94,25.11,11.26,20.35,13.85

In [ ]:
IRIS_COMPLET_OUI_FINAL[IRIS_COMPLET_OUI_FINAL["libelle"]=="Les Sables-d'Olonne"]["Exprimés"].sum()

10558.0

13.515817389657132

In [ ]:
IRIS_COMPLET_2[IRIS_COMPLET_2["libelle"]=="Les Sables-d'Olonne"]

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
201,851940301,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
202,851940204,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
203,851940203,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
204,851940302,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
205,851940303,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
206,851940305,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
207,851940304,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
208,851940205,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72
209,851940105,85194,Les Sables-d'Olonne,2,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0,4.24,13.52,27.07,4.71,11.93,35.72

In [ ]:
# BV COORDONNEES IMPRECISES : IRIS_COMPLET_OUI.drop_duplicates(subset=["IRIS", "commune_code"])

In [ ]:
IRIS_COMPLET_1_2 = pd.concat([IRIS_COMPLET_1,IRIS_COMPLET_2], axis=0).drop(['Inscrits', 'Abstentions',
       'Votants', 'Blancs', 'Nuls', 'Exprimés', 'Voix_1', 'Voix_2', 'Voix_3',
       'Voix_4', 'Voix_9', 'Voix_11'], axis=1)
IRIS_COMPLET_1_2

,IRIS,commune_code,libelle,FLAG,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
0,231670000,23167,Sannat,1,4.53,14.81,26.34,7.00,21.81,19.34
1,422620000,42262,Saint-Maurice-en-Gourgois,1,6.14,37.07,19.13,5.35,12.19,16.65
2,714540000,71454,Saint-Martin-du-Mont,1,6.31,21.62,29.73,4.50,17.12,17.12
3,710410000,71041,Bois-Sainte-Marie,1,5.71,34.29,18.57,4.29,12.86,20.00
4,711410000,71041,Bois-Sainte-Marie,1,5.71,34.29,18.57,4.29,12.86,20.00
...,...,...,...,...,...,...,...,...,...,...
6800,614610000,61167,La Ferté-en-Ouche,2,6.76,29.38,16.13,3.25,11.85,28.52
6801,850740000,85135,Mareuil-sur-Lay-Dissais,2,5.01,21.23,27.45,4.37,15.25,22.44
6802,371980000,49228,Noyant-Villages,2,5.15,27.08,16.71,4.48,13.57,27.66
6803,470850000,47207,Pompiey,2,5.44,30.61,18.37,6.12,17.69,11.56
6804,352780103,35189,Montgermont,2,4.34,8.72,39.56,9.05,16.93,18.72

In [ ]:
IRIS_COMPLET_1_2["IRIS"].value_counts().shape[0]+IRIS_COMPLET_OUI_FINAL["IRIS"].value_counts().shape[0]

48590

In [ ]:
pd.concat([IRIS_COMPLET_1_2["IRIS"],IRIS_COMPLET_OUI_FINAL["IRIS"] ], axis=0).value_counts().shape[0]

48590

In [ ]:
IRIS_COMPLET_OUI_FINAL["FLAG"]=0
IRIS_COMPLET_OUI_FINAL = IRIS_COMPLET_OUI_FINAL[['IRIS', 'commune_code', 'libelle', 'FLAG', 'Inscrits', 'Abstentions', 'Votants',
       'Blancs', 'Nuls', 'Exprimés', 'Voix_1', 'Voix_2', 'Voix_3', 'Voix_4',
       'Voix_9', 'Voix_11', 'Voix/Exprimés_1', 'Voix/Exprimés_2',
       'Voix/Exprimés_3', 'Voix/Exprimés_4', 'Voix/Exprimés_9',
       'Voix/Exprimés_11']] 
IRIS_COMPLET_OUI_FINAL

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
0,721910000,72191,Mayet,0,2321.0,383.0,1938.0,44.0,16.0,1878.0,81.0,522.0,310.0,82.0,302.0,498.0,4.31,27.80,16.51,4.37,16.08,26.52
1,811990000,81199,Padiès,0,168.0,26.0,142.0,1.0,4.0,137.0,13.0,27.0,32.0,8.0,30.0,20.0,9.49,19.71,23.36,5.84,21.90,14.60
2,592250102,59225,Feignies,0,881.0,217.0,664.0,10.0,3.0,651.0,32.0,282.0,98.0,30.0,124.0,59.0,4.92,43.32,15.05,4.61,19.05,9.06
3,603970000,60397,Le Mesnil-Conteville,0,82.0,9.0,73.0,6.0,0.0,67.0,3.0,20.0,7.0,2.0,9.0,24.0,4.48,29.85,10.45,2.99,13.43,35.82
4,383820104,38382,Saint-Égrève,0,1815.0,345.0,1470.0,15.0,3.0,1452.0,45.0,144.0,562.0,103.0,271.0,291.0,3.10,9.92,38.71,7.09,18.66,20.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36180,674822901,67482,Strasbourg,0,832.0,273.0,559.0,8.0,3.0,548.0,20.0,153.0,87.0,40.0,162.0,46.0,3.65,27.92,15.88,7.30,29.56,8.39
36181,385450101,38545,Vif,0,4562.0,848.0,3714.0,60.0,12.0,3642.0,209.0,997.0,860.0,250.0,603.0,606.0,5.74,27.38,23.61,6.86,16.56,16.64
36182,740630000,74063,Châtel,0,1019.0,187.0,832.0,11.0,3.0,818.0,43.0,185.0,89.0,17.0,42.0,407.0,5.26,22.62,10.88,2.08,5.13,49.76
36183,951010000,95101,Bray-et-Lû,0,626.0,110.0,516.0,10.0,5.0,501.0,35.0,189.0,95.0,36.0,86.0,49.0,6.99,37.72,18.96,7.19,17.17,9.78
36184,384030000,38403,Saint-Jean-d'Hérans,0,291.0,57.0,234.0,2.0,1.0,231.0,9.0,53.0,58.0,26.0,47.0,32.0,3.90,22.94,25.11,11.26,20.35,13.85

In [ ]:
#AJOUTER CANDIDAT
for k in [IRIS_COMPLET_OUI_FINAL,IRIS_COMPLET_1_2 ]:
    
    k['Nom_1']="DUPONT-AIGNAN";k['Prénom_1']="Nicolas"
    k['Nom_2']="LE PEN";k['Prénom_2']="Marine"
    k['Nom_3']="MACRON";k['Prénom_3']="Emmanuel"
    k['Nom_4']="HAMON";k['Prénom_4']="Benoît"
    k['Nom_9']="MÉLENCHON"; k['Prénom_9']="Jean-Luc"
    k['Nom_11']="FILLON";k['Prénom_11']="François"

<ipython-input-98-4d9bd4281377>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_1']="DUPONT-AIGNAN";k['Prénom_1']="Nicolas"
<ipython-input-98-4d9bd4281377>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_2']="LE PEN";k['Prénom_2']="Marine"
<ipython-input-98-4d9bd4281377>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_3']="MACRON";k['Prénom_3']="Emmanuel"
<ipython-input-98-4d9bd4281377>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_4']="HAMON";k['Prénom_4']="Benoît"
<ipython-input-98-4d9bd4281377>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_9']="MÉLENCHON"; k['Prénom_9']="Jean-Luc"
<ipython-input-98-4d9bd4281377>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  k['Nom_11']="FILLON";k['Prénom_11']="François"

In [ ]:
IRIS_COMPLET_1_2.columns

Index(['IRIS', 'commune_code', 'libelle', 'FLAG', 'Voix/Exprimés_1',
       'Voix/Exprimés_2', 'Voix/Exprimés_3', 'Voix/Exprimés_4',
       'Voix/Exprimés_9', 'Voix/Exprimés_11', 'Nom_1', 'Prénom_1', 'Nom_2',
       'Prénom_2', 'Nom_3', 'Prénom_3', 'Nom_4', 'Prénom_4', 'Nom_9',
       'Prénom_9', 'Nom_11', 'Prénom_11'],
      dtype='object')

In [ ]:
IRIS_COMPLET_OUI_FINAL = IRIS_COMPLET_OUI_FINAL[['IRIS', 'commune_code', 'libelle', 'FLAG', 'Inscrits', 'Abstentions',
       'Votants', 'Blancs', 'Nuls', 'Exprimés', 'Nom_1', 'Prénom_1', 'Voix_1', 'Nom_2', 'Prénom_2', 'Voix_2', 'Nom_3',
       'Prénom_3', 'Voix_3',
        'Nom_4', 'Prénom_4','Voix_4', 'Nom_9', 'Prénom_9','Voix_9', 'Nom_11',
       'Prénom_11', 'Voix_11', 'Voix/Exprimés_1', 'Voix/Exprimés_2',
       'Voix/Exprimés_3', 'Voix/Exprimés_4', 'Voix/Exprimés_9',
       'Voix/Exprimés_11']]

In [ ]:
IRIS_COMPLET_1_2 = IRIS_COMPLET_1_2[['IRIS', 'commune_code', 'libelle', 'FLAG',  'Nom_1', 'Prénom_1', 'Voix/Exprimés_1',
       'Nom_2','Prénom_2','Voix/Exprimés_2', 'Nom_3', 'Prénom_3', 'Voix/Exprimés_3', 'Nom_4', 'Prénom_4', 'Voix/Exprimés_4',
       'Nom_9','Prénom_9','Voix/Exprimés_9',  'Nom_11', 'Prénom_11', 'Voix/Exprimés_11']]

In [ ]:
FINAL_POURCENTAGE =pd.concat([IRIS_COMPLET_OUI_FINAL[IRIS_COMPLET_1_2.columns], IRIS_COMPLET_1_2], axis=0)

In [ ]:
#ENREGISTREMENT
IRIS_COMPLET_OUI_FINAL.to_csv("C:/Users/Christian/Desktop/IRIS_BV_final/PRESIDENTIELLES/IRIS_FLAG_0_INSCRITS_POURCENTAGE.txt",sep=";", index=False)
IRIS_COMPLET_1_2.to_csv("C:/Users/Christian/Desktop/IRIS_BV_final/PRESIDENTIELLES/IRIS_FLAG_1_2_POURCENTAGE.txt",sep=";", index=False)
FINAL_POURCENTAGE.to_csv("C:/Users/Christian/Desktop/IRIS_BV_final/PRESIDENTIELLES/IRIS_FINAL_POURCENTAGE_1_TOUR.txt",sep=";", index=False)

In [ ]:
(275.0+83.0)/(1096.0+281.0)*100

25.998547567175017

In [ ]:
IRIS_COMPLET_OUI_FINAL[IRIS_COMPLET_OUI_FINAL["commune_code"]=="85194"]

,IRIS,commune_code,libelle,FLAG,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Nom_1,Prénom_1,Voix_1,Nom_2,Prénom_2,Voix_2,Nom_3,Prénom_3,Voix_3,Nom_4,Prénom_4,Voix_4,Nom_9,Prénom_9,Voix_9,Nom_11,Prénom_11,Voix_11,Voix/Exprimés_1,Voix/Exprimés_2,Voix/Exprimés_3,Voix/Exprimés_4,Voix/Exprimés_9,Voix/Exprimés_11
5215,851940103,85194,Les Sables-d'Olonne,0,2263.0,457.0,1806.0,17.0,7.0,1782.0,DUPONT-AIGNAN,Nicolas,71.0,LE PEN,Marine,209.0,MACRON,Emmanuel,534.0,HAMON,Benoît,91.0,MÉLENCHON,Jean-Luc,212.0,FILLON,François,625.0,3.98,11.73,29.97,5.11,11.90,35.07
16069,851940101,85194,Les Sables-d'Olonne,0,1196.0,242.0,954.0,6.0,5.0,943.0,DUPONT-AIGNAN,Nicolas,28.0,LE PEN,Marine,103.0,MACRON,Emmanuel,240.0,HAMON,Benoît,38.0,MÉLENCHON,Jean-Luc,82.0,FILLON,François,421.0,2.97,10.92,25.45,4.03,8.70,44.64
19601,851940106,85194,Les Sables-d'Olonne,0,3555.0,785.0,2770.0,48.0,24.0,2698.0,DUPONT-AIGNAN,Nicolas,121.0,LE PEN,Marine,422.0,MACRON,Emmanuel,754.0,HAMON,Benoît,143.0,MÉLENCHON,Jean-Luc,329.0,FILLON,François,834.0,4.48,15.64,27.95,5.30,12.19,30.91
21095,851940104,85194,Les Sables-d'Olonne,0,4476.0,1088.0,3388.0,36.0,20.0,3332.0,DUPONT-AIGNAN,Nicolas,157.0,LE PEN,Marine,489.0,MACRON,Emmanuel,855.0,HAMON,Benoît,144.0,MÉLENCHON,Jean-Luc,418.0,FILLON,François,1176.0,4.71,14.68,25.66,4.32,12.55,35.29
26942,851940201,85194,Les Sables-d'Olonne,0,1174.0,285.0,889.0,11.0,3.0,875.0,DUPONT-AIGNAN,Nicolas,34.0,LE PEN,Marine,119.0,MACRON,Emmanuel,246.0,HAMON,Benoît,42.0,MÉLENCHON,Jean-Luc,113.0,FILLON,François,302.0,3.89,13.60,28.11,4.80,12.91,34.51
30255,851940102,85194,Les Sables-d'Olonne,0,1226.0,281.0,945.0,11.0,6.0,928.0,DUPONT-AIGNAN,Nicolas,37.0,LE PEN,Marine,85.0,MACRON,Emmanuel,229.0,HAMON,Benoît,39.0,MÉLENCHON,Jean-Luc,106.0,FILLON,François,413.0,3.99,9.16,24.68,4.20,11.42,44.50

In [ ]:
87.0/1738.0*100

5.005753739930955

In [ ]:
IRIS_COMPLET_1_2[IRIS_COMPLET_1_2["commune_code"]=="85194"] # Saint-Martin-du-Mont

,IRIS,commune_code,libelle,FLAG,Nom_1,Prénom_1,Voix/Exprimés_1,Nom_2,Prénom_2,Voix/Exprimés_2,Nom_3,Prénom_3,Voix/Exprimés_3,Nom_4,Prénom_4,Voix/Exprimés_4,Nom_9,Prénom_9,Voix/Exprimés_9,Nom_11,Prénom_11,Voix/Exprimés_11
201,851940301,85194,Les Sables-d'Olonne,2,DUPONT-AIGNAN,Nicolas,4.24,LE PEN,Marine,13.52,MACRON,Emmanuel,27.07,HAMON,Benoît,4.71,MÉLENCHON,Jean-Luc,11.93,FILLON,François,35.72
202,851940204,85194,Les Sables-d'Olonne,2,DUPONT-AIGNAN,Nicolas,4.24,LE PEN,Marine,13.52,MACRON,Emmanuel,27.07,HAMON,Benoît,4.71,MÉLENCHON,Jean-Luc,11.93,FILLON,François,35.72
203,851940203,85194,Les Sables-d'Olonne,2,DUPONT-AIGNAN,Nicolas,4.24,LE PEN,Marine,13.52,MACRON,Emmanuel,27.07,HAMON,Benoît,4.71,MÉLENCHON,Jean-Luc,11.93,FILLON,François,35.72
204,851940302,85194,Les Sables-d'Olonne,2,DUPONT-AIGNAN,Nicolas,4.24,LE PEN,Marine,13.52,MACRON,Emmanuel,27.07,HAMON,Benoît,4.71,MÉLENCHON,Jean-Luc,11.93,FILLON,François,35.72
205,851940303,85194,Les Sables-d'Olonne,2,DUPONT-AIGNAN,Nicolas,4.24,LE PEN,Marine,13.52,MACRON,Emmanuel,27.07,HAMON,Benoît,4.71,MÉLENCHON,Jean-Luc,11.93,FILLON,François,35.72
206,851940305,85194,Les Sables-d'Olonne,2,DUPONT-AIGNAN,Nicolas,4.24,LE PEN,Marine,13.52,MACRON,Emmanuel,27.07,HAMON,Benoît,4.71,MÉLENCHON,Jean-Luc,11.93,FILLON,François,35.72
207,851940304,85194,Les Sables-d'Olonne,2,DUPONT-AIGNAN,Nicolas,4.24,LE PEN,Marine,13.52,MACRON,Emmanuel,27.07,HAMON,Benoît,4.71,MÉLENCHON,Jean-Luc,11.93,FILLON,François,35.72
208,851940205,85194,Les Sables-d'Olonne,2,DUPONT-AIGNAN,Nicolas,4.24,LE PEN,Marine,13.52,MACRON,Emmanuel,27.07,HAMON,Benoît,4.71,MÉLENCHON,Jean-Luc,11.93,FILLON,François,35.72
209,851940105,85194,Les Sables-d'Olonne,2,DUPONT-AIGNAN,Nicolas,4.24,LE PEN,Marine,13.52,MACRON,Emmanuel,27.07,HAMON,Benoît,4.71,MÉLENCHON,Jean-Luc,11.93,FILLON,François,35.72

In [ ]:
IRIS_COMPLET_1_2

,IRIS,commune_code,libelle,FLAG,Nom_1,Prénom_1,Voix/Exprimés_1,Nom_2,Prénom_2,Voix/Exprimés_2,Nom_3,Prénom_3,Voix/Exprimés_3,Nom_4,Prénom_4,Voix/Exprimés_4,Nom_9,Prénom_9,Voix/Exprimés_9,Nom_11,Prénom_11,Voix/Exprimés_11
0,231670000,23167,Sannat,1,DUPONT-AIGNAN,Nicolas,4.53,LE PEN,Marine,14.81,MACRON,Emmanuel,26.34,HAMON,Benoît,7.00,MÉLENCHON,Jean-Luc,21.81,FILLON,François,19.34
1,422620000,42262,Saint-Maurice-en-Gourgois,1,DUPONT-AIGNAN,Nicolas,6.14,LE PEN,Marine,37.07,MACRON,Emmanuel,19.13,HAMON,Benoît,5.35,MÉLENCHON,Jean-Luc,12.19,FILLON,François,16.65
2,714540000,71454,Saint-Martin-du-Mont,1,DUPONT-AIGNAN,Nicolas,6.31,LE PEN,Marine,21.62,MACRON,Emmanuel,29.73,HAMON,Benoît,4.50,MÉLENCHON,Jean-Luc,17.12,FILLON,François,17.12
3,710410000,71041,Bois-Sainte-Marie,1,DUPONT-AIGNAN,Nicolas,5.71,LE PEN,Marine,34.29,MACRON,Emmanuel,18.57,HAMON,Benoît,4.29,MÉLENCHON,Jean-Luc,12.86,FILLON,François,20.00
4,711410000,71041,Bois-Sainte-Marie,1,DUPONT-AIGNAN,Nicolas,5.71,LE PEN,Marine,34.29,MACRON,Emmanuel,18.57,HAMON,Benoît,4.29,MÉLENCHON,Jean-Luc,12.86,FILLON,François,20.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6800,614610000,61167,La Ferté-en-Ouche,2,DUPONT-AIGNAN,Nicolas,6.76,LE PEN,Marine,29.38,MACRON,Emmanuel,16.13,HAMON,Benoît,3.25,MÉLENCHON,Jean-Luc,11.85,FILLON,François,28.52
6801,850740000,85135,Mareuil-sur-Lay-Dissais,2,DUPONT-AIGNAN,Nicolas,5.01,LE PEN,Marine,21.23,MACRON,Emmanuel,27.45,HAMON,Benoît,4.37,MÉLENCHON,Jean-Luc,15.25,FILLON,François,22.44
6802,371980000,49228,Noyant-Villages,2,DUPONT-AIGNAN,Nicolas,5.15,LE PEN,Marine,27.08,MACRON,Emmanuel,16.71,HAMON,Benoît,4.48,MÉLENCHON,Jean-Luc,13.57,FILLON,François,27.66
6803,470850000,47207,Pompiey,2,DUPONT-AIGNAN,Nicolas,5.44,LE PEN,Marine,30.61,MACRON,Emmanuel,18.37,HAMON,Benoît,6.12,MÉLENCHON,Jean-Luc,17.69,FILLON,François,11.56
6804,352780103,35189,Montgermont,2,DUPONT-AIGNAN,Nicolas,4.34,LE PEN,Marine,8.72,MACRON,Emmanuel,39.56,HAMON,Benoît,9.05,MÉLENCHON,Jean-Luc,16.93,FILLON,François,18.72

In [ ]:
IRIS_COMPLET_1_2[IRIS_COMPLET_1_2['FLAG']==2]

,IRIS,commune_code,libelle,FLAG,Nom_1,Prénom_1,Voix/Exprimés_1,Nom_2,Prénom_2,Voix/Exprimés_2,Nom_3,Prénom_3,Voix/Exprimés_3,Nom_4,Prénom_4,Voix/Exprimés_4,Nom_9,Prénom_9,Voix/Exprimés_9,Nom_11,Prénom_11,Voix/Exprimés_11
0,900100201,90010,Belfort,2,DUPONT-AIGNAN,Nicolas,3.68,LE PEN,Marine,20.31,MACRON,Emmanuel,21.65,HAMON,Benoît,7.71,MÉLENCHON,Jean-Luc,23.32,FILLON,François,18.57
1,900100502,90010,Belfort,2,DUPONT-AIGNAN,Nicolas,3.68,LE PEN,Marine,20.31,MACRON,Emmanuel,21.65,HAMON,Benoît,7.71,MÉLENCHON,Jean-Luc,23.32,FILLON,François,18.57
2,900100102,90010,Belfort,2,DUPONT-AIGNAN,Nicolas,3.68,LE PEN,Marine,20.31,MACRON,Emmanuel,21.65,HAMON,Benoît,7.71,MÉLENCHON,Jean-Luc,23.32,FILLON,François,18.57
3,900100203,90010,Belfort,2,DUPONT-AIGNAN,Nicolas,3.68,LE PEN,Marine,20.31,MACRON,Emmanuel,21.65,HAMON,Benoît,7.71,MÉLENCHON,Jean-Luc,23.32,FILLON,François,18.57
4,900100501,90010,Belfort,2,DUPONT-AIGNAN,Nicolas,3.68,LE PEN,Marine,20.31,MACRON,Emmanuel,21.65,HAMON,Benoît,7.71,MÉLENCHON,Jean-Luc,23.32,FILLON,François,18.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6800,614610000,61167,La Ferté-en-Ouche,2,DUPONT-AIGNAN,Nicolas,6.76,LE PEN,Marine,29.38,MACRON,Emmanuel,16.13,HAMON,Benoît,3.25,MÉLENCHON,Jean-Luc,11.85,FILLON,François,28.52
6801,850740000,85135,Mareuil-sur-Lay-Dissais,2,DUPONT-AIGNAN,Nicolas,5.01,LE PEN,Marine,21.23,MACRON,Emmanuel,27.45,HAMON,Benoît,4.37,MÉLENCHON,Jean-Luc,15.25,FILLON,François,22.44
6802,371980000,49228,Noyant-Villages,2,DUPONT-AIGNAN,Nicolas,5.15,LE PEN,Marine,27.08,MACRON,Emmanuel,16.71,HAMON,Benoît,4.48,MÉLENCHON,Jean-Luc,13.57,FILLON,François,27.66
6803,470850000,47207,Pompiey,2,DUPONT-AIGNAN,Nicolas,5.44,LE PEN,Marine,30.61,MACRON,Emmanuel,18.37,HAMON,Benoît,6.12,MÉLENCHON,Jean-Luc,17.69,FILLON,François,11.56
6804,352780103,35189,Montgermont,2,DUPONT-AIGNAN,Nicolas,4.34,LE PEN,Marine,8.72,MACRON,Emmanuel,39.56,HAMON,Benoît,9.05,MÉLENCHON,Jean-Luc,16.93,FILLON,François,18.72

In [ ]:
somme_commune[somme_commune["commune_code"]=="85194"]

,commune_code,Inscrits,Abstentions,Votants,Blancs,Nuls,Exprimés,Voix_1,Voix_2,Voix_3,Voix_4,Voix_9,Voix_11
33212,85194,13890.0,3138.0,10752.0,129.0,65.0,10558.0,448.0,1427.0,2858.0,497.0,1260.0,3771.0

In [ ]:
448.0/10558.0*100

4.243227884068952

In [ ]:
657.0/17846.0*100

3.6814972542866746